### ISSUE TITLE
Spin texture during Magnetization reversal

### ISSUE THREAD

**Issue by ahsu83** [ubermag/help#100]
Hi,

How I can have texture visualization at each value of magnetic during magnetization reversal? Like can I make an interactive figure with a slider that shows the change of the magnetic field and we can visualize the spin texture. Mumax gives the option save(m) at each field. How we can do it in ubermag?

do we need to add something in for loop?

for B_applied in B_array:
      system.energy.zeeman.H = (0, B_applied * 10**(-3) / mm.consts.mu0, 0)
      md.drive(system)
      my.append(system.m.orientation.y.average)

Kind Regrads,

**Comment by marijanbeg** [comment]
Hi @ahsu83, thank you for your question. Each time you drive the system, the final magnetisation state is saved. You can analyse it using `micromagneticdata` package by varying the drive number. For instance:

```
import micromagneticdata as md
data = md.Data(system.name)
@df.interact(n=data.selector())
def interactive_plot(nstep):
    data.drive(n).m.plane('z').mpl()
```

**Comment by ahsu83** [comment]
@marijanbeg Got it. Thank you very much. :)

**Comment by marijanbeg** [comment]
Thank you @ahsu83 for closing this issue. I kept it open on purpose as a reminder to write a dedicated tutorial on this topic.

**Comment by marijanbeg** [comment]
Hi @ahsu83, thank you so much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/hysteresis.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.

**Comment by ahsu83** [comment]
@marijanbeg Thanks :)
