### ISSUE TITLE
How to set the colorbar to be based on all directions instead of just the Z component

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#101]
Dear Ubermag Team,
When I was mapping the magnetic moment distribution, I found that ````discretisedfield.Field.quiver()```` can specify X, Y, U, V as its transfer parameters, but I don't know how to view the specific data. Usually when I draw a picture, I just use ````mpl_scalar()```` or````mpl_vector()````directly as you said in your tutorial, I use cmap to select the color bar, and the figure is as follows
![image](https://user-images.githubusercontent.com/61874432/103145569-edb9f700-4777-11eb-8078-f53a040d9168.png)

But sometimes I want to draw a picture of the color changing with the angle of the magnetic moment, as shown in the figure below. Can you tell me how to draw such a picture? This picture comes from your published article:) https://doi.org/10.1002/adma.201806598

![image](https://user-images.githubusercontent.com/61874432/103145703-6bcacd80-4779-11eb-8d0f-d62cb61c732e.png)

Thank you for your help! Looking forward to your reply!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. The trick is to compute the angle before plotting. For instance:
```
system.m.plane('z').angle.mpl()
```

I hope this answers your question. If not, please feel free to reopen this issue.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you very much for your help! I used ````angle````, but there was a gap between the picture and what I expected.I used the following code to plot````data.drive(34).step(0).plane(z=1e-9).angle.mpl_scalar(filter_field=data.drive(34).step(0).z,cmap='jet')````.The picture is shown below.
![image](https://user-images.githubusercontent.com/61874432/103254586-d3bf2500-49c0-11eb-997f-06f3760c7631.png)


I checked the API of discrete field and found that the syntax is applicable to the angle between the plane component and the horizontal axis. However, I hope to draw the same graph as in your article, which can reflect the changes of XYZ in three directions.The component color distribution I want is the color distribution as shown in the figure below.
![image](https://user-images.githubusercontent.com/61874432/103254651-1ed93800-49c1-11eb-9e1e-330ebdde1070.png)

Can you tell me how to implement such a graph? Is my colorbar wrong? Thank you again for your patient help!
