### ISSUE TITLE
How to set the colorbar to be based on all directions instead of just the Z component

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#103]
#101 
@marijanbeg, Sorry, I can't reopen the question #101. I can only create a new question. I copy the question as follows:
Thank you very much for your help! I used ````angle````, but there was a gap between the picture and what I expected.I used the following code to plot````data.drive(34).step(0).plane(z=1e-9).angle.mpl_scalar(filter_field=data.drive(34).step(0).z,cmap='jet')````.The picture is shown below.
![image](https://user-images.githubusercontent.com/61874432/103254586-d3bf2500-49c0-11eb-997f-06f3760c7631.png)

I checked the API of discrete field and found that the syntax is applicable to the angle between the plane component and the horizontal axis. However, I hope to draw the same graph as in your article, which can reflect the changes of XYZ in three directions.The component color distribution I want is the color distribution as shown in the figure below.
![image](https://user-images.githubusercontent.com/61874432/103254651-1ed93800-49c1-11eb-9e1e-330ebdde1070.png)

Can you tell me how to implement such a graph? Is my colorbar wrong? Thank you again for your patient help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you very much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/angle-hls-plot.ipynb

We are still working on adjusting the colorbar, but this is a non-trivial issue.

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.

**Comment by code-whale** [comment]
@marijanbeg, Thank you very much for your help with all the questions I have raised! Thank you and ubermag team for their efforts! I believe it will become the best micro magnetic software!
