### ISSUE TITLE
DMI_Cnv crystal class installation in OOMMF

### ISSUE THREAD

**Issue by Harry-09** [ubermag/help#104]
Does DMI_Cnv class extensions for OOMMF are supported by windows?If so please guide me for installing it, as I'm getting errors as below
![image](https://user-images.githubusercontent.com/59189839/104313827-9c8f5e80-54fe-11eb-88de-48bd7d9916dc.png)
I tried to install using the steps described in this [ https://github.com/joommf/oommf-extension-dmi-cnv](url)
while installing the extension.

Thanks in Advance !!!

**Comment by marijanbeg** [comment]
Hi @Harry-09, thank you for your question. We do not support it on Windows. However, if you want to use it on Windows, you can via Docker: https://github.com/ubermag/workshop/blob/master/tutorials/choosing-runner.ipynb
