### ISSUE TITLE
Initializing Triangular Geometry

### ISSUE THREAD

**Issue by Harry-09** [ubermag/help#107]
Hi, 
I wish to drive hysteresis for a  equilateral triangle, however I couldn't able to initialize the geometry as i'm very poor in programming and still confused with various aspects of it. Please help me in creating and learn from it. I wish to initialize a triangle with lateral size of L=100nm. It will be of great help to my research.

Thanks in advance!!!

**Comment by marijanbeg** [comment]
Hi @Harry-09, thank you for your question. Please have a look at the attached file - I made a quick tutorial. Please feel free to expand it and make it more general. You can then send it back to us and we can make it part of our tutorials (and acknowledge you as the contributor).

[traingle.pdf](https://github.com/ubermag/help/files/5835886/traingle.pdf)

The main trick is to identify the points of the triangle and define lines (https://mathworld.wolfram.com/Two-PointForm.html).

**Comment by Harry-09** [comment]
Thank you @marijanbeg so much for your input and help. I wish to implement the geometry a more general case and will send you once i make it complete.

**Comment by marijanbeg** [comment]
Thank you @Harry-09. We are really interested in having more contributions from the community. You all have interesting use cases other users would find interesting. This is why we invite all users to create tutorials (however small) to demonstrate what they are doing.
