### ISSUE TITLE
Support for OOMMF evolver thetaevolve

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#109]
Dear Ubermag Team, In the previous question, I saw that someone expected to add the temperature parameter to ubermag, and there was a term about ````system.T```` in mm API, so I wanted to install the OOMMF extension module the thetaevolve myself. So I checked miniconda3 / envs / ubermag / opt / OOMMF / APP / oxs / local and found that it already contains the thetaevolve file as shown in the figure below. So how do you call the solver to add temperature to ubermag? ‘
![image](https://user-images.githubusercontent.com/61874432/106701131-25db1200-6621-11eb-94d6-7cff98912ed6.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. We do not support ThetaEvolve at the moment - this is on our todo-list. I am going to keep this issue open to remind us.

**Comment by marijanbeg** [comment]
To consider for the next release (@lang-m).

**Comment by lang-m** [comment]
ThetaEvolve will be available in the next release.

**Comment by lang-m** [comment]
`ThetaEvolver` is available in Ubermag 0.60.0 (https://ubermag.github.io/changelog.html, https://ubermag.github.io/documentation/ipynb/oommfc/finite-temperature.html).
