### ISSUE TITLE
Importing cell structures to oommfc

### ISSUE THREAD

**Issue by kannanum** [ubermag/help#11]
Dear All,
                  I am a  new user to oommfc. I am trying to import an autocad image file to oommfc. bascially, this image will be the device structure which i have to subdivide into various materials for further simulation. can anyone help me with importing such an image to oommfc. any document related to this would be of great help. thanks in advance

**Comment by mb1a15** [comment]
Hi,

Thank you for your question. Could you please provide more details about the AutoCAD image you want to import? Is it a bitmap figure or some AutoCAD specific file?

**Comment by kannanum** [comment]
Hi,
         Thanks for the response. Default cad file formats are .dwg and .dxf but bitmap figure is also possible. I guess any generic image format is fine as long as it works with oommfc.

**Comment by marijanbeg** [comment]
We still do not have implemented the mesh creation from bitmaps. It would be helpful if you can provide us a use case to help us understand what you need exactly and then we can see if that can be implemented.

**Comment by marijanbeg** [comment]
Hi @kannanum, is this issue something that still concerns you. If yes, could you please provide us a more detailed example of what you are trying to implement.

**Comment by kannanum** [comment]
Hi marijanbeg
Apologies for the late reply. I had synthesized a binary magnetic alloy material. I wanted to record the local SEM image of the material at some point and create an exact copy of the SEM image in any image processing software like AutoCAD or Corel draw etc. Finally this image will be taken to oommfc where the different regions in the image ( as seen in SEM also) will be attributed the corresponding material properties. the rest of the work could be just the calculation part where one could generate the domain structure or any such micromagnetic calculations. 
Thanks 
Kannan

**Comment by marijanbeg** [comment]
Defining a mesh from an image is not covered by Ubermag's functionality.
