### ISSUE TITLE
Current distribution map

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#113]
Hello,

I've modeled a ferromagnetic nano-disk and injected  in-plane spin current. 

"system.m.z.plane('z').mpl()" displays the change in magnetization. In addition, I wish to see distribution map of current injected.

How to visualize the distribution of current injected in a ferromagnetic material?

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, thank you for your question. Can you please let us know how you defined that term? Depending on that, we can help you visualise it.

**Comment by Ponsudana** [comment]
Hi @marijanbeg 

Reference Image: https://www.nature.com/articles/s41598-018-34934-2/figures/1 
(c) Distribution map of the spin current density
![Current Distribution map](https://user-images.githubusercontent.com/43433451/110281333-8aafd080-8002-11eb-8e5d-52a0ff268bc8.png)

A ferromagnetic nanodisk is defined as,
**_def Ms_fun(pos):
    x, y, z = pos
    if ((x)**2 + (y)**2)**0.5 < 60e-9:
        return Ms
    else:
        return 0      
system.m = df.Field(mesh, value=(0, 0, 1), norm=Ms_fun, dim=3)_**

When an in-plane spin current is applied for 1ns, 
**_ux=100
beta=0.05
system.dynamics+= oc.ZhangLi(u=ux, beta=beta)
td = oc.TimeDriver()
td.drive(system, t=1e-9, n=200)
system.m.z.plane('z').mpl()_**

For this defined system, how to visualize the distribution of current in a nanodisk?

Thank you for all the support.

**Comment by fangohr** [comment]
The computation of the spatial current distribution as a function of geometry or local resistivity is not normally done within micromagnetic packages. Even more so the spin current density.  

If you need a detailed computation of the current distribution this feature, you may want to look  for 'multi physics simulations' - this term is used occasionally to refer to the simulation of multiple degrees of freedom (such as magnetisation AND current distribution).

Claas Abert and co-workers have described such a model some years ago: https://www.nature.com/articles/srep14855

**Comment by Ponsudana** [comment]
Thank you @fangohr
