### ISSUE TITLE
Saving computational power in 'empty' regions

### ISSUE THREAD

**Issue by n-loo** [ubermag/help#114]
Hi!

I'm running a fairly large hysteresis simulation with many regions (a chain of 5 magnetic nano particles each with 12 regions). This is an image showing the regions so you can get an idea of what they look like. There is a variable spacing in between each nano particle. 
![image](https://user-images.githubusercontent.com/45517947/109709997-22c53a00-7b6b-11eb-9861-ac941a3ea4c4.png)
I have the spacing in between all of the regions as a region called 'interspace' with the properties  `A=0`, `u=(1,0,0)` , `norm=0`. 

My issue is when I set a very large spacing it takes significantly more time to run the hysteresis loop. I assume this is because there ends up being a lot of 'empty' discretization cells which take a lot of computational time to merely produce the same result with no magnetization in those regions when running a hysteresis driver. 

Is there a way in Ubermag to set this interspace region (which has no magnetization) so that the magnetization does not have to be recalculated (because it will just be 0 again) in each step of the hysteresis loop?

Best,
Niels

**Comment by fangohr** [comment]
Thanks for the issue and nice image to illustrate what you are doing. 

Short answer: What you are asking for is not possible with OOMMF (and not with Mumax3 either, I think). 

More details: The origin of the intensive computation is the demagnetisation field calculation. This is essentially a convolution of a geometric kernel encoding the distances from simulation cells relative to each other with the magnetisation. This is computationally very intense. The way most packages work around this is by carrying out the convolution in Fourier space (where it is just a multiplication). However, to get to Fourier space and back, you need a Fouriertransform which tends to be expensive as well. Fortunatetly, using equidistant finite difference discretisation, one can use the Fast Fourier Transform. This is the standard method. In this standard method, you need to enclose all magnetic objects in a cuboid, and do the Fourier transform on the whole cuboidal region. This includes the ‘empty’ cells  (where Ms=0). Check out slides 9 and 10 in this talk by Mike Donahue https://math.nist.gov/~MDonahue/talks/bonn2006-staircase-errata20070116.pdf The original publication for this is from Newell, Williams and Dunlop (https://doi.org/10.1029/93JB00694)

You can also compute the demag field based on a magnetic scalar potential - this is commonly done in finite element micromagnetic simulators. In those, you can do the computation excluding the empty regions. This is known as the hybrid finite-element-boundary-element method by Fredkin and Koehler. (https://www.scinapse.io/papers/2116553152) They have other issues, though, for example need of large memory if you have many surface triangles in the mesh.

Coming back to your particular problem: the 'empty' regions seem quite small (if I understand your plot correctly), so I would guess the major computational effort comes from the filled cells, and there is no easy way to make your simulation faster, and it doesn't seem worth the effort considering going to finite elements.

**Comment by n-loo** [comment]
Thanks for the thorough answer Hans!

The image here does indeed have a small amount of 'empty' regions so it runs quite quickly, the performance issue was when I was running it with much larger spacing (200nm+ spacing between each 66nm particle, shown here it is only 2nm spacing). It seems like my best option might be to just wait out the computation, but these resources are great.

**Comment by fangohr** [comment]
I see. If you feel adventurous, you could look into tools like finmag (https://github.com/fangohr/finmag) or nmag. These are finite element based and may be more efficient for the problems with lots of space. But it is a steeper learning curve than finite difference micromagnetics, and there is no support for those packages.
