### ISSUE TITLE
UniaxialAnisotropy Field? 

### ISSUE THREAD

**Issue by Namico745** [ubermag/help#115]
Hello Ubermag! 

Currently using the OOMMFC module on python, thank you for all the work you've done in making it! 

I see on the NIST website for Oxs_UniaxialAnisotropy term, they allow the use of an anisotropy field rather than crystalline anisotropy constant. I'm wondering if you can provide any advice on how to get the field to be introduced within the python script? Any help you can provide would be greatly appreciated. 

Kind Regards

**Comment by marijanbeg** [comment]
Hi @Namico745, thank you for your question. Spatially varying parameters can be defined using `discretisedfield.Field` objects or dictionaries. For details, please refer to the following two tutorials:

- https://github.com/ubermag/workshop/blob/master/tutorials/spatially-varying-parameters1.ipynb
- https://github.com/ubermag/workshop/blob/master/tutorials/spatially-varying-parameters2.ipynb

I hope this answers your question. If not, please let us know.
