### ISSUE TITLE
Calculate the area surrounded by hysteresis loops

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#116]
Dear Ubermag Team,
I would like to try to calculate the area surrounded by hysteresis loops, or is there any way to calculate the area difference between the two hysteresis loops shown in the following figure? If so, can you teach me how to write code? Thank you very much for your help all the time!
![image](https://user-images.githubusercontent.com/61874432/109948649-7ffcef00-7d15-11eb-90e2-666d3fe17b55.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your interesting question. Probably the easiest way to compute this is by subtracting the areas between two "branches" of the hysteresis loop. To compute the area under the curve, you can have a look at some `scipy` functions (https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html).

Please give it a go and we can help if you get stuck at some point. In addition, this would be an interesting tutorial for other users, so if you could make an example tutorial, we can make it part of our documentation (and acknowledge your support).

I am going to keep this issue open until it is resolved.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you very much for your help! I am not in-depth in the study of scipy, but I think of another way to calculate the area, that is, take the area surrounded by four points as shown in the following figure to calculate, and then use the for loop to overlay. This method may not be the best choice. Please forgive me for my limited ability in math and computational science. It would be great if you could tell me a better way. At the same time, I enclose my code and ask you to help check whether my code is correct. Thank you again for your patient help. The data in the code is taken from your hysteresis tutorial.
Through this method, I think it should be possible to calculate the area. My original intention of asking this question is to show that the hysteresis losses of different materials are different by comparing the magnetic field loops. And this difference can be reflected more specifically by calculating the area. If my idea is wrong, please criticize and correct it.
![image](https://user-images.githubusercontent.com/61874432/110067613-0e717f00-7daf-11eb-9833-09ae658e3106.png)

````Area=[]
for i in range(1,20):
    A=system.table.data['mz'][i-1]
    B=system.table.data['mz'][41-i]
    C=system.table.data['mz'][i]
    D=system.table.data['mz'][40-i]
    H=100
    S=(abs(A-B)+abs(C-D))*H/2
    Area.append(S)
    
print(Area)
total = 0
for ele in range(0, len(Area)):
    total = total + Area[ele]
    
print("The total area is:", total)
````

In addition, when I used the data in your tutorial, I found a small problem (or maybe I misunderstood it), which is your description in the document shown in the following figure: step=0.2T, and I observed that you set n=21, so I think step should be 0.1T, if I understand it wrong, please ignore this paragraph:)
![image](https://user-images.githubusercontent.com/61874432/110068495-d703d200-7db0-11eb-9bbb-f48ee1ab77be.png)

**Comment by code-whale** [comment]
Sorry, the code in the previous reply should be ````Area= []```` on the first line, followed by the for loop statement.

**Comment by fangohr** [comment]
Regarding the integration, you can use the 'composite trapezoidal rule' for  numeric integration (see for example https://en.wikipedia.org/wiki/Trapezoidal_rule) to estimate the area under the curve.

**Comment by code-whale** [comment]
@fangohr ,Thank you very much for your help. In the above code, I approximately calculate the area with the help of the trapezoid method, but it is indeed a bit crude in the code expression. I use A-B,C-D to represent the upper and lower bottom of the trapezoid, and H is the step size of hysteresis, which represents the height of the trapezoid, so that I can get a 'small trapezoid' area, and then I use the for loop sentence to transfer the area of each trapezoid to an empty list. Finally, the sum of the list to get an approximate total area, this method should be similar to the meaning expressed in the link you gave me (if I do not understand correctly, please correct) Thank you again for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your patience. I made a small example notebook with a "fake" hysteresis loop as an example of how you can compute the hysteresis loop area using the trapezoidal rule as @fangohr suggested. Please let me know if anything does not make sense.

We would be very grateful if you could combine this notebook with a real hysteresis loop in a single tutorial so we can make it part of official Ubermag documentation and acknowledge your great contribution.

[hysteresis-loop-area.ipynb.zip](https://github.com/ubermag/help/files/6104484/hysteresis-loop-area.ipynb.zip)

**Comment by code-whale** [comment]
@marijanbeg,Thanks for your help! I learned your code and tried to calculate the area of the hysteresis loop. I used your code and my own code to calculate the area of the same hysteresis loop in the attached file, and the results are somewhat different. I am sure that the function built in your code is a trapezoidal rule, but from the observed results, the real area of the hysteresis loop is closer to the code I attached (it should be very close to 1). I think this problem lies with myself. I may not have learned to understand the code you provided (sorry again). If there is an error in my code, please criticize and correct it! In addition, because I am not familiar with ubermagutil, there may be some mistakes in my understanding, which leads to the opposite of yours, and please tell me the reason for this situation! Thank you again for your help. My file is attached below, which contains the hysteresis area calculation I performed according to your code, as well as the calculation performed by my own code!
[Hysteresis test.ipynb.zip](https://github.com/ubermag/help/files/6115146/Hysteresis.test.ipynb.zip)

**Comment by marijanbeg** [comment]
Hi @code-whale, your code is perfectly fine. The mistake was in the index in my code you modified. In summary, both top and bottom curves must be defined on the same range of B (-1 to 1). If not, the subtraction would give a wrong result.

I attach the notebook I fixed: [Hysteresis test.ipynb.zip](https://github.com/ubermag/help/files/6123320/Hysteresis.test.ipynb.zip)

It would be really nice if you could summarise this method in a tutorial, so we can make it part of Ubermag documentation.

Is this issue resolved now? Can we close it?

**Comment by code-whale** [comment]
@marijanbeg ，Thank you very much for your help! The problem is solved! I will try to summarize the code, and when I finish summarizing it, I will put it in the help repository. Thank you again for your continued help! Now I'll turn this problem off!

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.

I am looking forward to your tutorial.
