### ISSUE TITLE
There are two E's in the hysteresis loop data table

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#118]
Dear Ubermag Team, In the process of dealing with the total energy of each step of the hysteresis loop system, I found that there are two E tags in data[ xx] .table.data. I don't know what these two E represent respectively. According to my own model and the results of the energy output, I tend to show the total energy in the first row, and I don't know what the E in the latter line represents. I don't define it in my model. Can you help me understand what these two E's are? thank you for your help!
![image](https://user-images.githubusercontent.com/61874432/111031189-31500300-8441-11eb-8007-cc24e50a90fa.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. Could you please tell us what is the energy equation you used? This would help us debug the problem. (You can also share a minimal notebook with us)

**Comment by code-whale** [comment]
@marijanbeg ,The original data I use is the data  of hysteresis in your workshop tutorial folder.
After Input````system.table.data['E’]````, two columns of data appear

**Comment by marijanbeg** [comment]
Thank you for letting us know. We are going to investigate this and include a bug fix in the next release.

I am going to keep this issue open until this issue is addressed.

**Comment by marijanbeg** [comment]
Planned for the next release (@lang-m).
