### ISSUE TITLE
Linux installation failing tests & possible solution

### ISSUE THREAD

**Issue by n-loo** [ubermag/help#121]
Hi ubermag team!

I installed ubermag on Linux (CentOS Linux 8.3.2011) as shown in the [video demo ](https://www.youtube.com/watch?v=s-nUW04qUIY) using miniconda. When I ran `ubermag.test()` in the correct conda environment it failed 76 tests. Here's some of them listed:

```
tests/test_micromagnetictests.py::TestCompute::test_energy FAILED                      [ 65%]
tests/test_micromagnetictests.py::TestCompute::test_energy_density FAILED              [ 66%]
tests/test_micromagnetictests.py::TestCompute::test_effective_field FAILED             [ 66%]
tests/test_micromagnetictests.py::TestCompute::test_invalid_func PASSED                [ 66%]
tests/test_micromagnetictests.py::TestCompute::test_dmi FAILED                         [ 67%]
tests/test_micromagnetictests.py::TestCubicAnisotropy::test_scalar_vector_vector FAILED [ 67%]
tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_vector_vector FAILED [ 67%]
tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_field_field FAILED   [ 67%]
tests/test_micromagnetictests.py::TestCubicAnisotropy::test_dict_vector_vector FAILED  [ 68%]
tests/test_micromagnetictests.py::TestDamping::test_scalar FAILED                      [ 68%]
tests/test_micromagnetictests.py::TestDamping::test_dict FAILED                        [ 68%]
tests/test_micromagnetictests.py::TestDamping::test_field FAILED                       [ 69%]
tests/test_micromagnetictests.py::TestDemag::test_demag FAILED                         [ 69%]
tests/test_micromagnetictests.py::TestDemag::test_demag_asymptotic_radius FAILED       [ 69%]
tests/test_micromagnetictests.py::TestDemag::test_demag_pbc FAILED                     [ 70%]
```

The failed tests all returned `RuntimeError: Error in OOMMF run` indicating it was having trouble finding OOMMF. I tried wiping everything and I installed anaconda instead of miniconda but was receiving the same errors when running `ubermag.test()`. This issue also occurred on a Ubuntu 20.04 VM in WSL.

What solved the problem for me was building OOMMF (OOMMF 2.0 alpha 2 patch release (8-Jun-2020)) from their [website](https://math.nist.gov/oommf/software-20.html) and copying the file `/path_to_oommf_folder/config/platforms/linux-x86_64.tcl` to ubermag's OOMMF installation `~/anaconda3/envs/ubermag/opt/oommf/platforms/linux-x86_64.tcl`. I'm not sure why but doing this made the tests pass when running `ubermag.test()`. 

If this isn't already a known/documented issue for ubermag I hope this helps!

**Comment by marijanbeg** [comment]
Hi @n-loo, thank you for letting us know - much appreciated. Unfortunately, we do not have the ability to test installation on all Linux distributions. In the situation you encountered, there is a possibility of setting the environment variable. You can have a look at the advanced installation instructions: https://ubermag.readthedocs.io/en/latest/ipynb/advanced-installation.html

Please let us know if we can provide support on any other topic.
