### ISSUE TITLE
Skyrmions trajectory

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#122]
Dear Ubermag Team, I want to draw the trajectory of this kind of skyrmions driven by current or magnetic field as shown in the following figure. Can you teach me how to achieve this?
![image](https://user-images.githubusercontent.com/61874432/112854929-eab90480-90e0-11eb-80f0-57fd9d83e611.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. You can compute the position of a skyrmion by computing its guiding centre (equations in Yang et al. PRB 102, 094439 (2020)). Using discretised field, that would be:

```
def guiding_centre(field):
    q = dft.topological_charge_density(field)
    x = df.Field(field.mesh, dim=1, value=lambda point: point[0])
    y = df.Field(field.mesh, dim=1, value=lambda point: point[1])

    rx = df.integral(x*q*df.dx*df.dy) / df.integral(q*df.dx*df.dy)
    ry = df.integral(y*q*df.dx*df.dy) / df.integral(q*df.dx*df.dy)

    return (rx, ry)
```
where `field` is `system.m.plane('z)`.

Please add a comment to this issue if you have any further questions.

**Comment by code-whale** [comment]
@marijanbeg ,I tried to calculate the skyrmions location with the above code, but the following error occurred. Can you tell me why? Thank you again for your help
![image](https://user-images.githubusercontent.com/61874432/114391373-01278b80-9bca-11eb-967a-8be1e99483f0.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, I cannot debug this code unless I can see the field you passed to the function I sent you. Could you please send me a minimal failing example notebook, so I can have a look?

I am going to reopen this issue until it is fully addressed.

**Comment by code-whale** [comment]
@marijanbeg，Thank you for your help! I attach the ipynb file here. In this file, the skyrmions center point should be at the origin (I think)
[Skyrmion center point.ipynb.zip](https://github.com/ubermag/help/files/6296813/Skyrmion.center.point.ipynb.zip)

**Comment by marijanbeg** [comment]
Thank you @code-whale, I have had a look at the notebook. The error you get is there because you pass the plane with uniform magnetisation - please note at the subregions you defined. This causes division by zero and guiding centre formula does not make sense in that case (you cannot find a centre of a uniform field).

Sampling at z-coordinate which has a non-zero topological charge solves the problem. Try`guiding_centre(data[0][0].plane(z=1e-9))`, which is the plane you used to plot in the previous cell.

**Comment by zkhodzhaev** [comment]
Can this work for .ovf run on Mumax3 software, separate from Ubermag? 
I am not able to use this function:

![image](https://user-images.githubusercontent.com/21960382/121464996-3229ff80-c972-11eb-8635-6f9d4517b2fe.png)

**Comment by lang-m** [comment]
Hi @zkhodzhaev, the problem in your code is that you are not actually reading the file content. Your `field` object is just a string.
You can use:
```Python
field = df.Field.fromfile(files[10])
```
to read the file. Then, `field` is of type `df.Field` and can be processed further.

**Comment by zkhodzhaev** [comment]
Yes, silly mistake. Thanks.

**Comment by zkhodzhaev** [comment]
Also, can this work for multiple skyrmions moving through a geometry?

**Comment by marijanbeg** [comment]
Hi @zkhodzhaev, unfortunately, this works only for a single skyrmion. A much more complicated solution would be necessary for multiple skyrmions.
