### ISSUE TITLE
Skyrmionium state function and calculation of skyrmions size

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#123]
Dear Ubermag Team,I would like to ask you how to define a function with an initial state of skyrmionium. According to the function that defines biskyrmions in your literature(Do Images of Biskyrmions Show Type-II Bubbles?), I have defined Neel- skyrmions after modification the python code, as shown below. 
````
def init_neelskyrmion(pos):
    R = 20e-9
    x, y = pos[0], pos[1]
    r = np.sqrt(x ** 2 + y ** 2)
    phi = np.arctan2(y, x)
    phi_b = np.arctan2(y, x)
    
    k = np.pi / R
    
    if r < R :
        m = (np.sin(k * r) * np.cos(phi_b), np.sin(k * r) * np.sin(phi_b), -np.cos(k * r))
    else:
        m = (0, 0, 1)
    
    return m
````
If you can, please check whether the function can define neelskyrmion, and whether it can define neel-skyrmionium through further modification.
 In addition, I would also like to ask you how I get the size of skyrmions after I simulate it (for example, the R defined in the function is the skyrmions radius, how can I calculate this size from the omf file in the actual simulation? (could you tell me how to calculate it, if possible? Thank you again for your kind help!

**Comment by code-whale** [comment]
I try to modify the function as follows.
````
def init_neelskyrmion(pos):
    R = 20e-9
    x, y = pos[0], pos[1]
    r = np.sqrt((x-20e-9) ** 2 + y ** 2)
    phi = np.arctan2(y, x-20e-9)
    phi_b = np.arctan2(y, x-20e-9)
    
    k = np.pi / R
    
    if r < R :
        m = (np.sin(k * r) * np.cos(phi_b), -np.sin(k * r) * np.sin(phi_b), -np.cos(2*k * r))
    else:
        m = (0, 0, 1)
    
    return m
````
Skyrmionium is set successfully. Please help to check whether the function is correct. And how to determine the diameter of various skyrmions, as well as the speed of skyrmions under current or external magnetic field can be calculated by calculating coordinates. If so, please teach me how to write a program (or whether there is a better way to achieve this goal). Thank you again for your help!

**Comment by code-whale** [comment]
Can the calculation of skyrmions dimension be realized by calculating the distance between two points on the same horizontal line with MZ = 0 similar to the calculation of coordinates in question #122 ? But I don't know how to use Matplotlib to calculate the intersection coordinates of two curves. If I can, can you tell me how to calculate it?

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question and for using Ubermag. You can have a look at this paper (https://www.nature.com/articles/srep17137) where we defined analytic functions for defining different skyrmionic states. Besides, in this paper, we computed the size of skyrmion by fitting a cosine function to the state's profile.

The function you sent us is similar to what we did and I am glad you managed to get the state you wanted.

Regarding the size of the skyrmionic state, you can have a look at https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html function which can help you fit the cosine wave to the profile.

You can draft the code and I can help you debug it if necessary.

**Comment by code-whale** [comment]
@marijanbeg,Thank you very much for your help. I will try to learn the content in your link. If you have time, please look at the error in question #122 . The system reported an error when I calculated skyrmions center point. I can't reopen question 122 at present. Thank you again for your help!

**Comment by marijanbeg** [comment]
Addressed #122 :)

**Comment by code-whale** [comment]
@marijanbeg, Thank you for your help. I don't understand the method of fitting cosine function very well, and I don't know how to express the functions of skyrmions defined in your article in Python code. Can you give me a sample file of cosine fitting? In addition, I used another method to calculate the skyrmions diameter in the attached ipynb file. If you can, can you help me check whether the method of calculating skyrmions size in this file is correct,
[Skyrmion center point and size calculation.ipynb.zip](https://github.com/ubermag/help/files/6303096/Skyrmion.center.point.and.size.calculation.ipynb.zip)

**Comment by marijanbeg** [comment]
Hi @code-whale, I attach the notebook with curve fitting. The relevant code is:

```python
profile = data[0][0].orientation.z.line(p1=(-150e-9, 0, 1e-9), p2=(150e-9, 0, 1e-9))

r = profile.data['r'].values
mz = profile.data['v'].values

from scipy.optimize import curve_fit
import numpy as np

def cosine_fun(x, T, phase):
    w = 2*np.pi / T
    return np.cos(w*x + phase)

(T, phase), _ = curve_fit(cosine_fun, r, mz, p0=(300e-9, 150e-9))
```

`T` is the cosine wave period and you can extract many different things from it.

**Comment by marijanbeg** [comment]
Forgot to attach the notebook...

[Skyrmion center point and size calculation.ipynb.zip](https://github.com/ubermag/help/files/6304299/Skyrmion.center.point.and.size.calculation.ipynb.zip)

**Comment by code-whale** [comment]
@marijanbeg， Thank you for your reply. I have read your code, but I still have some doubts. First of all, I think skyrmions size should be the distance between two MZ = 0 points on the definition center line. T in your code seems to be the distance between two MZ = 1 points. Then, when skyrmions size is reduced, its magnetic moment curve does not seem to be accurate enough after cosine fitting I attached a notebook with data [1], which is a small skyrmions

[skyrmions size.zip](https://github.com/ubermag/help/files/6311037/skyrmions.size.zip)

**Comment by marijanbeg** [comment]
Hi @code-whale, this was an example of curve fitting for a particular case. If you want to fit some other curve, the code is the same and you only have to change the analytic formula of the curve.

**Comment by code-whale** [comment]
@marijanbeg ， Thank you for your help, I have understood your method about function fitting, I think your method and my method about calculating the distance between two points MZ = 0 can calculate the skyrmions diameter, thank you again for your help! You can close this problem now!
