### ISSUE TITLE
Simulate Spin-Torque Oscillator System 

### ISSUE THREAD

**Issue by RuanJohn** [ubermag/help#124]
Good day everyone, 

Please see the attached PDF for the system I am trying to simulate. 
The system also has the constraint that it must remain on a unit-sphere for all time such that 
M_x^2 + M_y^2 + M_z^2  = 1

Exact constants are not too important for this system, I am trying to verify some analytic work I have done by checking stability of fixed points in the system. 

Thank you for your help. 

Kind regards,
Ruan
[system.pdf](https://github.com/ubermag/help/files/6320411/system.pdf)

**Comment by marijanbeg** [comment]
Hi @RuanJohn, thank you for your question. All `TimeDriver` simulations preserve the norm - the magnitude remains fixed. Please note that `system.m` gives you the magnetisation field with Ms magnitude. If you need a unit vector field, you can get it via `system.m.orientation`. So, I do not see this being a problem.

In terms of the equation you sent us, it seems it is a bit specialised for the analytic case you are studying. I believe there all terms you need should be available in Ubermag.

You can draft a simulation notebook, and send it to us. This way we can address the problems as they arise and help you set up your simulation.

I am going to close this issue now, but that does not mean you cannot keep asking questions on this topic.
