### ISSUE TITLE
Problems in simulating polarization current

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#125]
Dear ubermag team, I want to add the influence of spin current to the simulation system. I simulated several situations in the attached ipynb file. I found that I defined the parameters of spatial variation such as J, MP, P, eps_prime, lambda through functions, but the simulation results are no different from those of directly adding these parameters in the global. I feel that the spatial variation statement I defined does not work. And when I define the lambda of spatial change, OOMMF will report an error.
[random2layer_B0_Dd.ipynb.zip](https://github.com/ubermag/help/files/6357927/random2layer_B0_Dd.ipynb.zip)
In addition, I would like to ask you about eps_prime and lambda For example, lambda is the slonczswski factor, but I don't know what this parameter is affected by. For eps_prime I also have the same question, if you can, can you tell me what impact they are affected by (such as the material itself or geometric structure, etc.). Thank you very much for your help!

**Comment by code-whale** [comment]
When I further change the size of P, lambda, J and other parameters, the simulation results do not change. I do not know whether my assignment is wrong. It seems that the whole system does have the effect of polarization current, but no matter how I change the parameters, the simulation results do not seem to change

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for the question. There is no need to define all parameters separately. If you define only J as a field, you can pass other parameters as scalars. Where J=0, it does not matter what the values of other parameters are. This minimises the chances of introducing errors.

After you define J field, you can visualise it to check if it is what you wanted. Could you please simplify the notebook as I suggested and update us on the progress.

**Comment by code-whale** [comment]
@marijanbeg, 
[Polarization current test.ipynb.zip](https://github.com/ubermag/help/files/6373424/Polarization.current.test.ipynb.zip)
Thank you for your reply! After I made some adjustments according to your instructions, the results show that I have successfully changed the position of the injected current, but this change has no effect on the simulation results, in addition, changing the size of the current has no effect on the results. I attach the updated ipynb file below for your reference. Thank you again for your help!

**Comment by code-whale** [comment]
@marijanbeg ,After testing the program again, I found that the problem should be that the radius of the current area I set was too small so that the result did not seem to change. When I expanded the size of the current area, the result changed. In addition, I would like to ask you whether ubermag supports the definition of time-varying current. For example, I hope to apply the current in the (0, 0, 1) direction in the first 0.5ns of the simulation, and apply the current in the (1, 0, 0) direction in the last 0.5ns, or whether the sinusoidal current can be applied just like the sinusoidal magnetic field. If these functions can be realized, can you tell me how to do it? Thank you very much for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for letting us know. For simple current pulses, you can always apply current and run `TimeDriver` for some time. After that, you can modify the relevant term in the dynamics equation (`system.dynamics.J=...`) and drive the system again. Similarly, you can add or remove terms from both energy and dynamics equations between drives.

Applying a time-varying current (like a sine wave) is unfortunately not possible at the moment.

I am going to close this issue now, but please keep raising new issues.

**Comment by code-whale** [comment]
@marijanbeg , Thank you very much for your help! If ubermag can apply sinusoidal current in the future, that would be great!
