### ISSUE TITLE
Multiple gyromagnetic ratios in the same mesh

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#127]
Hi, 

I want to know if there is a way to define different gammas for subregions of my mesh.

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you for your qurstion. gamma is like any other parameter in Ubermag. You can make it spatially varying either using a dictionary or by defining a field object. Please have a look at these two tutorials: 

1. https://github.com/ubermag/workshop/blob/master/tutorials/spatially-varying-parameters1.ipynb
2. https://github.com/ubermag/workshop/blob/master/tutorials/spatially-varying-parameters2.ipynb

I am going to close this issue now, but please feel free to post further questions.
