### ISSUE TITLE
Requirements for Binder launch

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#128]
Hi,
Because I like Ubermag so much, I'm trying to convince everyone in my group to use it and I wrote a small tutorial in a Github repo. I would like to add a Binder button, but that can be tricky since I don't know what other packages are required. Where could I find the requirements.txt file?
Thanks

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you so much! We are very glad you are finding Ubermag helpful in your work.

Regarding Binder, we do not use `requirements.txt`, but a conda environment file. Simply adding this file (https://github.com/ubermag/ubermag/blob/master/binder/environment.yml) to your repository should do the work. If you encounter any difficulties, you can share the repository with me and I can help you set it up.

Please note that we are always looking for tutorials written by users, so if you are interested please share them with us and we can make them part of our official documentation.

I will keep this issue opened until I receive a confirmation from you that Binder is working.

**Comment by AkravasTheWise** [comment]
Hi @marijanbeg 
It works perfectly now. Thank you so much. Yes, I have been wanting to share the tutorial with you guys, but I'd like to do more research-specific work on it before I'm ready to.  I'll keep in touch and I'm closing the issue now.
