### ISSUE TITLE
The direction of u in Zhang-Li term

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#130]
Dear Ubermag Team，I would like to ask about how to define the direction of U in Zhang-Li term. I found after watching your example that there is no statement to set the direction of U. For example, I want U to be perpendicular to the plane or along the Y direction, how should I set it? Thank you for your help.

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. Unfortunately, this is not possible due to the limitations of the OOMMF Zhang-Li extension - only x-direction is allowed. The only workaround would be to reorient the sample.
