### ISSUE TITLE
On the possibility of calculating the influence of temperature by self-defined driving equation

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#133]
Dear Ubermag Team, I'm studying the integral calculation in your tutorial, and calculating the system energy by calculating the energy equation (instead of using the built-in function in ubermag). In addition, I noticed that your tutorial is about iterative calculation with the for loop statement according to the driving equation. I would like to ask a possibility here, that is, if I find the LLG equation at finite temperature, whether this method can be used to realize the micromagnetic simulation at finite temperature. Thank you again for your help.

**Comment by code-whale** [comment]
In recent days, I'm trying to simulate according to your tutorial custom method, but my simulation results are not consistent with the default solver results of ubermag. Can you tell me what errors lead to this phenomenon? I attach my ipynb file below. Thank you again for your help
[Custom calculation.ipynb.zip](https://github.com/ubermag/help/files/6532375/Custom.calculation.ipynb.zip)

**Comment by code-whale** [comment]
The previous ipynb file forgot to remove the demagnetization field, so update here.
[Uploading Custom calculation.ipynb.zip…]()

**Comment by code-whale** [comment]
In addition, I also want to ask you about the definition of mz. ````system. m. orientation```` defines m, but in the DMI of CNV class, the energy term contains mz. How to define mz? Do you use ````system. m. orientation. z````?

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your questions. Here are the answers to them:

1. We do not do finite-temperature simulations in Ubermag and this is something that is not on our agenda. Therefore, we cannot provide any support on this topic.
2. I will come back to this later, and keep this issue open because of that.
3. Yes, `system.m.orientation.z` gives you mz.

**Comment by marijanbeg** [comment]
Simulations at T > 0 using ThetaEvolve will be in the next release of Ubermag. Please keep an eye on: https://github.com/ubermag/oommfc/issues/52 where we will post future updates.
