### ISSUE TITLE
Failure caused by limited running time of simulation under windows system

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#136]
Dear Ubermag Team, When my classmate @zzyzm123 and I ran ubermag on Windows system, we found that when the simulation time exceeded 900 seconds, an error would occur. The same code running in MacOS is not limited by time. I attach the ipynb file with the error, please check it. Thank you again for your help!
[driving sk bag.ipynb.zip](https://github.com/ubermag/help/files/6591506/driving.sk.bag.ipynb.zip)

**Comment by code-whale** [comment]
Sorry, the problem should appear in the file name. In the early morning test, we used the Chinese system name, which can run normally after changing to pure English! Now I close this question!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for the update. Ubermag does not have any limitations on the simulation time. Unfortunately, we do not have control over the limitations imposed by the operating system. I am glad you can run simulations on different machines.
