### ISSUE TITLE
Installation on Google Colab 

### ISSUE THREAD

**Issue by Harry-09** [ubermag/help#137]
Is it possible to run ubermag simulation using Google Colaboratory? If so please kindly help me in this regard as it takes much resources from the local computer while running the simulation.

Thanks in Advance!!!

**Comment by marijanbeg** [comment]
Hi @Harry-09, Ubermag is not a GPU code and we do not support those simulations. However, I believe you can set it up on Google Colab and use CPU resources.

**Comment by marijanbeg** [comment]
Hi @Harry-09, have you managed to install Ubermag on Google Colab using conda?
