### ISSUE TITLE
Converting df to numpy array/ reading multiple file from the same directory

### ISSUE THREAD

**Issue by zkhodzhaev** [ubermag/help#138]
I have 2 questions:

1. How can we read multiple files and save them as, e.g.,  "file_name"?

The website does not have this info: https://discretisedfield.readthedocs.io/en/latest/ipynb/field-read-write.html
i tried this, but didn't work:
![image](https://user-images.githubusercontent.com/21960382/120875586-c60e5c80-c569-11eb-9dcd-2c29f8ae7333.png)

2. I noticed discretisedfield array is not a NumPy array. Can I convert it to NumPy array? so that, I can do the usual operations on the final array. 

Thanks

**Comment by code-whale** [comment]
@zkhodzhaev ,Hi, I'm also a beginner of ubermag. I have some suggestions for your question. First of all, I think you can use the for loop to read multiple files (on the premise that your read files should be named by regular numbers), but I haven't tried that before, so I'm not sure it works. For the second point, you can check whether d in your figure has been successfully defined as a field object. A field object should be similar to the one in the figure below.
![image](https://user-images.githubusercontent.com/61874432/120879855-02d56480-c5f9-11eb-8222-f7740be37f78.png)
If your d returns this type, then I think you just need to enter ````d.array```` to return a numpy array. Hope to help you!
![image](https://user-images.githubusercontent.com/61874432/120879899-40d28880-c5f9-11eb-8e05-5c25d054efec.png)

**Comment by zkhodzhaev** [comment]
Thanks, I'll let you if it works.

**Comment by marijanbeg** [comment]
Hi @zkhodzhaev, thank you for your question and for using Ubermag. 

1. As @code-whale suggested, you can use a loop. However, a package `micromagneticdata` can help you if you obtained the `ovf` files using Ubermag. For instance:

```python
import micromagneticdata as md
import discretisedfiels as df

data = md.Data(system.name)
drive = data[drive_number]
for field in drive:
    field.write(filename)
```

However, if the files you want to read/write are not obtained by Ubermag, I would suggest looking at `glob` (https://docs.python.org/3/library/glob.html). If you provide us with more details, I can give you more specific advice.

2. NumPy array from a field object can be obtained as `field.array`. Please note that the `Field` object provides many common operations and convenience functions already. If you let me know what you want to calculate, I can provide further details.

**Comment by zkhodzhaev** [comment]
> Hi @zkhodzhaev, thank you for your question and for using Ubermag.
> 
> 1. As @code-whale suggested, you can use a loop. However, a package `micromagneticdata` can help you if you obtained the `ovf` files using Ubermag. For instance:
> 
> ```python
> import micromagneticdata as md
> import discretisedfiels as df
> 
> data = md.Data(system.name)
> drive = data[drive_number]
> for field in drive:
>     field.write(filename)
> ```
> 
> However, if the files you want to read/write are not obtained by Ubermag, I would suggest looking at `glob` (https://docs.python.org/3/library/glob.html). If you provide us with more details, I can give you more specific advice.
> 
> 1. NumPy array from a field object can be obtained as `field.array`. Please note that the `Field` object provides many common operations and convenience functions already. If you let me know what you want to calculate, I can provide further details.


I am trying to track skyrmion motion:

- I have ".ovf" files from Mumax3, I ran them outside Ubermag, myself (glob seem to work to get all files)
- Now, I was able to import of file using Ubermag's "discretisedfiels" package

Is there a way to track a skyrmion using the `Field` object? to see the trajectory of the motion, separately and multiple skyrmions at the time?

**Comment by marijanbeg** [comment]
Thank @zkhodzhaev for the clarification. If you used mumax3 for generating files, then glob seems to be the best way forward.

In order to track the position of a skyrmion, you can have a look at our discussion with @code-whale (https://github.com/ubermag/help/issues/132). For tracking multiple skyrmions, there is no easy solution I am afraid.

Is there anything else we can help you with regarding this issue?

**Comment by zkhodzhaev** [comment]
Thank you, I have other issues. I can open another ticket later.

**Comment by marijanbeg** [comment]
My apologies, I referred to the wrong issue. This is the right one: https://github.com/ubermag/help/issues/122
