### ISSUE TITLE
How to get the initial state energy value

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#139]
Dear Ubermag Team, When I use ````TimeDriver```` to simulate, the data of the first row of ````data[].table.data```` in the output table is the data value after the first step time, so I can't observe the data of the initial state (i.e. t = 0). Can you teach me how to get the data of initial state (without simulation)? Thank you for your help!

**Comment by code-whale** [comment]
I tried to use the method you taught me before to calculate the initial state energy, but the program reported the following error.
![image](https://user-images.githubusercontent.com/61874432/120895171-57ef9580-c64e-11eb-9755-ed0ff4caa651.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, it is a bit difficult for me to see what exactly went wrong in your code. You can simplify your code as:
```
# At this point in the code I assume you have your system object fully defined
E = oc.compute(system.energy.energy, system)
```
Could you please let us know if this works?

**Comment by code-whale** [comment]
@marijanbeg ,Thank you for your help! I tried your method, but there is still this error. I attach the ipynb file for your reference
[Untitled2.ipynb.zip](https://github.com/ubermag/help/files/6608905/Untitled2.ipynb.zip)

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for the notebook. You found a special case we did not cover in our code. More precisely, we did not cover the case when the Slonczewski term is in the dynamics equation and we should look for a different evolver key.

Until we add this bugfix, you can simply move `system.dynamics = ...` line to be after the `oc.compute()` line and this should work.

I will keep this issue open and label it as a bug.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you for your help! After removing ````system. dynamics =... ````It can be calculated normally!
