### ISSUE TITLE
reading files with the extension .omf using discretisedfield

### ISSUE THREAD

**Issue by Physics153** [ubermag/help#151]
Good afternoon.
please tell me if it is possible to open your magnetization file obtained by modeling in the OOMMF program using discretisedfield. I tried to use the commands described on the page https://discretisedfield.readthedocs.io/en/latest/ipynb/field-read-write.html
but I couldn't open my file.
please advise us.
I'm just in awe of the amazing visualization that discretisedfield helps to make.
Thanks!

**Comment by marijanbeg** [comment]
Hi @Physics153, thank you for your question and for using Ubermag. If you have a file `my-oommf-file.omf`, you can open it using:
```python
import discretisedfield as df

field = df.Field.fromfile('my-oommf-file.omf')
```

Have you tried that? If yes, what error did you get?

**Comment by Physics153** [comment]
Good afternoon!
Thank you so much for your help!
I reinstall the Python, installed Ubermag again.
Everything works.

**Comment by marijanbeg** [comment]
Hi @Physics153, thank you for letting us know. I am closing this issue now.

Please let us know if you need further help by raising another issue.
