### ISSUE TITLE
Cropping a field object

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#152]
Hi, all

I'm trying to crop a `df.Field` object in order to visualize only the region of interest.

Keep up the good work :)

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, thank you for your question. Please have a look at this tutorial from the workshop: https://github.com/ubermag/workshop/blob/master/tutorials/subfields.ipynb

If you have any further questions, please do not hesitate to ask.
