### ISSUE TITLE
MacOS Ubermag installation

### ISSUE THREAD

**Issue by zkhodzhaev** [ubermag/help#153]
While doing the test, I received this error:

![image](https://user-images.githubusercontent.com/21960382/120870651-b0436c00-c556-11eb-862c-63ee3a95899e.png)

Is it a fatal error? Do I need to do anything?

System: 
![image](https://user-images.githubusercontent.com/21960382/120870716-d537df00-c556-11eb-9a14-f2a8829080f1.png)

Thanks

**Comment by marijanbeg** [comment]
Hi @zkhodzhaev, thank you for your question and sorry for the delayed response. Is this issue still active or it has been resolved?

**Comment by zkhodzhaev** [comment]
Yes

**Comment by marijanbeg** [comment]
Thank you for letting u know @zkhodzhaev. Could you please give us a short description of how the problem is resolved so that we know how to address it in the future as well as to help others who have the same problem?
