### ISSUE TITLE
Query related to AFM lattice on Ubermag

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#157]
I am Ishan Bhat, a fourth-year undergraduate at Indian Institute of Science, Bangalore, India. I want to simulate antiferromagnetic lattice and work on it. Can you please explain how to do it on Ubermag?

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, thank you for your question and for using Ubermag. Although setting negative A is permitted, simulating AFM lattice using micromagnetic simulators is not trivial and this is not currently supported.
