### ISSUE TITLE
how to get the demagnetization tensor in Python

### ISSUE THREAD

**Issue by dvincentwest** [ubermag/help#159]
Hi, I have set up a fairly simple magnetic system using `magneticmodel`, `discretisedfield`, and `oommfc`.  I would like to do some further calculations using the demagnetization tensor for this system.  Is there an api to retrieve this back as a numpy array? If not, is there a way to take the outputs from this system, and hook directly into OOMMF to get the demagnetization tensor? Thank you

**Comment by marijanbeg** [comment]
Hi @dvincentwest, thank you for your question and for using Ubermag. At the moment, we do not support extracting the demag tensor. However, this is something we will consider including in the next release of Ubermag.

Besides, please note that Ubermag is an open-source project and we welcome all contributions (however small they are). So, if there is anything you are working on and you believe would be helpful to the community, please feel free to create a pull request and become of the authors or contributors to Ubermag. If you need any help on the way, please let us know, and we would be very happy to assist you :)

**Comment by lang-m** [comment]
@dvincentwest Demagnetisation tensor and demagnetisation field can be extracted in Ubermag version 0.60.0 (https://ubermag.github.io/api/_autosummary/discretisedfield.tools.demag_tensor.html, https://ubermag.github.io/api/_autosummary/discretisedfield.tools.demag_field.html, not documented in great details yet.) Please note that this is (differently from OOMMF) only using the analytic formula (which can cause numerical issuse: https://fangohr.github.io/blog/2015-computing-the-demag-tensor-for-finite-difference-micromagnetic-simulations.html).
