### ISSUE TITLE
Magnetization Dynamics in a triangular and square shaped Antidot lattice

### ISSUE THREAD

**Issue by AmritKumarMondal** [ubermag/help#160]
Dear Sir,
I want to study magnetization dynamics in triangular (arm = 50 nm) and square-shaped (arm = 50 nm) antidot lattice with lattice constant la and lb, equal to 150 nm and 200 nm. Can you please help me how to create those antidot structures?

**Comment by marijanbeg** [comment]
Hi @AmritKumarMondal, thank you for your question and for considering using Ubermag in your work.

I am not sure I fully understand your question. Could you please provide us with more information? Ideally, a sketch of the system you want to simulate.

**Comment by AmritKumarMondal** [comment]
Dear Sir,
Txt and image files are attached herewith. Please have a look. I want to study magnetization dynamics in this system using ubermag.
[Tri_AD_Stat.txt](https://github.com/ubermag/help/files/6834520/Tri_AD_Stat.txt)
![tri_X800_Y660](https://user-images.githubusercontent.com/82872319/126032577-ef2b89af-38b4-431d-b709-0395787a4856.jpg)

**Comment by AmritKumarMondal** [comment]
Dear Sir,
Do you understand my question?
