### ISSUE TITLE
Simulate Hexagonal / Honey comb lattice on Ubermag?

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#161]
How to simulate hexagonal / honey comb lattice on Ubermag?

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, thank you for your question and for using Ubermag. Ubermag is a finite-difference micromagnetic simulation tool and it does not support atomistic simulations on hexagonal lattices.

We have another simulator Fidimag (https://computationalmodelling.github.io/fidimag/) which has this functionality. However, we cannot provide support for Fidimag as we do for Ubermag.
