### ISSUE TITLE
How to draw such visualisations?

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#163]
![image](https://user-images.githubusercontent.com/86786384/126113515-13b8b6cc-4c8e-4e2a-bca0-9dfb2922a2e7.png)
Can we get what tutorial has explained how to draw such visualisations on Ubermag? If tutorial is not available, can we get the syntax being used here

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, thank you for your question. The simulations were performed in Ubermag and the results were saved as a VTK file. After that, Blender (https://www.blender.org/) was used for the visualisation. Unfortunately, we cannot provide support for Blender, but there are many online tutorials that can help you.
