### ISSUE TITLE
How to simulated 3D / hedgehog skyrmion simulations?

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#164]
![image](https://user-images.githubusercontent.com/86786384/126114017-7399952a-98b4-48b5-b86b-f6ba69b1d9c1.png)
How to simulate these 3D / hedgehog skyrmions?

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, thank you for your question. This is not an Ubermag question. The magnetisation states in the first row you can simulate using Ubermag by changing the crystallographic class for DMI (T, Cnv, D2d). Then, you can save the field as a VTK file and visualise it using e.g. Paraview (https://www.paraview.org/).

The images in the second row are projections on the sphere and some extra coding is necessary before visualising it using Paraview. Unfortunately, this is not something Ubermag is made for and we do not provide Paraview support. Therefore, I am going to close this issue.

However, maybe somebody from the community has already done similar visualisations and would be happy to help.
