### ISSUE TITLE
Dipole dipole interactions

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#167]
I want to include the dipole dipole interactions between two skyrmions to form a bi-skyrmion. How to include that?

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, dipole-dipole interactions are added to the energy equation by including `mm.Demag()` energy term.

Before simulating "bi-skyrmions", I would recommend having a look at this paper: https://onlinelibrary.wiley.com/doi/full/10.1002/adma.201806598.
