### ISSUE TITLE
Periodic Boundary Condition Error

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#168]
Hello Ubermag Team,

https://github.com/ubermag/workshop/blob/master/tutorials/periodic-boundary-conditions.ipynb
When I tried this Periodic Boundary Condition (PBC) program, I got an error as "The system cannot find specific file"
Is it possible to use PBC on Windows Operating System?
Thank you for the help.

![PBC Error](https://user-images.githubusercontent.com/43433451/126597853-06313929-8ff3-4eb9-a21d-9525f8cbbf14.png)

**Comment by marijanbeg** [comment]
Hi @Ponsudana, thank you for your question. Yes, if you are a Windows user, DMI Cnv extension is not supported. However, you can install Docker and this should allow you to run these problems.

**Comment by Ponsudana** [comment]
Thank you @marijanbeg 
If possible can you share a website link or instruction steps to install Docker for running Ubermag programs?

**Comment by marijanbeg** [comment]
Hi @Ponsudana, all you need to do is to follow instructions on https://docs.docker.com/get-docker/ and each time you run a simulation which requires to be run inside Docker, Ubermag will do it automatically. You can find more information in this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/choosing-runner.ipynb
