### ISSUE TITLE
How to incorporate a Heavy Metal (HM) layer?

### ISSUE THREAD

**Issue by ishanbhat17** [ubermag/help#169]
Hi. How to incorporate a Heavy Metal (HM) layer like Pt/Ta to form a HM/FM/HM layer so that it already incorporates heavy metal characteristics and has spin orbit coupling??

**Comment by marijanbeg** [comment]
Hi @ishanbhat17, thank you for your question. I assume you want to run simulations of systems with interfacial DMI. You can do that by adding DMI energy term of class Cnv to the energy equation:
```
system.energy = ... + mm.DMI(D, crystalclass='Cnv')
```
