### ISSUE TITLE
Antidots array on joommf

### ISSUE THREAD

**Issue by nabilch88** [ubermag/help#17]
Hi
I'm bigenner in joommf and would like to build an antidot network. I already done it on oommf using procedure but i do not find supports to do it joommf. Can any one help me please? 
Thank u in advance.

**Comment by marijanbeg** [comment]
Hi @nablich88, can you please provide us more information on the simulations you want to run with antidots. What features are you missing? If you already did it in OOMMF, you can provide us a MIF file.  From it we can see and advise you on how to proceed with JOOMMF.

**Comment by nabilch88** [comment]
Thank u for your answer. I try to calculate the eigen modes and frequencies of an antidots array. To do this, I built an antidots array usin procedure on oommf (u can see in the attached file) and excit whith exp magnetic field to do precession. I still trying to do the same on joommf but I do not find the way to construct the antidots array.
[antidots_dyn_modes_propres_FZ).txt](https://github.com/joommf/help/files/1874944/antidots_dyn_modes_propres_FZ.txt)

**Comment by nabilch88** [comment]
Thank u lot

**Comment by marijanbeg** [comment]
Thank you for the file. I will go through it and update you on how to proceed soon (most probably next week).

**Comment by nabilch88** [comment]
thank u!!

**Comment by marijanbeg** [comment]
Hi @nabilch88, can you give us a physical explanation of the problem you are trying to simulate. More precisely, what is the system you are trying to simulate.

Many thanks.
