### ISSUE TITLE
The results of timdriver and MinDriver are inconsistent

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#170]
Dear Ubermag Team,I am simulating the formation of skyrmion in a racetrack with some holes and I found that the results obtained by choosing different solvers with the same parameters and model are not consistent, can you tell me what is the reason for this? (I don't think it is caused by my simulation time not being long enough, because at time=1e-8 only 2 skyrmion are left, while mindriver will end up with 5 skyrmion) I am not sure if there is a correlation between these two solvers and which one is closer to the real situation? I'm attaching my ipynb file for your review, thanks for your help!
[mindriver and timedriver.ipynb.zip](https://github.com/ubermag/help/files/6916233/mindriver.and.timedriver.ipynb.zip)

**Comment by fangohr** [comment]
Your question is probably about micromagnetics, not Ubermag. Try to see if you find a explanation at https://www.ctcms.nist.gov/~rdm/email-list.html .

In short: 

The min driver will minimise the energy of the system following some minimisation strategy in phase space. This may not be the path the real system takes. 

The time driver simulates the time development (and is thus probably more trustworthy than the min driver if you get to different results).
