### ISSUE TITLE
Unit of stray field?

### ISSUE THREAD

**Issue by himadri2024** [ubermag/help#171]
Dear all,

I have done the stray field simulation for a permalloy nanowire and plotted stray fields at different z heights. I have attached the file here.
[Demag_energy_Py.zip](https://github.com/ubermag/help/files/6917104/Demag_energy_Py.zip)

I am a little confused about the unit of the stray field in the y-axis. It is in 'Oe', 'mT' or something else.

Please help me in clarifying my doubt.

Thank you.
Regards,
Himadri

**Comment by marijanbeg** [comment]
Hi @himadri2024, thank you for your question. All fields are in A/m units.

**Comment by himadri2024** [comment]
Thank you, sir.
