### ISSUE TITLE
oommf computational backend not found when using pyenv

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#172]
Context:

- installed ubermag in a new (Python) virtual environment using `pyenv`
- I was expecting `oommfc` would not find an oommf installation, and then use Docker to host oommf
- Instead, I ran into an error when attempting to drive a micromagnetic system

Interpretation and hypothesis:

The mechanism for finding an oommf runner is not working if Python was installed using `pyenv` and at least one environment provides the `oommf` command (and that environment is not activated). 
The `pyenv` shim for `oommf` seems to make `oommfc` believe that there is an oommf executable, but this fails when it is actually called.

**Comment by fangohr** [comment]
More details (in different formats):

<img width="1279" alt="Screenshot 2021-08-03 at 12 41 13" src="https://user-images.githubusercontent.com/4489119/128002567-b91d1229-3e58-4061-9879-476095962760.png">


[runner-issue.zip](https://github.com/ubermag/help/files/6923464/runner-issue.zip)

**Comment by lang-m** [comment]
The issue has been resolved in PR ubermag/oommfc#61
