### ISSUE TITLE
MinDriver Loop Error

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#176]
Hello Ubermag team,

I tried to run MinDriver in a 'for' loop by varying the uniaxial anisotropy constant (K) and DMI constant (D).
But, I got different results when I varied K and D in a 'nested for' loop and when I varied a single parameter K by fixing D in a 'for'  loop.
I've also tested the results by running the MinDriver individually for specific K and D values.

The Jupyter notebook and the results are attached.
[Loop_MinDriver.zip](https://github.com/ubermag/help/files/7217369/Loop_MinDriver.zip)

For the value of K=0.4e6 and D=3.5e-3 in a for loop, I got the following result.
![loop2_0 4_3 5](https://user-images.githubusercontent.com/43433451/134503496-d1324a34-ce66-4af2-9271-71de76765228.png)
But, when I tested the result without a loop, my result is different.
![looptest_0 4_3 5](https://user-images.githubusercontent.com/43433451/134503672-bd775051-829f-4617-9d7b-348c59ec5c6d.png)

I wish to know why my results are inconsistent? Or is there any problem with my loop code? 

Any comments on this issue will be helpful.
Thank you,
Regards,
Ponsudana

**Comment by code-whale** [comment]
@Ponsudana ,Hi, I checked your code and found that the initial state was not reset in your loop command. This means that the initial state when you cycle n + 1 is the state at the end of the nth cycle. Therefore, it will be different from the results you run alone. I think you need to add ```` system.m = df. Field(mesh, value = (0, 0, 1), norm = ms_fun, dim = 3)```` analogues to the loop statement to reset the initial state. Hope to help you!
![image](https://user-images.githubusercontent.com/61874432/135003259-7477e1eb-3ea8-45fe-a2e6-85e93a4d5553.png)

**Comment by Ponsudana** [comment]
Hi @code-whale 

Thanks for the help. I forgot about resting initial value. I hope this resolves my issue.
