### ISSUE TITLE
Problem with drawing table data in tutorial

### ISSUE THREAD

**Issue by okmike** [ubermag/help#178]
Hello:
In the tutorial Session 2, Dynamics Equation,  cell 9,  the plot for 'mz' column with respect to time evolution is:
system.table.mpl(y=['mz']). But I keep getting error from Jupyter:  TypeError: plot got an unexpected keyword argument 'y'. Is this a problem with matplotlib? Thank you very much.

**Comment by lang-m** [comment]
Hi @okmike What ubermag version are using (`import ubermag; ubermag.__version__`)? The latest version (0.51) does not produce an error for me.

**Comment by okmike** [comment]
Thank you! I updated to the latest version and no error was shown.
