### ISSUE TITLE
MinDriver( ) Relaxed State

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#185]
Hello Ubermag Team,

When relaxing the defined system using MinDriver, does the system relax to a stable state or metastable state? How to differentiate between stable and metastable states using micromagnetic simulation. 

Thank you,
Regards,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, thank you for your question. Energy minimisation at zero temperature always results in the local energy minimum. What minimum you end up in depends strongly on your initial state. Unfortunately, there is no way of being sure if the final configuration is a global energy minimum.

You can find more details in this paper where we were searching for a global energy minimum (ground state): https://www.nature.com/articles/srep17137
