### ISSUE TITLE
Issue With Hysteresis Workshop Tutorial

### ISSUE THREAD

**Issue by MichaelSherburne** [ubermag/help#187]
Hello,

I am going through the Hysteresis tutorial (https://ubermag.github.io/workshop/tutorials/hysteresis.html) and it errors out when it gets to hd.drive. It is a fairly long error chain, so I've attached both the beginning and end of the error report. I think it is missing a sub package.

![image](https://user-images.githubusercontent.com/21108870/142932533-ce01b1fb-4222-4309-a687-68fcd6042e41.png)
![image](https://user-images.githubusercontent.com/21108870/142932714-e3a829fe-ff61-475c-9d15-775ee3695598.png)

All the packages are loaded in the python code from the tutorial and I updated the OOMMF software.

**Comment by lang-m** [comment]
Hi @MichaelSherburne, I've transferred your question to the help repository because we collect all questions/issues in here.
In order to address this problem I would need to see the full error message. Could you please upload it?

**Comment by MichaelSherburne** [comment]
@lang-m Here is the full error report:
--------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17612/3700443349.py in <module>
      5 
      6 hd = mc.HysteresisDriver()
----> 7 hd.drive(system, Hmin=Hmin, Hmax=Hmax, n=n)
      8 
      9 system.m.plane('y').mpl()

~\anaconda3\envs\OOMMF\lib\site-packages\oommfc\drivers\driver.py in drive(self, system, dirname, append, fixed_subregions, compute, output_step, n_threads, runner, **kwargs)
    226                     else:
    227                         runner = oc.runner.runner
--> 228             runner.call(argstr=miffilename, n_threads=n_threads)
    229 
    230             # Update system's m and datatable attributes if the derivation of

~\anaconda3\envs\OOMMF\lib\site-packages\oommfc\oommf\oommf.py in call(self, argstr, need_stderr, n_threads)
     65 
     66         tic = time.time()
---> 67         res = self._call(argstr=argstr, need_stderr=need_stderr,
     68                          n_threads=n_threads)
     69         self._kill()  # kill OOMMF (mostly needed on Windows)

~\anaconda3\envs\OOMMF\lib\site-packages\oommfc\oommf\oommf.py in _call(self, argstr, need_stderr, n_threads)
    331         if n_threads is not None:
    332             cmd += ['-threads', str(n_threads)]
--> 333         return sp.run(cmd, stdout=sp.PIPE, stderr=sp.PIPE)
    334 
    335     def _kill(self, targets=('all',)):

~\anaconda3\envs\OOMMF\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    491         kwargs['stderr'] = PIPE
    492 
--> 493     with Popen(*popenargs, **kwargs) as process:
    494         try:
    495             stdout, stderr = process.communicate(input, timeout=timeout)

~\anaconda3\envs\OOMMF\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    856                             encoding=encoding, errors=errors)
    857 
--> 858             self._execute_child(args, executable, preexec_fn, close_fds,
    859                                 pass_fds, cwd, env,
    860                                 startupinfo, creationflags, shell,

~\anaconda3\envs\OOMMF\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1309             # Start the process
   1310             try:
-> 1311                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1312                                          # no special security
   1313                                          None, None,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by code-whale** [comment]
@MichaelSherburne , Hi, I want to ask if your computer system is windows. If you are simulating under Windows system, I suggest you use docker to solve it. I also encountered this error about a few months ago. In addition, you can also see whether you can simulate for a long time (for example, the simulation time is expected to be greater than 1000-1500s). Some programs of ubermag do not work well under windows (I think). So I suggest you use docker

**Comment by lang-m** [comment]
@MichaelSherburne On Windows this tutorial is relying on Docker being installed because the DMI terms used in here are not available on Windows by default. The error message must be a result of `ubermag` not being able to find Docker on your system.

The next version of `ubermag` will come with an improved version of `OOMMF` that can run all DMI extensions natively on Windows without Docker.

**Comment by MichaelSherburne** [comment]
@lang-m and @code-whale thank you so much! I'll look into Docker.
