### ISSUE TITLE
Questions about DMI boundary conditions

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#193]
Dear Ubermag Team,
When reading this article(PHYSICAL REVIEW B 88, 184422 (2013),https://doi.org/10.1103/PhysRevB.88.184422), I found that this article analyzes the DMI boundary conditions.
![image](https://user-images.githubusercontent.com/61874432/148342137-2b9fae46-909e-4a53-bd4f-3e84249e6cfd.png)

 I want to ask how this can be achieved in ubermag. For example, in a thin film, the saturation magnetization is defined as follows:
````
def ms_fun(pos):
    x,y,z=pos
    if xa<=x<=xb and ya<y<yb:
        return 0
    else:
        return Ms
````
If a hole is defined, how can I model the DMI of the area boundary? Thank you for your help and look forward to your response!

**Comment by code-whale** [comment]
I found that the DMI of CNV class should be derived from this project（https://github.com/joommf/oommf-extension-dmi-cnv）, which shows that this extension has been verified in the finite size model, which means that this extension has considered the above DMI boundary conditions?

**Comment by marijanbeg** [comment]
Hi @code-whale, boundary conditions are a tricky topic. You can assume they are implemented right, which has been verified by a lot of tests :)

**Comment by code-whale** [comment]
@marijanbeg Thank you very much for telling me, thank you for your help!
