### ISSUE TITLE
Slonczewski term

### ISSUE THREAD

**Issue by Siyuanq** [ubermag/help#197]
I have a question on the Slonczewski term regarding to the following link.  'https://ubermag.github.io/api/_autosummary/micromagneticmodel.Slonczewski.html'
In the introduction of Damping term and Precession term, the explicit LLG equation is adopted. But in the Slonczewski term, it confuses me. There's no 'alpha' in the RHS so I assume it is in the implicit form, which is not consistent with other dynamic terms. I think ubermag uses 'Xf' extension of OOMMF and on the website 'https://kelvinxyfong.wordpress.com/research/research-interests/oommf-extensions/xf_stt/', I find it in the implicit form. So I want to confirm if the STT term is written in the implicit form.

Thanks

**Comment by Siyuanq** [comment]
same question for ZhangLi term. I suppose it is also written in implicit form.

**Comment by swapneelap** [comment]
@Siyuanq thank you for pointing it out. The representation of STT terms are in implicit form while the LLG is in explicit form. I will fix this and notify you soon.
