### ISSUE TITLE
td.drive error after Ubermag Update

### ISSUE THREAD

**Issue by MichaelSherburne** [ubermag/help#199]
I'm experiencing issues with Ubermag after the update. I downloaded everything into a new environment to make sure it was all new. Everything runs okay until I go to the td.drive line. I've tried looking in the example codes on the website to see if there were any changes to the syntax but they all appear the same. Below is a screenshot of my error. Please let me know what could of changed?

![image](https://user-images.githubusercontent.com/21108870/158043980-e1ed9780-d928-4fe1-9e9d-43691814148c.png)

**Comment by Ponsudana** [comment]
Hello @MichaelSherburne 
After the update "wave" syntax is changed as "func"
You can check the link:
https://ubermag.github.io/api/_autosummary/micromagneticmodel.Zeeman.html
Hope this helps.

**Comment by MichaelSherburne** [comment]
@Ponsudana thank you so much for the fast reply! That fixed it!
