### ISSUE TITLE
Eorro in oommf run

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#201]
Dear ubermag team:
       When I define the spatially varying D using such a method, df.Field(mesh,dim=1,D=D_fun), 'Eorro in oommf run' always occurs, and even running in docker. 
       Such an error also occurs when defining periodic boundary conditions.
       In the ubemrag documentation, these methods are supported and I would like to know the reasons for the error.
Thanks
![error(1)](https://user-images.githubusercontent.com/81371568/160281091-70c343c5-e05f-4646-92ac-9cdd3545f983.png)
![error(2)](https://user-images.githubusercontent.com/81371568/160281094-b543d7be-96ef-4a57-b6bc-bc3d6d492898.png)

**Comment by marijanbeg** [comment]
Hi @ZhiyuZhang001, thank you for your question and for using Ubermag. It is difficult to see what exactly went wrong without looking at the entire simulation script. Could you please share a minimal failing example with us?

I can notice in the command you sent us (`df.Field(mesh, dim=1, D=D_fun`) that you pass `D`. Field accepts `value`.

**Comment by lang-m** [comment]
Hi @ZhiyuZhang001 unfortunately OOMMF does not support DMI terms initialised with spatially varying parameters defined via `df.Field` (despite ubermag allowing it). You can only define a spatially varying material constant `D` by defining subregions with different `D`. You can have a `default` key (which is an Ubermag feature) and subregions can overlap (the first one to be defined at a certain point takes precedence, please also check the OOMMF documentation for this.) So maybe you can rewrite your problem to using subregions for the part with `D1` and have a default value `D2` for the rest of your sample.
