### ISSUE TITLE
the problem in calculating demagnetization field

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#202]
Dear ubermag team:
       In the ubermag documentation, I find that I can use dft.demag_tensor and dft.demag_field to calculate the demagnetization field, but I can't get the correct results in my simulations, and I'd like to know where the error occurs.

thanks
[effective_field.md](https://github.com/ubermag/help/files/8377355/effective_field.md)

**Comment by lang-m** [comment]
Fixed in ubermag/discretisedfield#137
