### ISSUE TITLE
Related problems when using the temperature evolver

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#207]
Dear Ubermag Team,
I encountered some problems when I tried to use temperature to calculate the micromagnetic problem. first of all, the results obtained by using the temperature evolver (temperature=0) are not consistent with those without the temperature solver. For example, skyrmion, which can be driven under the ordinary timedriver, cannot be driven after using the temperature evolver. In addition, Xf_ThermSpinXferEvolver temperature evolver cannot be used in zhangli model. Moreover, the method of Xf_ThermSpinXferEvolver must be specified as rk2heun at a non-zero temperature, otherwise an error will be reported, but the simulation will become very slow after specifying rk2heun. It takes about half a minute to simulate 1ps when the temperature is set to 50k and about 8 hours for 1 ns.
I don't know what caused these problems. You can help us. I have attached an ipynb file containing all the problems below for your inspection. Looking forward to your reply!
Best regards
code-whale
[temp test.ipynb.zip](https://github.com/ubermag/help/files/8958309/temp.test.ipynb.zip)

**Comment by lang-m** [comment]
@code-whale Maybe you can get help on the Mumag mailing list.
