### ISSUE TITLE
The property 'subregions' of micromagneticdata.Drive

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#209]
Dear Ubermag team:

     When we call micromagneticdata.Drive, the information about our defined
 subregions is missing here, which is very inconvenient for us to do some processing.
 I sincerely hope you will improve here in the next update.
![screenshots](https://user-images.githubusercontent.com/81371568/176094290-630efa77-cea1-47a3-a3af-7dfc00231467.png)
      Thank you for taking the time.

Best regards,

ZhiyuZhang

**Comment by lang-m** [comment]
Hi @ZhiyuZhang001 the missing subregion information is a know problem. Better support is planned for the future.

**Comment by lang-m** [comment]
Support for loading subregions has been added in Ubermag 0.66.0 (https://ubermag.github.io/changelog.html#oct-20-2022). Old simulations cannot be supported because the information has not been saved to disk before.
