### ISSUE TITLE
Slonczewski term units

### ISSUE THREAD

**Issue by fgr1986** [ubermag/help#215]
Hi. 

Acording to https://ubermag.github.io/api/_autosummary/micromagneticmodel.Slonczewski.html?highlight=slonczewski# the computed term gives  [A/m] =  (Joule * second)/( (Henry/meter)*Coulomb) * (Ampere / meter / meter) / (meter * Ampere / meter).
Should it not be multiplied by _gamma_, as per in https://math.nist.gov/oommf/doc/userguide20a2/userguide/Standard_Oxs_Ext_Child_Clas.html#SX

If this is the case, is the current module scaling the computed differential factor?

Apologies if this issue should have been posted to ubermag/help. Let me know if I should move it there.

Thanks

**Comment by swapneelap** [comment]
Hello @fgr1986,
Thank you for pointing this out. I will have a look at this and get back to you shortly! In the meantime, I have moved the issue to our `ubermag/help` repo.
~ Swapneel

**Comment by fgr1986** [comment]
Thank you very much, @swapneelap 
I am thinking, it might be useful to have a test comparing ZhangLi with Slonczewski  with a groundtruth, to check that there is no scaling factor messing around.

Please let me know if I can be of help.

**Comment by swapneelap** [comment]
Hello @fgr1986,

Ubermag does not integrate the LLG but writes a `MIF` file which is used by OOMMF to perform the calculations. The value of $\gamma$ is passed on to the `Oxs_SpinXferEvolve` evolver properly in the `MIF` file. Here, the discrepancy is in the LaTex representation of the Slonczewski term in the explicit LLG equation.

Moreover, we have tests for the Zhang-Li and Slonczewski dynamic terms in `ubermag/micromagnetictests`. Please have a look and open a PR if you think the tests can be extended. Also, It would be helpful if you can suggest the correct LaTex representation of the Slonczewski dynamic term.

Best,
Swapneel

**Comment by fgr1986** [comment]
Hi @swapneelap 
I believe, the modulo of gamma is missing, being gamma in [m/As].

Regards

**Comment by swapneelap** [comment]
Hello @fgr1986,
I agree that $\gamma$ is missing in the *formula* displayed on the website. However, consider the following simulation
```Python
import discretisedfield as df
import micromagneticmodel as mm
import numpy as np
import oommfc as oc

p1 = (0, 0, 0)
p2 = (20e-9, 20e-9, 2e-9)
cell = (2e-9, 2e-9, 2e-9)

mesh = df.Mesh(p1=p1, p2=p2, cell=cell)

# Material params
Msat = 800e3
Aex = 13e-12
alpha = 0.01

# CPP params
lambda_ = 1
Pol = 0.5669
epsilonprime = 0
angle = 20 * (np.pi / 180.0)
mp = (np.cos(angle), np.sin(angle), 0)
J = 1e12

system = mm.System(name="CPP")
system.m = df.Field(mesh=mesh, dim=3, value=(1, 0, 0), norm=Msat)
system.dynamics = (
    mm.Precession(gamma0=mm.consts.gamma0)
    + mm.Damping(alpha=alpha)
    + mm.Slonczewski(
        J=J,
        mp=mp,
        P=Pol,
        Lambda=lambda_,
        eps_prime = epsilonprime,
    )
)

driver = oc.TimeDriver()
driver.drive(system, t=1e-9, n=100)
```
This generates a `MIF` file in the folder `CPP/drive-0` which has the block
```MIF
# Slonczewski evolver
Specify Oxs_SpinXferEvolve:evolver {
  alpha 0.01
  gamma_G 221276.14872118403
  P 0.5669
  Lambda 1
  eps_prime 0
  J 1000000000000.0
  mp {0.9396926207859084 0.3420201433256687 0}
}
```
Here you can see that the value of $\gamma$ is passed on to the Slonczewski term *even though it is not explicitely defined in the `mm.Slonczewski()`* term. Does this answer your question?

Best regards,
Swapneel

**Comment by fgr1986** [comment]
Yes, indeed. Apologies, I meant it was missing in the documentation. As you said, it looks it passes the param to the evolver.

**Comment by swapneelap** [comment]
I'll open a PR soon to update the documentation. Please let me know if you have a suggestion for the right representation of the term.

**Comment by fgr1986** [comment]
https://github.com/ubermag/micromagneticmodel/pull/55
