### ISSUE TITLE
Import error for discretisedfield on Google Colab

### ISSUE THREAD

**Issue by bolozubaankesari** [ubermag/help#216]
I tried import discretisedfield on Google Colab and it throws the following error. 
![discretisedfield_import_error](https://user-images.githubusercontent.com/74605094/180858862-8e5fac5a-9f62-4afe-bc8c-e7384a7efbb8.png)
Would appreciate any and all help!

**Comment by bolozubaankesari** [comment]
Thanks for your response. I am facing another error while import oommfc, discretisedfield and micromagnetic model. 
`module 'dask.array' has no attribute 'lib'`
How can I resolve this?

**Comment by lang-m** [comment]
@bolozubaankesari This seems to be related to some problem with `xarray`, one of our dependencies. A workaround for this is to install `dask`.
