### ISSUE TITLE
mumax3c data extraction

### ISSUE THREAD

**Issue by Siyuanq** [ubermag/help#217]
When use ubermag, I use m = data[i][j].array to convert the file to numpy array, where i is the drive number and j is the time step.
But when I use mumax3c, I use the same command for date convert but there is error report that list index out of range. The drive number is 30 and time step is 1000. The following are the error report of data convert.

<img width="970" alt="截屏2022-08-01 下午12 47 56" src="https://user-images.githubusercontent.com/68694112/182210677-40838de2-591a-4bd8-8d05-9b3452228219.png">

**Comment by Siyuanq** [comment]
I am curious is all the mumax3c command is the same as oommfc? If I would like to use like data[i][j].m.x.plane('z').mpl(), Is it exactly the same as in oommfc? I tried but failed.

**Comment by lang-m** [comment]
Hi @Siyuanq there is no (indented) difference between `mumax3c` and `oommfc`. Please re-check if the problem is really coming from `ubermag` (e.g. also compare against `data.info`) and report back.
