### ISSUE TITLE
instantiate abstract class TimeDriver with abstract methods _x

### ISSUE THREAD

**Issue by Siyuanq** [ubermag/help#219]
I have a error report when I run my code in the CentOS. I run other codes which were executable previously and they all have the same problem now. What I did these days is that I instore another lower version ubermag in another virtual environment to run mumax3c. Here is the error report.
![截屏2022-08-06 上午10 59 40](https://user-images.githubusercontent.com/68694112/183256620-4d4a9803-ffd0-46e9-980e-553de44e8b09.png)

**Comment by Siyuanq** [comment]
both timedriver and mindriver are not executable.

**Comment by fangohr** [comment]
Which versions of `ubermag` and `oommfc` have you got installed?

Please also post the complete code example. (See https://fangohr.github.io/computing/smartquestion.html for some suggestions.)

**Comment by Siyuanq** [comment]
I use ubermag 0.65.0 and oommfc 0.63.0 and the following is the code. Thanks for your help!
![截屏2022-08-08 下午2 33 39](https://user-images.githubusercontent.com/68694112/183499420-5d31fc7c-10ae-46ab-968b-0ff6a5f5efc4.png)
![截屏2022-08-08 下午2 33 53](https://user-images.githubusercontent.com/68694112/183499489-24c1ac97-277a-4480-b8de-f44b28cc7aab.png)

**Comment by Siyuanq** [comment]
the ubermag is 0.65.0 and oommfc is 0.63.0. The following is the code. I really appreciate your efforts.
![截屏2022-08-08 下午2 45 19](https://user-images.githubusercontent.com/68694112/183501472-cc673366-f7ec-4f27-b47a-aaf20be1dec1.png)
![截屏2022-08-08 下午2 46 10](https://user-images.githubusercontent.com/68694112/183501613-27acc16c-9c87-4409-894b-ce50c9d528ce.png)

**Comment by samjrholt** [comment]
Hi @Siyuanq , I've just tried a shortened version of your code and it seems to be working on my system and on the Binder. This would indicate that the issue is likely to be a local one. I would try force reinstalling the `ubermag` metapackage and if that doesn't work maybe trying a clean environment. Let us know how it goes.

p.s. it looks like you create a function to initiate the Ms value but dont actually use it. This might be intentional but just in case!

![image](https://user-images.githubusercontent.com/48217392/183512509-91b657af-ac20-4b89-ad68-d30c1b14c2d0.png)

**Comment by Siyuanq** [comment]
Thank you for your help! I have found the way to solve this problem but I do not know why. Previously I use conda to install the ubermag and it works well. But last time I wanted a lower version ubermag0.64.0 for mumax3c but the install process is stuck in the "solving environment" so I turn to pip. Today I deleted the previous virtual environment and do multiple trials and find that:  when I use conda to install ubermag, there is error report. But if I use pip to install ubermag, there is no error report.

**Comment by Siyuanq** [comment]
I'd like to report a feature, maybe not a universal problem. That when I use pip to install ubermag, docker does not have authority to write the mif file, but when I use conda to install, it has. I do not have problems remaining to be resolved now, just a remind if anyone have the same issues as me that try conda may help.
The picture is the error report when I use pip installed version.
![thumbnail_截屏2022-08-24 下午2 21 02](https://user-images.githubusercontent.com/68694112/186749799-9eeb47fe-5ef7-4271-ac50-7f4e8bd3d77c.png)
