### ISSUE TITLE
KeyError: DMI in calculating DMI energy

### ISSUE THREAD

**Issue by be-zimmermann** [ubermag/help#22]
_Dear JOOMMF-Team,_

_first of all: Thank you for creating this very nice Python interface to OOMMF! I leaned about JOOMMF and oommfc at the ICM2018-workshop (excellent tutorial by Marijan Beg!!!)._

Here comes the specific problem:
========================
Trying to access the DMI energy of a system, a `KeyError: DMI` is thrown (see below). I tested the crystal classes 'o', 't', and 'cnv', and all produce the error. Other energy terms (Exchange, Demagnetizing energy) are calculated and seem reasonable.

Here is a minimal example:
```
import oommfc as oc
import discretisedfield as df

# Geometry
L = 100e-9  # x and y dimensions of the sample
t = 1e-9    # thickness of the sample

# Material (permalloy) parameters
Ms = 8e5  # saturation magnetisation (A/m)
A = 1.3e-11  # exchange energy constant (J/m)
D = 1e-3     # DMI constant (J/m**2)

system = oc.System(name='mininmalExampleDMIError')
cell = (5e-9, 5e-9, t)  # mesh discretisation (m)

mesh = oc.Mesh(p1=(0, 0, 0), p2=(L,L,t), cell=cell)  # Create a mesh object.
system.hamiltonian = oc.Exchange(A) + oc.Demag() + oc.DMI(D=D, crystalclass="interfacial")
system.m = df.Field(mesh, value=(1,1,1), norm=Ms)

print(system.hamiltonian.terms)
#out: [Exchange(A=1.3e-11, name="exchange"), Demag(name="demag"), DMI(D=0.001, crystalclass="cnv", name="dmi")]
print(system.hamiltonian.terms[0].energy) #exchange energy
# 0.0
print(system.hamiltonian.terms[1].energy) #demagnetizing energy
# 1.3404128655307846e-18
print(system.hamiltonian.terms[2].energy) #DMI energy
#KeyError                                  Traceback (most recent call last)
```

This is the traceback of the error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/test/oommf/DMI_energy_minimal.py in <module>()
     27 print(system.hamiltonian.terms[1].energy) #demagnetizing energy
     28 # 2.1187568659238725e-18
---> 29 print(system.hamiltonian.terms[2].energy) #DMI energy

~/Library/Python/3.6/lib/python/site-packages/micromagneticmodel/hamiltonian/energyproperties.py in energy(self)
     14     @property
     15     def energy(self):
---> 16         return self._data.energy
     17 
     18     @property

~/Library/Python/3.6/lib/python/site-packages/oommfc/data.py in energy(self)
     41         dt = oommfodt.read(odt_file, replace_columns=False)
     42 
---> 43         return dt[_dict[self.cls]][0]
     44 
     45     @property

KeyError: 'DMI'
```

**Comment by marijanbeg** [comment]
Hello, thank you for your question. We are glad you are using JOOMMF. To understand better what is the issue on your system, could you please:

1. Tell us what operating system you use
2. Send me the *.odt file which should be in `mininmalExampleDMIError` directory

Of course, let me know if anything does not make sense.

PS. I would recommend using `system.hamiltonian.exchange.energy` or `system.hamiltonian.dmi.energy` instead of indexing terms list. Maybe further examples can be found here: https://oommfc.readthedocs.io/en/latest/ipynb/derived_fields.html.

**Comment by marijanbeg** [comment]
That is a bug in JOOMMF. Thanks a lot for letting us know. I will fix that, but it is probably going to take a few days until it propagates to `conda` cloud. You will need to update your `joommf` installation in a few days, by running `conda upgrade joommf`. I will let you know here when everything is ready for an update.

Please raise further issues if you spot any other problems - this helps us a lot.

**Comment by be-zimmermann** [comment]
Thank you. As a temporary workaround, can I assume that the DMI-energy is the difference of the total energy and all other energy terms?

**Comment by marijanbeg** [comment]
Yes, you can. After a driver run, you can also get `system.dt` data table where you can find the DMI energy.

**Comment by fangohr** [comment]
@be-zimmermann - has this issue been resolved?

**Comment by fangohr** [comment]
This is over a year old now - I'll close it.
