### ISSUE TITLE
Discrepancy in Slonczewski documentation

### ISSUE THREAD

**Issue by vinodnaikb** [ubermag/help#220]
@fangohr @JLeliaert @marijanbeg @swapneelap @samjrholt 
[Slonczewski ubermag documentation-discrepancy.pdf](https://github.com/ubermag/help/files/9337615/Slonczewski.ubermag.documentation-discrepancy.pdf)

I feel there are discrepancies in the 'signs' in the documentation of the Slonczewski STT term. I have attached a document regarding the same. I request the Ubermag team to check this.

**Comment by swapneelap** [comment]
Hello @vinodnaikb, thank you for submitting the issue. I can confirm that I get the same expression for explicit form of the LLG equation as you have mentioned in the document in the presence of Slonczewski terms. I will be opening a PR soon to rectify it.

**Comment by marijanbeg** [comment]
This issue could be related to #215.

**Comment by marijanbeg** [comment]
Thanks a lot, @swapneelap!

**Comment by vinodnaikb** [comment]
Thank you for the immediate response. On Mon, 15 Aug 2022 at 8:26 PM, Swapneel Amit Pathak ***@***.***> wrote:
Hello @vinodnaikb, thank you for submitting the issue. I can confirm that I get the same expression for explicit form of the LLG equation as you have mentioned in the document in the presence of Slonczewski terms. I will be opening a PR soon to rectify it.
