### ISSUE TITLE
How to define a rectangular subregion at angle of 135 degree from x axis.

### ISSUE THREAD

**Issue by Shobhn** [ubermag/help#221]
Hi,

I would like to know that is it possible to define a subregion inside the mesh such that it is a tilted rectangle at 135 degree from x axis. I have attached an image showing the subregion I want to define. 
Kindly help me through this :)
![subregion](https://user-images.githubusercontent.com/91781486/184658173-4eab0c27-d32e-4afa-9dbd-5fa2dbd6e9d4.png)

**Comment by marijanbeg** [comment]
Hi @Shobhn, thank you for raising this issue and for using Ubermag. Unfortunately, this is not possible. What we would suggest doing, in this case, is to define spatially varying parameters using `df.Field`: https://ubermag.github.io/documentation/notebooks/discretisedfield/field-spatially-varying.html

I hope this answers your question. I will close this issue now, but please do not hesitate to add comments or open new issues. :)
