### ISSUE TITLE
Javascript error for K3D

### ISSUE THREAD

**Issue by muntasir-mahdi** [ubermag/help#223]
### What might be the problem?
![Screenshot 2022-09-04 173216](https://user-images.githubusercontent.com/16884661/188336145-53742644-f31d-4b4b-8167-63c22dc4f412.png)
![Screenshot 2022-09-04 173238](https://user-images.githubusercontent.com/16884661/188336146-fa25daa9-7e3f-46e7-ad42-0a425c03dfcc.png)

**Comment by lang-m** [comment]
@muntasir-mahdi If you use Jupyter Notebook (instead of Jupyter lab) you have to manually enable the k3d extension. See here for details: https://github.com/K3D-tools/K3D-jupyter#pypi
