### ISSUE TITLE
Multiple torques in dynamic term

### ISSUE THREAD

**Issue by fgr1986** [ubermag/help#224]
Good morning.
I just noticed that at the moment, the driver's python interface fails to add multiple torques to the MIF file.

```
...
torque0 = mm.Slonczewski(J=J0, mp=MP_0, eps_prime=0,  Lambda=1.2, P=P0, name='torque0 ')
torque1 = mm.Slonczewski(J=J1, mp=MP_1, eps_prime=0,  Lambda=1.2, P=P1, name='torque1 ')
...
system.dynamics += torque0 
system.dynamics += torque1
...
```

Error at:
https://github.com/ubermag/oommfc/blob/master/oommfc/scripts/driver.py#L158
as only one term is expected

```
    156             setattr(driver.evolver, arg, getattr(zhang_li, arg))
    157 if system.dynamics.get(type=mm.Slonczewski):
--> 158     (slonczewski,) = system.dynamics.get(type=mm.Slonczewski)
    159     driver.evolver.J = slonczewski.J
    160     driver.evolver.mp = slonczewski.mp

ValueError: too many values to unpack (expected 1)
```

Thank you very much.

**Comment by vinodnaikb** [comment]
![Untitled](https://user-images.githubusercontent.com/109891764/193571222-a5ad3a81-a2bc-42c7-9ee5-971d08066ea0.png)

It worked for me, see the image

**Comment by swapneelap** [comment]
Hello @fgr1986,
I am not sure what it means, physically, to have two Slonczewski terms. Will you be able to send me the full notebook used for the simulation so that I can understand the problem better?

@vinodnaikb I am assuming that the error will originate from `oommfc` when you will drive the system.

**Comment by vinodnaikb** [comment]
I did the time drive,  it worked fine.

**Comment by fgr1986** [comment]
Apologies for the delay.

```
import oommfc as oc
import discretisedfield as df
import micromagneticmodel as mm
import micromagneticdata
import numpy as np
import os


def test():
    p1 = (-25e-9, -25e-9, 0e-9)
    p2 = (25e-9, 25e-9, 1e-9)
    cell = (5e-9, 5e-9, 1e-9)

    def Ms_fun(pos):
        """Function to set magnetisation: zero outside cylindric shape"""
        x, y, z = pos
        if (x**2 + y**2)**0.5 < p2[1]:
            return 1e6
        else:
            return 0

    region = df.Region(p1=p1, p2=p2)

    mesh = df.Mesh(region=region, cell=cell)
    system = mm.System(name='test')
    
    uniaxial_anisotropy = mm.UniaxialAnisotropy(K=5e5, u=np.array([0., 0., -1]))
    t_0 = mm.Slonczewski(J=1e12,
                         mp=np.array([0., 0., -1]),
                         eps_prime=0,
                         Lambda=1.2,
                         P=0.7,
                         name='torque_0')
    
    t_1 = mm.Slonczewski(J=1e12,
                         mp=np.array([0., 1., -0.]),
                         eps_prime=0,
                         Lambda=1.2,
                         P=0.7,
                         name='torque_1')

    # system.hamiltonian = uniaxial_anisotropy + demag
    system.energy = 0.
    system.energy += mm.Exchange(A=1e-12)
    system.energy += mm.Demag()
    system.energy += uniaxial_anisotropy

    # dynamics
    # gamma0 2.211e5  # gyrotropic ration
    system.dynamics = mm.Precession(gamma0=1.76e11 * 1.25663706212e-6)
    system.dynamics += mm.Damping(alpha=0.01)
    system.dynamics += t_0
    system.dynamics += t_1

    # initial magnetization
    m0 = df.Field(mesh, dim=3, value=(0., 0., -1), norm=Ms_fun)
    system.m = m0

    td = oc.TimeDriver()
    td.drive(system, 
             t=2e-9, 
             n=100,
             n_threads=8,
             dirname='_transient')
```

**Comment by lang-m** [comment]
@fgr1986 As far as I know OOMMF does not support multiple Slonczewski terms. Looking at your code you use the exact same parameters (apart from `mp`) for your two current terms. Could you not combine them "manually", i.e. calculate the resulting effective `mp` and adjust the current strength `J`, and only use a single effective Slonczewski term?

**Comment by lang-m** [comment]
@vinodnaikb I am surprised to hear that multiple Slonczewski terms worked for you (it does not for me with the current version of oommfc). Which version do you use (`python3 -c "import oommfc; print(oommfc.__version__)"`)?

**Comment by fgr1986** [comment]
Thanks for your answer, @lang-m .
This was just a toy example, in the experiments I am conducting both have independent parameters.
Indeed in version 0.63.0 we face the 1 torque limitation.

**Comment by lang-m** [comment]
@fgr1986 Please note that your simulation also does **not** work with version < 0.63.0. When running your code with older versions the Slonczewski terms are both ignored (silently, so it is impossible to tell without looking at the mif file) due to a bug in setting up the Slonczewski term when a custom name is used.
