### ISSUE TITLE
Thermal Field Term

### ISSUE THREAD

**Issue by vinodnaikb** [ubermag/help#226]
Good evening, @swapneelap @samjrholt @marijanbeg 

I didn't see any reference regarding the thermal field in the ubermag. 
I'm talking about this https://kelvinxyfong.wordpress.com/research/research-interests/oommf-extensions/xf_thermheunevolve/
Please suggest how to include this thermal field to the field term.

**Comment by swapneelap** [comment]
Hello @vinodnaikb,
You can use `oommfc.Xf_ThermHeunEvolver`. For example,
```Python
...
import oommfc as oc
import micromagneticmodel as mm
...
system = mm.System(name="Temp_sys", T=150)  # Temperature in K
...
evlr = oc.Xf_ThermHeunEvolver()
driver = oc.TimeDriver(evolver=evlr)
driver.drive(system, t=1e-10, n=10)
``` 
I hope this helps. You can also refere to [this example](https://ubermag.github.io/examples/notebooks/finite-temperature.html) which uses `UHH_ThetaEvolver`, however, the process is the same. If this solves your problem, then please close the issue.
