### ISSUE TITLE
How to define irregular regione

### ISSUE THREAD

**Issue by yejinhong10** [ubermag/help#228]
I am trying to define irregular region, such as a sphere with a bump somewhere. 

region1 = df.Region(p1 = (-100e-9, -100e-9, 0), p2 = (100e-9, 100e-9, 4e-9))
region2 =df.Region(p1=(100e-9,100e-9,0),p2=(110e-9,110e-9,4e-9))
region = region1+region2
mesh = df.Mesh(region=region, cell=(5e-9, 5e-9, 1e-9))

This is what I tried, but + is not a supported operant. Is there anyway I can do this? Thanks!

**Comment by fangohr** [comment]
Here is an example that shows how to create a cylinder in 3d space. https://ubermag.github.io/examples/notebooks/13-tutorial-skyrmion.html . The important cell is `[5]`.

You can in principle extend this arbitrarily to realise any shape.
