### ISSUE TITLE
Time-Dependent Anisotropy and Magnetization term in the UBERMAG simulation

### ISSUE THREAD

**Issue by DebanjanPolley** [ubermag/help#232]
Hi,
Is it possible to include a time-dependent energy term in the equation? I have previously used a constant exchange and anisotropy energy. 

`system.energy = mm.Exchange(A=A) + mm.Zeeman(H=H) + mm.UniaxialAnisotropy(K=K1, u=(0,0,1)) + mm.Demag()`

After defining the energy term, I drive current-induced dynamics to study SOT-induced magnetization dynamics with a gaussian current pulse as the following:

```
system.dynamics = mm.Precession(gamma0=gamma0) + mm.Damping(alpha=alpha) + mm.Slonczewski(J = Jc1, mp = (0, dirc, 0), P = P, Lambda = L, eps_prime = ep_imag,func=time_func,dt=2e-13)
td = oc.TimeDriver()
td.drive(system, t=1000e-12, n=1000)
```

However, in my experiment, the norm of magnetization and anisotropy energy amplitude varies as a function of time and I have the datasets for this time-dependent magnetization and anisotropy. 

So far, I have tried the following procedure. I am running the time driver for a small time when the anisotropy can be considered constant and in the next iteration, I am updating new values of anisotropy. This gives me somewhat expected result:

```
times = np.linspace(0, 1000e-12, 1000)
system.m = df.Field(mesh, dim=3, value=(0.02,0,0.98), norm=Ms_T(times)[0])
for i in (range(len(times)):
    system.m = df.Field(mesh, dim=3, value=(0.02,0,0.98), norm=Ms_T(times)[i])
    system.energy = mm.Exchange(A=A) + mm.Zeeman(H=H) + mm.UniaxialAnisotropy(K=Kz_T(times)[i], u=(0,0,1)) + mm.Demag()
    system.dynamics = mm.Precession(gamma0=gamma0) + mm.Damping(alpha=alpha) +  mm.Slonczewski(J=Jc_array[i], mp = (0, dirc, 0), P = P, Lambda = L, eps_prime = ep_imag) 
    td = oc.TimeDriver()
    td.drive(system, t=1e-12, n=10)

```
However, is it possible to use a time-dependent magnetization where `Ms_T` varies with time? I tried inserting
`system.m = df.Field(mesh, dim=3, value=(0.02,0,0.98), norm=Ms_T(times)[i])` into the for loop to simulate this effect, but it is then giving me strange results. 

Is there any way to simulate this with ubermag?

**Comment by lang-m** [comment]
The code overall looks okay to to such types of simulations. There is a minor mistake in the first line of your loop (`    system.m = df.Field(mesh, dim=3, value=(0.02,0,0.98), norm=Ms_T(times)[i])`). You reset the magnetisation (`value`) during each iteration. Instead you should be able to just use `system.m.norm = Ms_T(times)[i]`.

**Comment by lang-m** [comment]
Here is an improved version:
```python
times = np.linspace(0, 1000e-12, 1000)
system.m = df.Field(mesh, dim=3, value=(0.02,0,0.98), norm=Ms_T(times)[0])
system.energy = mm.Exchange(A=A) + mm.Zeeman(H=H) + mm.UniaxialAnisotropy(K=Kz_T(times)[0], u=(0,0,1)) + mm.Demag()
system.dynamics = mm.Precession(gamma0=gamma0) + mm.Damping(alpha=alpha) +  mm.Slonczewski(J=Jc_array[0], mp = (0, dirc, 0), P = P, Lambda = L, eps_prime = ep_imag) 
td = oc.TimeDriver()
for i in (range(len(times)):
    system.m.norm = Ms_T(times)[i]
    system.energy.uniaxialanisotropy.K = Kz_T(times)[i]
    system.dynamics.slonczewski.J = Jc_array[i]
    td.drive(system, t=1e-12, n=10)
```
