### ISSUE TITLE
Help Writing an Anisotropic DMI Energy Term

### ISSUE THREAD

**Issue by EleyGroup** [ubermag/help#234]
Hello,

I'm trying to implement anisotropic DMI into my simulation and am a bit confused on how to do this after reading through the documentation. The example provided online only ever explicitly defines an energy term by its latex representation, and I don't see how this provides enough information.  The particular term I'd like to add is as follows:

$$ E_{aniso} = D\left( u_x L_{yz}^{(x)} + u_y L_{zx}^{(y)} + u_z L_{xy}^{(z)} \right) $$

where $(u_x,u_y,u_z)$ is a unit vector I want to specify, and $L_{jk}^{(i)} = m_j \frac{\partial m_k}{\partial i} - m_k \frac{\partial m_j}{\partial i}$. I'd really appreciate if someone could help me with the coding to do this. I intend to assign different $\mathbf{u}$ and $D$ parameters to various subregions in my simulation region. 

Thank you.

**Comment by fangohr** [comment]
Ubermag delegates the actual solving of the differential equations to OOMMF or mumax3. The maximum functionality provided by Ubermag is thus what is available from OOMMF / mumax (and potentially other such micromagnetic 'calculators' in the future). The latex terms Ubermag displays are meant to make it easier to understand what model you use, but they cannot be used to define an equation (to be solved by Ubermag and thus OOMMF/Mumax).

The term you are interested is not available (as far as I know) in either OOMMF or mumax. So the first step would be to implement that term in these packages.
