### ISSUE TITLE
How to generate irregular regions/shape of fields whose contour cannot described by functions easily.

### ISSUE THREAD

**Issue by Andyuch** [ubermag/help#236]
Dear Sir,
This problem stems from the situation that will be encountered in reality. Especially in the surface of thin films, there are irregular domains, just like the image shown. 
![Untitled](https://user-images.githubusercontent.com/105619884/222895422-a709789a-5f86-43ac-b9a4-05893c3e7699.jpg)
In this case, I want to set the magnetization for different areas (different color blocks).  
So how can we define these irrgular regions and fields in our simulation?
Any help will be really appreciated.

**Comment by lang-m** [comment]
Hi @Andyuch, you could do this using additional (Python) packages as follows.
- Create an image (or a series of images for a 3d sample) with an external program to define the different regions (so grey-scale would be good) and save as `png`.
- Use one of the standard Python image libraries (e.g. `imageio` or `PIL`) to load the image and convert it into a numpy array.
- Use this array to select the different parts of the mesh to initialise the magnetisation as desired.
