### ISSUE TITLE
print the value of the stop parameter every some step number

### ISSUE THREAD

**Issue by mcastrob91** [ubermag/help#237]
Hi,

It is possible to visualize the value of the stop parameter in the minimization driver (in real-time). I remember that in oommf this can be done by setting the Datatable.

thanks

**Comment by lang-m** [comment]
Hi @mcastrob91 there is no possibility in Ubermag to visualise the parameter in real-time. You can inspect it after the simulation has finished using `micromagneticdata` and `micromagnetictable` (or `system.table` for the current simulation).

Note, that for energy minimisation you would need to activate saving individual steps (which in Ubermag currently comes with the restriction that it will save table data **and** magnetisation data after each step).
