### ISSUE TITLE
CALCULATE FMR FOR THIN FILM SINGLE LAYER PERMALLOY 

### ISSUE THREAD

**Issue by jmiasif** [ubermag/help#242]
HELLO UBERMAG TEAM
I am beginner to use ubermag, i am using miniconda jupyter in window. and want to simulate fmr for thin film single layer structure as well as double layer. please help me out thankyou 

thanks and regards 
asif

**Comment by lang-m** [comment]
Here is a notebook for FMR: https://github.com/ubermag/workshop/blob/2022-06-29/tutorials/skyrmion_tubes.ipynb
You can find a multi-layer structure in this notebook: https://github.com/ubermag/workshop/blob/2022-06-29/tutorials/SAF.ipynb

Some of the syntax in these two notebooks might be slightly outdated. Please refer to the documentation https://ubermag.github.io/ for up-to-date syntax.
