### ISSUE TITLE
How to obtain each cell co-ordinate and it's corresponding magnetization.

### ISSUE THREAD

**Issue by ssailsahanaa** [ubermag/help#243]
In a geometrical structure after applying external magnetic field  I need the final magnetization of each cell along with it's co-ordinate.I have attached file for the geometry and the external magnetic field..
[import micromagneticmodel as mm.txt](https://github.com/ubermag/help/files/11417941/import.micromagneticmodel.as.mm.txt)

**Comment by fangohr** [comment]
The object holding the magnetisation (`system.m`) is a `Discretisedfield` object. From that discretisedfield object you can get the coordinates of all the cuboids and the associated vectors. 

The documentation is at https://ubermag.github.io/documentation/discretisedfield.html .

**Comment by fangohr** [comment]
Here is how to get a numpy array with the data of the magnetisation vector field from a discretised field: https://ubermag.github.io/documentation/notebooks/discretisedfield/field-definition.html (`field.array`)

You may also like this example regarding the coordinates: https://ubermag.github.io/documentation/notebooks/discretisedfield/field-operations.html#Iterating-through-the-field
