### ISSUE TITLE
Demagnetizing factor calculation using OOMMF generated files 

### ISSUE THREAD

**Issue by talekarpm1** [ubermag/help#244]
How to Calculate Demagnetizing factor using OOMMF generated files (magnetization.omf and demagnetization.ohf) for thin permalloy pattern?

**Comment by lang-m** [comment]
We currently do not have any functionality to calculate the demagnetization factor. You can use discretisedfield to load the data and get the underlying numpy array (field.array) to implement it yourself.

If you implement it yourself, we would be interested to discuss possibilities of integrating your code into Ubermag.
