### ISSUE TITLE
Wrong relativistic wavelength expression found

### ISSUE THREAD

**Issue by KylinGuo** [ubermag/help#245]
The relativistic wavelength expression given at the following page
```
https://ubermag.github.io/api/_autosummary/mag2exp.ltem.relativistic_wavelength.html#mag2exp.ltem.relativistic_wavelength
```
 is wrong. See the image below. 

![image](https://github.com/ubermag/ubermag/assets/32160749/9e5f16c3-82a2-44b9-aee9-11775f153627)

Please correct it. One could find the details at the following page
```
https://zhuanlan.zhihu.com/p/629008312
```
It was given in Chinese but the result is quiet straightforward. 

![image](https://github.com/ubermag/ubermag/assets/32160749/32012517-9b9a-46f7-8f48-b727548c7b08)

**Comment by samjrholt** [comment]
@KylinGuo Thank you for pointing this out. I can confirm that whilst the code is correct the expression given in the API documentation has an additional $2 m0 e U$ term. This has now been updated on the master branch of mag2exp and will appear on the website when we next update it.
