### ISSUE TITLE
Spin Orbit Torque

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#247]
Hello!
I am doing micromagnetic calculations and need to add SOT for my research, I wonder if this is possible with the current version of UBERMAG and if not, will SOT be added in the next update?

**Comment by swapneelap** [comment]
Hello @ZhiyuZhang001, spin orbit torque (SOT) is not explicitly implemented in either OOMMF or mumax3 at the moment. Since, ubermag uses these "calculators" to perform the simulations under the hood, they need to support it first in order to use SOT.
