### ISSUE TITLE
How to plot intensity Vs H(field)

### ISSUE THREAD

**Issue by Milad-spinwave** [ubermag/help#249]
Dear all,
Hi. I hope you are doing well and enjoying using Ubermag. I want to plot the intensity (on the vertical axis) Vs. H ( for example, from 9 to 13 KOe on the horizontal axis)  for the single layer permalloy (FMR, I mean). Can you please kindly guide me? I must add a loop in FMR standard problem example in ubermag tutorial? In fact, we plotted with COMSOL, but I want to do it with ubermag and use ubermag for the simulation part of my paper.

**Comment by fangohr** [comment]
You question is not clear - we don't know about your paper. Your question may also be out of scope for this forum. 

Please check https://fangohr.github.io/computing/smartquestion.html for some guidance .

**Comment by Milad-spinwave** [comment]
Dear Prof.Fangohr,
Thanks for your kind reply. My question is completely related to the forum. I know at least 6 other PhD students like me who needs this. Yes maybe I didn't make it clear. I will send you email if you don't mind
Best regards,
Milad(Southeast University-Nanjing-China)
