### ISSUE TITLE
Combining scalar and vector graphs.

### ISSUE THREAD

**Issue by SeregaKR** [ubermag/help#251]
Good afternoon.
I need to combine the scalar and vector plots as specified here: https://ubermag.github.io/documentation/notebooks/discretisedfield/field-matplotlib-visualisation.html

Firsly, I load ovf file, rotate it by 90 degree and try to plot it. But I get the following error: R**egion <...> of the provided field does not contain Region <...> of the field that is being created.**

The code is attached below.
```
#figure properties, subfigures
fig = plt.figure(constrained_layout = True,  figsize = (10,3))
(subfig_l, subfig_r) = fig.subfigures(1, 2, width_ratios=[1, 3], height_ratios=[1.5], squeeze=True)
fig.set_constrained_layout_pads(hspace=0., wspace=0., w_pad = 0., h_pad = 0.)

#now we enter the first subfigure and do subplot inside
(axs_l) = subfig_l.subplots(ncols = 1, nrows = 1)

#load from ovf - I didn't put full path naturally
part_cut = df.Field.fromfile("m_full000000.ovf")

#now we rotate he graph - so everything will be uniform
part_cut_fin = df.FieldRotator(part_cut)
part_cut_fin.rotate("from_euler", seq="z", angles=np.pi / 2)

#the scalar part is fine
im0 = part_cut_fin.field.plane(z=30e-9).z.mpl.scalar(ax=axs_l,colorbar=False, norm=norm1)

#here we got an error
part_cut_fin.field.plane(z=30e-9, n=(12, 12)).mpl.vector(ax=axs_l, colorbar=False) 
```
I work with exactly the same file on the exact same plane. What can be the problem?

**Comment by SeregaKR** [comment]
If I change 30e-9 to let's say 10e-9 it starts working

**Comment by lang-m** [comment]
Hi @SeregaKR ,

that sounds a bit like a problem of floating point inaccuracies. However, to properly help we need the full error message, in particular the parts `<...>` that you left out, and ideally also the file that you are trying to plot.

**Comment by SeregaKR** [comment]
Thank you for a quick answer. The full error message is as follows:

> Region(p1=(-5.293955920339377e-23, -5.293955920339377e-23, 0.0), p2=(4.0000000000000003e-07, 4.0000000000000003e-07, 3e-08)) of the provided field does not contain Region(p1=(-5.293955920339377e-23, -5.293955920339377e-2, 3, 2.9062499999999996e-08), p2=(4.0000000000000003e-07, 4.0000000000000003e-07, 3.0937499999999995e-08)) of the field that is being created.

The ovf file is also attached.
[m_full000000.zip](https://github.com/ubermag/help/files/11981448/m_full000000.zip)

**Comment by lang-m** [comment]
Hi @SeregaKR 
thanks for sharing the file. This is a bug in the resampling code (`n=(12, 12)`) of the `plane` method. As a work-around, please use a smaller z value within the same cell. Using the cell centre (`part_cut_fin.field.mesh.midpoints.z[-1]`) seems to work without any issues.

Note: In the next version of Ubermag the `plane` will be replaced by a new method that does not have the problem.

Closing as completed. Please re-open if you still face any issues.
