### ISSUE TITLE
Adding a custom energy term in micromagneticmodel

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#252]
Hi !
When I use Ubermag to do my research, I find that I cannot add a custom energy term in mm.energy. In Fig.1, I write an energy term, which represent an anisotropic DMI energy. However, this term cannot be added in mm.energyterm. I want to know how to add this kind of field or energy term to micromagnetic system in Ubermag, and use oommfc to complete the calculation.
Thank you !
![fig 1](https://github.com/ubermag/help/assets/81371568/c6ec1ac2-e4c0-44de-910b-825e6ff548c5)

**Comment by swapneelap** [comment]
Hello @ZhiyuZhang001, to use your custom energy term with one of the micromagnetic calculators, either `oommfc` or `mumax3c`, it is not enough to just add the energy term to the `micromagneticmodel`. You will also need to add the extension to the calculator programs (i.e. `OOMMF` or `mumax3`) as well. Further, you will need to update the scripts in `oommfc` and `mumax3c` to write a correct configuration file that refers to your added extension when you have your custom energy term present in `system.energy`.

**Comment by ZhiyuZhang001** [comment]
Thank you for your reply. This issue is important to me, but I'm not sure how to realize it. Can you give me some specific advice?
