### ISSUE TITLE
Importing .ovf and visualising it on ubermag

### ISSUE THREAD

**Issue by Mishrakishan** [ubermag/help#253]
Hi, 
Thank you for developing Ubermag. I have generated a series of ovf files from mumax3 for a device structure. I tried to post-process the simulated ovf file on ubermag. I have successfully read the ovf file but while making a vector plot using mpl or k3d, there seems some glitch.

Most of the time there are no vector-only scalar plots. I tried to create a similar mesh to that of mumax3 but it takes a huge amount of time to run.
What is the process to plot a compatible scalar and vector plot together that is compatible with ovf file.

A script of code I've taken from the documentation:
```
%matplotlib inline
field_read = df.Field.fromfile('/Users/kishi/Downloads/R128nm/m000008.ovf')

import matplotlib.pyplot as plt
from matplotlib import style
style.use('seaborn-white')
fig, ax = plt.subplots(figsize=(9, 7))
field_read.plane(z = 1e-9, n = (128, 64)).mpl(ax=ax,
    scalar_kw={"cmap": "bwr", "interpolation": "spline16", "colorbar": False,"colorbar_label": "Magnetization ($\mathbf{M_z}$)" },
    vector_kw={
        "color": "black",
        "use_color": False,
        "color_field": field_read.plane('z').x,
        #"colorbar": True,
        #"colorbar_label": "x-component",
    },
    multiplier=1e-6,
    # filename='mplplot.pdf
                       
                       )
```

The scalar plot seems fine but the vector plot is strongly overlapped and haphazard. 
Thank you!

**Comment by swapneelap** [comment]
Hello @Mishrakishan, will you be able to share with us the plots that you obtained? Thank you!

**Comment by Mishrakishan** [comment]
Thank you for your response. @swapneelap 
Certainly, fo this particular plot the codes are:
%matplotlib inline
field_read = df.Field.fromfile('/Users/kishi/Desktop/DW_DiscreteR100nm_loop6x.out/m000055.ovf')

import matplotlib.pyplot as plt
from matplotlib import style
style.use('seaborn-white')
fig, ax = plt.subplots(figsize=(9, 7), dpi=100)  # Increased dpi value for better quality
field_read.z.plane('z').mpl(ax=ax,
    scalar_kw={"cmap": "bwr", "interpolation": "spline16", "colorbar": False,"colorbar_label": "Magnetization ($\mathbf{M_z}$)" },
    vector_kw={
        "color": "black",
        "use_color": False,
        "color_field": field_read.plane('z').x,
    },
    multiplier=1e-6,
)

**I have used field_read.z.plane('z')**. because **field_read.plane('z')** only giving a black screen. 

Athough with some cell discretisation, I'm able to get the arrows but then layout of arrow is completely heywire. 
![Screenshot 2023-07-31 at 3 25 24 PM](https://github.com/ubermag/help/assets/68537575/f1f1622c-9024-4181-b74b-bf9f0b0462a0)

**Comment by Mishrakishan** [comment]
Thank you for the clarification. I have been doing this but this way it takes time to calibrate for a fine value of grid points n that will provide the corresponding plot with both the scalar and vector adjusted well.
