### ISSUE TITLE
Saving and loading the results of Ubermag simulations 

### ISSUE THREAD

**Issue by jcl25** [ubermag/help#257]
Sorry to be useless - how do I save and load the results of Ubermag simulations?

As I understand it, if I run the code

```
system = mm.System(name="my_simulation")
system.energy = mm.Zeeman(H=(0, 0, 1e6))
system.m = df.Field(mesh, dim=3, value=(0, 0, 1), norm=1e6)

md = mc.MinDriver()
md.drive(system, dirname="./my_project")
```

Ubermag saves the results of the energy minimisation in `my_project/my_simulation/drive-0/` and if I run the code again, the answer is stored in drive-1/ etc.

But ... how do I load the results of a previous simulation?

https://ubermag.github.io/documentation/notebooks/oommfc/dirname.html indicates that I should do this using

```
import os
dirname = os.path.join("my_project", "my_simulation", "drive-0")
os.path.isdir(dirname)
```

but that seems just to set `dirname` to where the results are stored rather than loading everything into `system` which is what I thought would happen.

**Comment by jcl25** [comment]
Thanks - how do I then plot the data?

```
system.m.plane("y").mpl(figsize=(12, 3))
``` 
returns
```
NameError: name 'system' is not defined.
```

**Comment by samjrholt** [comment]
You should be able to do:
```
drive[-1].plane("y").mpl(figsize=(12, 3))
```

**Comment by jcl25** [comment]
That gives the error `Object has no attribute m`.

**Comment by samjrholt** [comment]
Please could you send the line of code you ran?

**Comment by jcl25** [comment]
Sorry - I did not read your previous comment properly. I wrote 
`drive[-1].m.plane("y").mpl(figsize=(12, 3))`
not
`drive[-1].plane("y").mpl(figsize=(12, 3))`

It now works.

Why do you have to type drive[-1]? (I would have thought an array would start at 0 ...)

**Comment by samjrholt** [comment]
You are correct that the array does start at zero! If you have a negative number it counts from the end of the array i.e. -1 would be the last element of the array. Hence, to get the last field in the drive we can either use `drive[-1]` or `drive[i]` where `i` is the highest index.

**Comment by jcl25** [comment]
OK - That's all working. Thanks very much.

**Comment by jcl25** [comment]
Sorry to reopen this.

How do I recreate the mesh that accompanied the results of the simulation?

I can see from typing `drive[-1]` what `p1` and `p2` were and how many pixels were used in each direction (`n`). I was then expecting it to set the variables `p1`, `p2` and `cell` so that I could recreate the mesh using
```
region = df.Region(p1 , p2)
mesh = df.Mesh(region = region, cell = cell)
```
but that is not what happens.

**Comment by samjrholt** [comment]
The magnetisation field is stored inside the drive with all of the mesh information. To access the mesh of a field you should be able to do

```
field.mesh
```

Indexing a drive gives a field hence you should be able to do something like

```
drive[-1].mesh
```

If you wanted to separate and edit the mesh you can store it as a new variable as well

```
mesh = drive[-1].mesh
```

**Comment by jcl25** [comment]
Thanks. That works. 

Nearly there.

How do I recover the energy equation that was used, the saturation magnetisation, the DMI constant, the anisotropy constants, the exchange constant and the applied field? `drive.table.data` seems to come close to this but the numbers are different to what I originally entered (they are presumably energies per pixel).

**Comment by samjrholt** [comment]
There isn't currently a way to load the energy equation that was used to create the system. If you do not have this stored in a notebook you can examine the script used to run the calculations by running

```
print(drive.calculator_script)
```

This will give you the full script that is used to run the calculator. In here you will be able to find all of the variables such as the DMI constant, the anisotropy constants, the exchange constant and the applied field.

For an OOMMF script this will look something like

```
# UniformExchange
Specify Oxs_UniformExchange:exchange {
  A 1.5e-11
}
```

The saturation magnetisation is associated with the magnetisation field and hence the `field` class. You should be able to recover the saturation magnetisation for every cell by doing

```
field.norm
```

or in your case

```
drive[-1].norm
```

This will give the spatially resolved saturation magnetisation. You can do all the normal field operation on this e.g. examine the array directly with

```
drive[-1].norm.array
```

p.s. all values are in SI units of A/m

**Comment by jcl25** [comment]
Great - Thanks for all your help.
