### ISSUE TITLE
How to consider the next-nearest-neighbor exchange constant in OOMMF?

### ISSUE THREAD

**Issue by xugznjust** [ubermag/help#26]
Hello joommf team, 
Is it possible to consider the next-nearest-neighbor exchange constant for a uniform material in OOMMF? At present, it can only consider one uniform exchange constant in the module of "Oxs UniformExchange".

Thanks, Xu

**Comment by marijanbeg** [comment]
Hi, please refer to new documentation for this issue: https://github.com/ubermag/oommfc. There is a tutorial on exchange energy.
