### ISSUE TITLE
Unit Conversions in Ubermag website

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#263]
Hi:
In the unit conversions part of  Ubermag, is there a small mistake here?

from astropy import constants as const
induction_field = [(u.T, u.A / u.m, lambda x: x / const.mu0, lambda x: const.mu0 / x)]

I think it should be translated as follows，
induction_field = [(u.T, u.A / u.m, lambda x: x / const.mu0, lambda x: const.mu0 * x)]
namely, the operator in last item should be changed to a *

**Comment by samjrholt** [comment]
@ZhiyuZhang001 thank you for spotting this. We will update the website shortly.
