### ISSUE TITLE
Decoding issue when transforming OVF to Field

### ISSUE THREAD

**Issue by ZhiyuZhang001** [ubermag/help#266]
Dear Ubermag team,

I would like to use ubermag to post-process .ovf files (bin8) I have obtained, and transform them into Fields by using 'df.Field.from_file'. 
However, I encountered an error during decoding. ('utf-8' codec can't decode byte 0xde in position 1: invalid continuation byte.) Additionally, it can be confirmed that this file can be opened and displayed correctly in MuView.  
Is there any way to resolve this issue?

Best regards,
Zhiyu

**Comment by lang-m** [comment]
@ZhiyuZhang001 Could you share this (or a similar, potentially smaller) file with us?

**Comment by ZhiyuZhang001** [comment]
Thank you for your response. This file has a data type of bin8. If needed, I can also provide data in bin4 or text formats.
[Ta_Jsz360.zip](https://github.com/ubermag/help/files/13457281/Ta_Jsz360.zip)

**Comment by lang-m** [comment]
@ZhiyuZhang001 The problem is a difference in capitalisation in the ovf header (compared to how OOMMF writes ovf files). We will fix this in ubermag to make it more flexible.

As a work-around in the mean time (if needed), you could modify the line:
```
# Begin: data binary 8
```
and replace it with:
```
# Begin: Data Binary 8
```

**Comment by lang-m** [comment]
@ZhiyuZhang001 Is it okay if I add your ovf file as additional test file in `discretisedfield`?

**Comment by ZhiyuZhang001** [comment]
Yes, please feel free to include my ovf file as an additional test file for discretisedfield.

**Comment by lang-m** [comment]
Out of interest: what software did you use to create that OVF file?

**Comment by lang-m** [comment]
The problem is fixed in `ubermag 2023.11` (or `discretisedfield 0.90.1`).

**Comment by ZhiyuZhang001** [comment]
> Out of interest: what software did you use to create that OVF file?

I use Boris, which is also a micromagnetic simulation software.


> The problem is fixed in `ubermag 2023.11` (or `discretisedfield 0.90.1`).

Thank you very much for your help.
