### ISSUE TITLE
Issue with Ubermag and oommf

### ISSUE THREAD

**Issue by MiroCaf** [ubermag/help#271]
Hello, I am working on a Mac. I have followed the advanced installation with pip but there seem to be some issues when importing Ubermag and OOMMF. Spyder returns an error 

/runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop')
Traceback (most recent call last):

File "/Users/clodomirocafolla/Desktop/untitled0.py", line 10, in 
import ubermag

ModuleNotFoundError: No module named 'ubermag'

runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop')
Traceback (most recent call last):

File "/Users/clodomirocafolla/Desktop/untitled0.py", line 11, in 
import oommfc

ModuleNotFoundError: No module named 'oommfc'

**Comment by MiroCaf** [comment]
I had compiled OOMMF and checked it. It seemed fine

/--- Testing Xp_DoubleDouble build ---
darwin/ddtest basetest
All 94 tests passed.
--- Xp_DoubleDouble build looks OK. ---

<84354> pimake 2.0a3 info:
Target '' up to date.
Built Sun Jan 07 12:06:14 CET 2024
Current time: Sun Jan 07 12:06:14 CET 2024
(base) 192:oommf clodomirocafolla$ export OOMMFTCL="/Users/clodomirocafolla/oommf/oommf/oommf.tcl"
(base) 192:oommf clodomirocafolla$ echo $OOMMFTCL
/Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ ls -l $OOMMFTCL
-rwxr-xr-x 1 clodomirocafolla staff 11434 22 May 2022 /Users/clodomirocafolla/oommf/oommf/oommf.tcl
(base) 192:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status"
Running OOMMF (TclOOMMFRunner)[2024/01/07 12:07]... (2.8 s)
OOMMF found and running.
(base) 192:oommf clodomirocafolla$

**Comment by MiroCaf** [comment]
However, there seems to be issues with Ubermag. I run python -c "import ubermag; ubermag.test()" and got
```console
===== 98 failed, 3815 passed, 2 skipped, 125 warnings in 421.51s (0:07:01) =====
Account lookup failure: clodomirocafolla
Account lookup failure: clodomirocafolla
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 27, in _global_cleanup
instance._terminate()
File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 52, in _terminate
self._kill()
File "/Users/clodomirocafolla/miniconda3/lib/python3.8/site-packages/oommfc/oommf/oommf.py", line 231, in _kill
sp.run(command, env=self.env)
AttributeError: 'ExeOOMMFRunner' object has no attribute 'env'
```

**Comment by fangohr** [comment]
> Hello, I am working on a Mac. I have followed the advanced installation with pip but there seem to be some issues when importing Ubermag and OOMMF. Spyder returns an error
> 
> /runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop') Traceback (most recent call last):
> 
> File "/Users/clodomirocafolla/Desktop/untitled0.py", line 10, in import ubermag
> 
> ModuleNotFoundError: No module named 'ubermag'
> 
> runfile('/Users/clodomirocafolla/Desktop/untitled0.py', wdir='/Users/clodomirocafolla/Desktop') Traceback (most recent call last):
> 
> File "/Users/clodomirocafolla/Desktop/untitled0.py", line 11, in import oommfc
> 
> ModuleNotFoundError: No module named 'oommfc'

This means that from the Python that spyder executes, the modules `ubermag` and `oommfc` are not installed.

This suggests that within Spyder you are using a different python version than if you are at the command line.

As a quick work around, you should be able to run your program (`untitled0.py` in `~/Desktop`) from the shell: `cd ~/Desktop; python untitled.py`.

Perhaps you can choose the right python from inside spyder. Or install spyder into the same python for which you have installed Ubermag (something like `pip install spyder`).

**Comment by fangohr** [comment]
> I had compiled OOMMF and checked it. It seemed fine
> 
> /--- Testing Xp_DoubleDouble build --- darwin/ddtest basetest All 94 tests passed. --- Xp_DoubleDouble build looks OK. ---
> 
> <84354> pimake 2.0a3 info: Target '' up to date. Built Sun Jan 07 12:06:14 CET 2024 Current time: Sun Jan 07 12:06:14 CET 2024 (base) 192:oommf clodomirocafolla$ export OOMMFTCL="/Users/clodomirocafolla/oommf/oommf/oommf.tcl" (base) 192:oommf clodomirocafolla$ echo $OOMMFTCL /Users/clodomirocafolla/oommf/oommf/oommf.tcl (base) 192:oommf clodomirocafolla$ ls -l $OOMMFTCL -rwxr-xr-x 1 clodomirocafolla staff 11434 22 May 2022 /Users/clodomirocafolla/oommf/oommf/oommf.tcl (base) 192:oommf clodomirocafolla$ python3 -c "import oommfc; oommfc.runner.runner.status" Running OOMMF (TclOOMMFRunner)[2024/01/07 12:07]... (2.8 s) OOMMF found and running. (base) 192:oommf clodomirocafolla$

This looks good. So at this point, you have installed ubermag successfully, you have oommf, and ubermag knows how to find oommf.

Try to run a `which python3` in this shell, to see which python interpreter you are using here.

**Comment by MiroCaf** [comment]
(base) 192:oommf clodomirocafolla$ which python3
/Users/clodomirocafolla/miniconda3/bin/python3

**Comment by MiroCaf** [comment]
I tried (base) 192:Desktop clodomirocafolla$ cd ~/Desktop; python uber_1.py
but nothing happens and Spyder is not launched :(

**Comment by lang-m** [comment]
The failure
```
AttributeError: 'ExeOOMMFRunner' object has no attribute 'env'
```
can be ignored for now; it should not cause any problems.

**Comment by lang-m** [comment]
In your Spyder, could you try to change the Python interpreter to the one where you installed ubermag (presumably `/Users/clodomirocafolla/miniconda3/bin/python3`). You can find this options in the Spyder "Preferences" under "Python interpreter".

**Comment by MiroCaf** [comment]
Hello and thank you so much for your help. I tried to do what you suggested but I do not seem to go anywhere. Possibly, I am doing something wrong- sorry!

Anyway, this is what I did. On Spyder "Preferences" under "Python interpreter", I changed the Python interpreter to the directory you suggested ('''/Users/clodomirocafolla/miniconda3/bin/python3''') but still get the same Error No module named 'ubermag'.

I then changed the interpreter to '''/Users/clodomirocafolla/miniconda3/envs/ubermag/bin'''  and selected Python3. I thought that we wanted to be in the same folder where Ubermag was. Still the same error. 

Thank you very much once again for your help

**Comment by fangohr** [comment]
It is difficult to debug as many things can go wrong. Regarding [this](https://github.com/ubermag/help/issues/271#issuecomment-1883533353) attempt, it is possible that the Python kernel with which you execute your python program has not been update to use the ubermag/bin environment. 

However, you also seem to have a conda environment for Ubermag which I didn't know about at first (judging by the existence of `/Users/clodomirocafolla/miniconda3/envs/ubermag/bin`), and if Ubermag is installed in that, then the output for `which python3` may not be accurate (perhaps you ran the command in the wrong python/conda environment?). 

As we don't see all the steps you have taken to install miniconda, and then ubermag (and at some point in some way spyder), it is really hard to say what is going on:
You could take a fresh user account, install everything from scratch there, and show the precise commands in the order you use them (and ideally output from each of them) together. Perhaps that will show what is going on.

**Comment by fangohr** [comment]
Note further that you do not need Spyder to run or write Ubermag programs: Spyder is just a Python Editor and environment, and it is not needed for Ubermag. Some basic notes on Python installation and components are in the beginning of [this post](https://fangohr.github.io/blog/installation-of-python-spyder-numpy-sympy-scipy-pytest-matplotlib-via-anaconda.html#what-is-what-python-python-packages-spyder-anaconda).

While I like Spyder, it also introduces a little bit of extra complexity: have you got somebody nearby who knows Spyder and can help you to pick the right kernel, perhaps?

If you have the chance to learn a little bit about Python and installation of packages with pip, that might also be useful - perhaps a colleague has the right skills? One introduction is [available here](https://fangohr.github.io/introduction-to-python-for-computational-science-and-engineering/18-environments.html).

**Comment by MiroCaf** [comment]
Thank you very much once again for all your help. I will see whether any colleagues of mine can help pick the right kernel, and will learn more about Python and installation with pip. 

In the worst scenario, I will follow your previous suggestion, take a fresh user account and install everything from scratch.

Will update you! Thanks again :)

**Comment by MiroCaf** [comment]
Just to let you know that re-installing everything from scratch did the trick. Thanks a lot for all your help
