### ISSUE TITLE
Minor update to documentation

### ISSUE THREAD

**Issue by brevisfg** [ubermag/help#277]
In the section for "ovf2vtk tool" the instruction for using wildcard needs to be updated because "infile" has to be changed to "input".

<img width="733" alt="Captura de pantalla 2024-03-19 a la(s) 2 29 01 p  m" src="https://github.com/ubermag/help/assets/163329202/2aff4c39-1b20-4bbe-a661-4286381906eb">

**Comment by kzqureshi** [comment]
Done
