### ISSUE TITLE
jupyter notebook note found

### ISSUE THREAD

**Issue by Rahul26Singh** [ubermag/help#278]

**Comment by lang-m** [comment]
Hi @Rahul26Singh ,
the current version of Ubermag does no longer install jupyter notebook. Instead, you can use `jupyter lab`, which provides a more flexible interface for working with notebooks.

Note also that the youtube recordings are for an older version of Ubermag and some of the syntax has changed in the mean time. So whenever something shown in the videos does not work please consult the documentation in https://ubermag.github.io.

**Comment by Rahul26Singh** [comment]
Thank you so much for reaching out. I have installed it and am
already starting to learn it as well. There is now no issue with it. I have
a low-configuration PC (i3 processor, Radeon Graphics, 8GB RAM, 256GB SSD,
1TB HDD) will it work properly?


Rahul Singh
Ph.D. Research Scholar
School of Physical & Material Sciences
Central University of Himachal Pradesh.
Contact +91-9882858281
