### ISSUE TITLE
hysterisis simulation of ferromagnetic material

### ISSUE THREAD

**Issue by jmiasif** [ubermag/help#280]
Dear sir 
i want to reproduce experimental hysterisis curve by ubermag jupyter notebook, and calculate anisotropy energy (k) of diffrent sample. when i use this ubermag example [](https://ubermag.github.io/examples/notebooks/hysteresis.html).
1- In this code input parameter is Ms, K, DMI, A. i had calculate Ms from experimantal study so i use it here as a input but how can i fix the value of K and DMI to get same Hc (coericive field) and same curve?
2- Please help me to get value of k for diffrent thin film?
3- Can i calculate Ms of thin film using ubermag? if yes then please help me.
4- how can i calculate stress and strain in this thin film?
5- can i calculate the cure temperature of ferromagnetic thin film using ubermag? is yes please help me.
````
import oommfc as mc
import discretisedfield as df
import micromagneticmodel as mm

region = df.Region(p1=(-50e-9, -50e-9, -50e-9), p2=(50e-9, 50e-9, 50e-9))
mesh = df.Mesh(region=region, cell=(5e-9, 5e-9, 5e-9))

system = mm.System(name='hysteresis')
system.energy = mm.Exchange(A=1e-12) + mm.UniaxialAnisotropy(K=4e5, u=(0, 0, 1)) + mm.DMI(D=1e-3, crystalclass='T')# + mm.Demag()

system.m = df.Field(mesh, nvdim=3, value=(0, 0, -1), norm=Ms, valid="norm")
Hmin = (0, 0, -1/mm.consts.mu0)
Hmax = (0, 0, 1/mm.consts.mu0)
n = 21
hd = mc.HysteresisDriver()
hd.drive(system, Hmin=Hmin, Hmax=Hmax, n=n)
system.table.units['B_hysteresis']
system.table.mpl(x='Bz_hysteresis', y=['mz'], marker='o', linewidth=2, linestyle='dashed')
````
i am research student and want to add this simulation result and citations to validate of our experimental result. 

Thanks in advance for any kind of help.

@marijanbeg @fangohr @JLeliaert @swapneelap @samjrholt

**Comment by jmiasif** [comment]
Hi ubermag team
can we simulate temparature dependent hysteresis cure Or to find curei temparature fo any ferromagnetic material.

**Comment by fangohr** [comment]
You are planning an interesting project. Most of the things you are asking for needs some understanding of physics, material science and magnetism (and is thus not a specific Ubermag question). 

Question 1: Choosing material parameters to match experimental results is difficult and the aim of many projects, perhaps your advisor can give you some ideas what parameters may be good starting points or what effects they may have. Then you need to experiment.

Regarding your other questions 2 and 3, the anwser is that Ubermag cannot do this; these are generally parameters that micromagnetic simulations need as input.  (Assuming `k` is meant to be `K`.)

Not clear what you mean with question 4 but I don't think the micromagnetic simulators can help you with that. 

The answer to 5 is no. (Monte Carlo or spin dynamics simulations are better suited to estimate the Curie temperature.)

**Comment by jmiasif** [comment]
Thank you so much Sir for giving me your precious time.
