### ISSUE TITLE
Field sweep FMR

### ISSUE THREAD

**Issue by jmiasif** [ubermag/help#282]
Dear ubermag Team
Respected sir @fangohr @marijanbeg @samjrholt @swapneelap
I have gone throgh all the littrature survey i found that FMR is only done by frequency sweep technique by ubermag but sir i want to fmr in field sweep technique in which o/p is absorption vs field which is exactly match with experiment.

below code is frequency sweep method to calculate fmr so what should i change in it for  shift at field sweep 

````
import oommfc as oc
import discretisedfield as df
import micromagneticmodel as mm
import numpy as np

lx = ly = 4000000e-9  # x and y dimensions of the sample(m)
lz = 30e-9  # sample thickness (m)

region = df.Region(p1=(0, 0, 0), p2=(lx, ly, lz))
mesh = df.Mesh(region=region, n=(10, 10, 10))

Ms = 1610.30e3  # saturation magnetisation (A/m)
A = 1.3e-11  # exchange energy constant (J/m)
H = 154.901e3 * np.array([0, 1, 0])
alpha = 0.02100  # Gilbert damping
gamma0 = 2.211e5
system = mm.System(name='stdprobfmr')

system.energy = mm.Demag() + mm.Zeeman(H=H) + mm.Exchange(A=A)
system.dynamics = mm.Precession(gamma0=gamma0) + mm.Damping(alpha=alpha)
system.m = df.Field(mesh, nvdim=3, value=(0, 1, 0), norm=Ms)
md = oc.MinDriver()
md.drive(system)
T = 20e-9
n = 4000

td = oc.TimeDriver()
td.drive(system, t=T, n=n)
import matplotlib.pyplot as plt

t = system.table.data['t'].values
my = system.table.data['mx'].values

# Plot <my> time evolution.
plt.figure(figsize=(30, 10))
plt.plot(t, my)
plt.xlabel('t (ns)')
plt.ylabel('my average')
plt.grid()
import scipy.fft
import pandas as pd

psd = np.log10(np.abs(scipy.fft.fft(my))**2)
f_axis = scipy.fft.fftfreq(4000, d=20e-9/4000)

plt.plot(f_axis/1e9, psd)
plt.xlim([-2, 45])
plt.xlabel('f (GHz)')
plt.ylabel('Psa (a.u.)')
plt.grid()
```` 
thanks in advance for any kind of help.

**Comment by fangohr** [comment]
I do not understand the question.

**Comment by jmiasif** [comment]
Respected sir @fangohr 
Above code is given at ubermag page[https://ubermag.github.io/examples/notebooks/10-tutorial-standard-problem-fmr.html](url) which is frequency sweep due absorption on y axis and frequency on x axis with fixed applied field. But in field sweep fmr absorption is on y axis and range of aplied field on x axis like (50 Oe to 7000 Oe) with fixed frequency. 
so, i want fmr in field sweep in support of this field and frequency sweep fmr technique litrature are attached. i know it is time consuming for you in this busy time but please have a look.
[Field sweep and freq. sweep.pdf](https://github.com/ubermag/help/files/15217537/Field.sweep.and.freq.sweep.pdf)
Thanks
