### ISSUE TITLE
Artificial skyrmion

### ISSUE THREAD

**Issue by xiaoxin7721** [ubermag/help#289]
First, I assume that the magnetization directions of the double-layer thin film material are randomly distributed. Apply a magnetic field of 400 mT in the +z direction (perpendicular to the film plane and pointing upwards) to cause all the magnetizations of the double-layer film to deflect towards the +z direction. After the magnetic field disappears, let the hard magnetic layer CoCrPt and the soft magnetic layer NiFe spontaneously form a vortex structure. How can I use Ubermag to achieve this process of deflecting the magnetizations and then removing the magnetic field?
![image](https://github.com/user-attachments/assets/aa30b450-3325-4f14-a85f-b7572bf2dd50)
![image](https://github.com/user-attachments/assets/97b595cc-f571-458b-a888-f42f7eca6a2c)
I have completed part of the code, but I don't know how to proceed next.

**Comment by lang-m** [comment]
Please refer to this notebook in our documentation to learn how to add and remove energy terms such as the Zeeman field: https://ubermag.github.io/demo.html

**Comment by xiaoxin7721** [comment]
def Ms_fun(pos):
    x, y, z = pos
    if ((x - 80)**2 + (y - 80)**2)**0.5 < 60e-9:
        return 8.6e5
    else:
        return 0

Ms = {'Nife': Ms_fun, 'cocrpt': 3.98e5}

def m_init(pos):
    x, y, z = pos
    if 0 < x < 160e-9 and 0 < y < 160e-9:
        return [2 * random.random() - 1 for _ in range(3)]
    else:
        return [0, 0, 1]

m = {'Nife': m_init,'cocrpt':m_init }

system.m = df.Field(mesh, nvdim=3, value=m, norm=Ms)
system.m.sel('z').mpl()

Thank you for your help. However, I have encountered a new problem. I want to define the Ms for a bilayer material. The Ms for the CoCrPt layer is correct, but for the NiFe layer, the Ms is not correct. Is there something wrong with my code, and how can I fix it?
