### ISSUE TITLE
It is taking longer time to execute a simulation

### ISSUE THREAD

**Issue by Nikki00-sys** [ubermag/help#290]
I am taking a longer time to execute a simulation ,whereas same simulation is taking only few minutes in OOMMF.Please help me to find out the problem and get rid of it.I am hereby attatching the simulation code of that,
[ubermag query doc.pdf](https://github.com/user-attachments/files/16371187/ubermag.query.doc.pdf)

**Comment by lang-m** [comment]
Question has been answered on Zulip: https://ubermag.zulipchat.com/#narrow/stream/337652-using-ubermag/topic/Hi.2CI.20need.20to.20solve.20the.20issue.20of.20time.20taking.20for.20simulation/near/453862275

Short summary: use hysteresis driver instead of a Python for-loop calling min driver.
