### ISSUE TITLE
Need guidance to run OOMMF

### ISSUE THREAD

**Issue by FracKD** [ubermag/help#292]
I am trying to run OOMMf using docker. But I am facing an issue- 

![Problem1](https://github.com/user-attachments/assets/d612af3b-a082-47f0-b025-e5e7b0d0dadc)
![Problem2](https://github.com/user-attachments/assets/f5d8a3c9-659f-4bf9-a935-fc1860b45ebc)

**Comment by FracKD** [comment]
FAILED tests/test_micromagnetictests.py::TestCompute::test_energy - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCompute::test_energy_density - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCompute::test_effective_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCompute::test_slonczewski - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCompute::test_zhang_li - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_scalar_vector_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_vector_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_field_field_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestCubicAnisotropy::test_dict_vector_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDamping::test_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDamping::test_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDamping::test_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDemag::test_demag - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDemag::test_demag_asymptotic_radius - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDemag::test_demag_1_pbc - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_dirname - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDMI::test_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDMI::test_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDMI::test_crystalclass - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDMI::test_crystalclass_init - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDynamics::test_scalar_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDynamics::test_scalar_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestDynamics::test_field_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_zeeman - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_uniaxialanisotropy - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_cubicanisotropy - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_dmi_zeeman - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_exchange_dmi_zeeman_uniaxialanisotropy_demag - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestEnergy::test_zeeman_zeeman - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestExchange::test_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestExchange::test_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestExchange::test_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestFixedSubregions::test_fixed_subregions - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestHysteresisDriver::test_noevolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_info_file - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMesh::test_single_nopbc - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMesh::test_multi_nopbc - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMesh::test_single_pbc - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMesh::test_multi_pbc - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_noevolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_evolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_noevolver_driver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_evolver_driver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestMinDriver::test_output_files - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_multiple_drives - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_format - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_outputstep - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestPrecession::test_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestPrecession::test_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestPrecession::test_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestRKKY::test_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_skyrmion - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_single_values - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_single_values_finite_temperature - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_dict_values - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestSlonczewski::test_field_values - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_stdprob3 - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_stdprob4 - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::test_stdprob5 - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestThreads::test_threads - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noevolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_rungekutta_evolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_euler_evolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_theta_evolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_therm_heun_evolver_nodriver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noevolver_driver - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_noprecession - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_nodamping - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestTimeDriver::test_output_files - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_scalar_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_scalar_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_dict_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_field_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestUniaxialAnisotropy::test_higher_order_scalar_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_time_vector - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_time_dict - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZeeman::test_time_field - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_scalar_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_time_scalar_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_dict_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_micromagnetictests.py::TestZhangLi::test_field_scalar - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_exe_oommf_runner - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED tests/test_oommf.py::test_get_oommf_runner - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_get_cached_runner - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_set_exe_oommf_runner - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED tests/test_oommf.py::test_runner_repr - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_status - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_overhead - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_wrong_command - OSError: Cannot find OOMMF.
FAILED tests/test_oommf.py::test_choose_runner - TypeError: expected str, bytes or os.PathLike object, not NoneType
FAILED tests/test_oommf.py::test_silent - OSError: Cannot find OOMMF.
FAILED tests/test_mfm.py::test_mfm_phase_tip_m - OSError: Cannot find OOMMF.
FAILED tests/test_mfm.py::test_mfm_phase_tip_q - OSError: Cannot find OOMMF.
FAILED tests/test_mfm.py::test_mfm_phase_no_tip - OSError: Cannot find OOMMF.
FAILED tests/test_mfm.py::test_mfm_phase_quality - OSError: Cannot find OOMMF.
FAILED tests/test_mfm.py::test_mfm_phase_fwhm - OSError: Cannot find OOMMF.
FAILED tests/test_quick_plots.py::test_quick_plots_mfm_phase_shift - OSError: Cannot find OOMMF.
FAILED tests/test_util.py::test_util_calculate_demag - OSError: Cannot find OOMMF.
FAILED tests/test_info.py::test_debug_info - AssertionError: assert 'OOMMFRunner' in 'Platform: win32\nPython: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]\n...
================================================ 104 failed, 3806 passed, 5 skipped, 302 warnings in 565.50s (0:09:25) ================================================

this is the summery of the Test Result.. Please Help

**Comment by lang-m** [comment]
@FracKD We need more information to be able to help you.
From your output it seems you are not using the latest version of Ubermag. Please check and re-try with the latest version if you currently have an older one.

Please paste the output of the following commands (executed on the command line):
```
docker run ubermag/oommf /bin/bash -c "tclsh /usr/local/oommf/oommf/oommf.tcl +version"
docker run ubermag/oommf /bin/bash -c "tclsh /usr/local/oommf/oommf/oommf.tcl +platform"
```
and
```
docker run oommf/oommf /bin/bash -c "tclsh /usr/local/oommf/oommf/oommf.tcl +version"
docker run oommf/oommf /bin/bash -c "tclsh /usr/local/oommf/oommf/oommf.tcl +platform"
```

**Comment by FracKD** [comment]
Thank you for the suggestion! The problem is solved.
