### ISSUE TITLE
Multiple Zeeman energy terms in MuMax3

### ISSUE THREAD

**Issue by nirelbern** [ubermag/help#294]
Hello, Ubermag community,

First, thank you for the great tool that are working on that allowed me to increase my research capabilities greatly.

I am trying to apply DC Zeeman and an AC Zeeman field both through the Zeeman class.
While [compatibility document ](https://ubermag.github.io/documentation/compatibility.html) says it is possible,
I am getting the following error:
`RuntimeError: Mumax3 does not allow more than one energy term of the same class.`

What am I doing wrong?

Thanks again,
Nirel

Attached is my code:

`import micromagneticmodel as mm
import discretisedfield as df
import mumax3c as oc

md = oc.MinDriver()
td = oc.TimeDriver()

# System
system_name = 'Test'

# Mesh
lx = ly = 100e-9 # x and y dimensions of the sample (m)
lz = 10e-9  # sample thickness (m)
dx = dy = dz = 10e-9  # discretisation in x, y, and z directions (m)

# Energies 
Ms = 500e3  # Saturation magnetisation (A/m)
A = 1e-11  # Exchange energy constant (J/m)
Ku = 1e5  # UMA constant (J/m^3)

# Initialize system
system = mm.System(name='Test')
region = df.Region(p1=(0, 0, 0), p2=(100, 100, 10))
mesh = df.Mesh(region=region, cell=(10, 10, 10)) 

# Initialize energies and dynamics
system.m = df.Field(mesh, dim=3, value=m_init_random, norm=Ms)
system.energy = mm.Exchange(A=A) + mm.Zeeman(H=(100, 0, 0), name='Zeeman') + mm.Zeeman(H=(0, 10, 0), wave='sin', f=10e9, t0=0, name='Sine')
system.dynamics = mm.Precession(gamma0=mm.consts.gamma0) + mm.Damping(alpha=0.1)
system.energy

# Minimize energy
rd = oc.RelaxDriver()
rd.drive(system, verbose=2)
system.m.plane('z').mpl(figsize=(10,12))`

**Comment by samjrholt** [comment]
Hi @nirelbern, 
It looks like you are using an older version of Ubermag. Please could you update to the newest version and try again? I have managed to run you code with only minor syntax changes (i.e. `plane`->`sel` and `dim`->`nvdim`)

**Comment by nirelbern** [comment]
It worked. 
Thank you @samjrholt !
