### ISSUE TITLE
Clarification on the Meaning of Nested Matrix Values in `count_bps` Function Output

### ISSUE THREAD

**Issue by acse-zl6322** [ubermag/help#295]
I have been using the count_bps function in your project and noticed that it returns a nested matrix within the output, as shown below:
![屏幕截图 2024-08-19 082209](https://github.com/user-attachments/assets/b5797a86-b890-4cf1-b2a6-c2956ea64e64)

Could you please provide some clarification on what the values within the nested matrices (e.g., [-0.0, 8] in bp_pattern_z) represent?  Specifically, I am interested in understanding the significance of both the first and second elements in these arrays.

I have also checked the Ubermag documentation but couldn't find detailed explanations regarding these specific outputs.

Thank you for your assistance!

**Comment by lang-m** [comment]
Hi @acse-zl6322, each element in the outer list consists of [current topological charge, number of cells without changes].

The topological charge is computed over increasing subvolumes in the given direction. E.g. the output in your cell 12 means:
- starting from the minimal z value, the topological charge is 0 for the subvolumes spanning at most the first 8 cell layers in the z direction
- the topological charge jumps to -1 (=1 HH BP) when the subvolume contains the first 9 layers of cells and does not change for the remaining four layers of cells
- so overall we find 1 BP located 8 cells away from the lower boundary in the z direction.

The information for the other directions is similar. In your case the BP is mostly centred in the x and y directions.

Please also check the supplementary material (https://static-content.springer.com/esm/art%3A10.1038%2Fs41598-023-33998-z/MediaObjects/41598_2023_33998_MOESM1_ESM.pdf) of this publication https://www.nature.com/articles/s41598-023-33998-z#Sec17
