### ISSUE TITLE
Ubermag test failing after installation

### ISSUE THREAD

**Issue by biggestsam** [ubermag/help#297]
[ubermag.txt](https://github.com/user-attachments/files/16715795/ubermag.txt)
Hi Team, I have installed Ubermag by following this online tutorial: https://www.youtube.com/watch?v=s-nUW04qUIY
However, the it outputs 40 errors which has been attached in the test file. Will be grateful if you could help troubleshoot and resolve this issue.
Many thanks in advance for the support.

**Comment by samjrholt** [comment]
Hi @biggestsam. The tutorials are slightly old now so we would recommend starting fresh (in a new environment) and following the instructions on the website https://ubermag.github.io/installation.html . I will close the issue but please feel free to reopen it if you still get errors after following these new instructions.
