### ISSUE TITLE
Help With Hysteresis Simulation

### ISSUE THREAD

**Issue by MadSc1ent1st96** [ubermag/help#299]
I am new to Ubermag and i was messing around with the hysteresis simulation given in the example. I want to see the difference in the area of hysteresis loop of hard and soft magnet. For that, I need absolute value on the y-axis (the one plotted as m(z)) and not the values in the range (-1,1). As we know, there is a difference in the y-axis saturation of hard and soft magnet. When I plot the graph, both hard and soft magnet saturate at -1 and 1, which should not be the case. So, how can i plot such a graph in which comparison between hard and soft magnet can be made?

**Comment by fangohr** [comment]
I don't understand the question. Please be more detailed in your description of the problem. Some suggestions are [available](https://fangohr.github.io/computing/smartquestion.html).
