### ISSUE TITLE
Need help with running ubermag I'm encountering "AttributeError: Object has no attribute sel"

### ISSUE THREAD

**Issue by nehaprince** [ubermag/help#300]
Hello, It's my first time using ubermag I installed it using pip +venv as I already had oommf installed beforehand after installing I've encountered an error with the attribute .sel()  and I'm not sure why it's not working.
![image](https://github.com/user-attachments/assets/7f693c3f-1c98-44c1-bdc4-f7986ce02756)

**Comment by samjrholt** [comment]
Hi @nehaprince  please could you do `df.__version__` so we can see the version number if discretisedfield you are using.

**Comment by nehaprince** [comment]
sorry for not getting back sooner I got '0.61.0' this for ` df.__version__`

**Comment by nehaprince** [comment]
I'll try updating discretisedfield thank you for suggestion

**Comment by nehaprince** [comment]
I tried updating it. it did not update instead it's stll 0.61.0 I think on the website it was 0.91.1

**Comment by nehaprince** [comment]
@samjrholt  Should I try updating pip as well and see if that helps ?

**Comment by nehaprince** [comment]
![image](https://github.com/user-attachments/assets/d4f1f2bf-9bc1-4f66-b629-9b7b68d8e473)

**Comment by nehaprince** [comment]
My problem was that my environment was running on Python 3.13 I downgraded to Python 3.11 So everything installed well and I'm getting zero errors. Thank you
