### ISSUE TITLE
Need help with  running ubermag RuntimeError: Error in OOMMF run.

### ISSUE THREAD

**Issue by nehaprince** [ubermag/help#301]
Previously  I had issues with running .sel() and updating discretisedfield I realized that I was using python 3.13 instead of 3.11 and some of the packages didn't support python 3.13 so I made a new virtual environment  with python 3.11 and most of the example files run except for the ones  that skyrmion simulations.  I also have tried doing simulations changing values of files that works but it still gives me errors. I would appreciate any suggestions to troubleshoot this error. 

  
![Screenshot 2024-10-28 105708](https://github.com/user-attachments/assets/a694f470-8cf3-42e6-b3ab-12f0c33aef8a)

[practice-ubermag.pdf](https://github.com/user-attachments/files/17544753/practice-ubermag.pdf)
this is the one I tried testing 
what I eventually be able to do is run simulations similar to this paper  using ubermag 
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.86.184404

**Comment by nehaprince** [comment]
Hello 
I tried using ubermag  installed by pip + env since I was having errors constantly so I went on to reset my laptop (a full reset all files removed )and installed anaconda and installed ubermag in a conda environment. I ran my demo file but to my dismay it had errors again. 
![image](https://github.com/user-attachments/assets/43f3e684-c701-42e0-824f-d92a0937a58e)

I would highly appreciate any feedback.
I urgently need help 
Please help 
I am extremely grateful for any feedback

@marijanbeg @fangohr

**Comment by lang-m** [comment]
Hi @nehaprince Ubermag for some reason cannot find OOMMF. Did you install Ubermag using `conda` or `pip`? (OOMMF is only available via `conda`.)
The easiest solution for you would be to install docker (https://docs.docker.com/desktop/install/windows-install/). Ubermag should then be able to use it and run OOMMF.

**Comment by nehaprince** [comment]
I used conda. I tried installing the docker it didn't help. Instead I used this set of code.
` oc.oommf.tcl_path = r"C:\Users\trees\anaconda3\pkgs\oommf-2.0b0.post1-h1aae169_0\Library\opt\oommf\oommf.tcl"
oc.runner
oc.runner.envvar
import micromagneticmodel as mm # mm is just a shorter name we want to use later
import discretisedfield as df # df is just a shorter name we want to use later
oc.runner.oommf_exe
oc.runner.docker_exe

oc.runner.runner = oc.oommf.TclOOMMFRunner("C:\\Users\\trees\\anaconda3\\pkgs\\oommf-2.0b0.post1-h1aae169_0\\Library\\opt\\oommf\\oommf.tcl")
print (oc.runner)


print(oc.oommf.tcl_path) `  

It works now for some reason I don't know how.

**Comment by nehaprince** [comment]
It works well right now. Thank you.
