### ISSUE TITLE
Specifying the Heisenberg Exchange Interactions to the Nearest, Neighbor-Nearest, and Next-Neighbor-Nearest Lattices

### ISSUE THREAD

**Issue by myhsia** [ubermag/help#302]
Hi,
Is it possible to specifying the Heisenberg exchange interactions to the **Nearest, Neighbor-Nearest, and Next-Neighbor-Nearest** lattices? Just like the following Hamiltonian described

$$
    H = J_1 \sum_{\langle ij \rangle}\vec m_i\cdot\vec m_j+
           J_2\sum_{\langle\langle ij \rangle\rangle}\vec m_i\cdot\vec m_j+
           J_3\sum_{\langle\langle\langle ij \rangle\rangle\rangle}\vec m_i\cdot\vec m_j+
           \sum_{\langle ij \rangle}\vec D_{ij}\vec m_i\times\vec m_j-
           K\sum_i(m_i^z)^2
$$

Reference: arXiv 2403.05747

**Comment by fangohr** [comment]
I don't think so. The micromagnetic model - used by all calculators in ubermag - is a continuum model that does not know about individual sites in an atomic lattice.  See for example https://en.wikipedia.org/wiki/Micromagnetics .
