### ISSUE TITLE
How to visualize dynamic components of magnetisation

### ISSUE THREAD

**Issue by dovod91** [ubermag/help#303]
Dear Ubermag team,

I am starting to use Ubermag for my research work and I can only thank you for your efforts, the tool is great.
I am running simulations with sinc pulse excitations in order to excite spin waves, which are better visualized in the dynamic (time derivative) components of magnetisation.
I managed to incorporate to the system.table.data table three columns with such data, but I would like to visualize these magnitudes with space resolution, in the plane cuts using matplotlib, as in 
![image](https://github.com/user-attachments/assets/8b15dea1-8f28-4c8c-b7fc-3252bd30b7e8)

I can see this plot shows m, in turn obtained from the 'drive' in the data.info. Is it possible to visualize other magnitudes, such as the differentiated magnetization m with respect to time? 
Many thanks for your help.

P.S. another question, in the data.info table I can see the drive numbers only increase with every simulation, is tehre a way to deelte the 'old drives' so they don't stack up?

**Comment by lang-m** [comment]
Hi @dovod91,

Deleting individual drives via Ubermag is not supported. You can delete whole simulation set using e.g. `oommfc.delete` (https://ubermag.github.io/api/_autosummary/oommfc.delete.html). You can also delete the files manually. Gaps in the numbers (i.e. deleting a few drives) can however lead to problems that Ubermag cannot deal with. So the best option will be to change the system name whenever you start/test something new and delete that data folder once you no longer need it.

For interactive visualisation, I would generally recommend that you use the holoviews backend integrated into `micromagneticdata`. This notebook should get you started: https://ubermag.github.io/documentation/notebooks/micromagneticdata/interactive_plotting.html (Note: some of the plots are not rendered correctly in the browser, so best either download the notebook or run on Binder to explore its functionality, see links on the webpage). The main advantage of using holoviews (with bokeh as backend) is the much better responsiveness compare to matplotlib.

Computing and visualising derived quantities is also supported in micromagneticdata, details are explain in the same notebook: https://ubermag.github.io/documentation/notebooks/micromagneticdata/interactive_plotting.html#Selecting-only-a-part-of-the-drive
In short: you define a function that will be called for each magnetisation snapshot of a `drive` prior to plotting that data. This function can then be registered in a `drive` using `register_callback` (https://ubermag.github.io/api/_autosummary/micromagneticdata.AbstractDrive.html#micromagneticdata.AbstractDrive.register_callback). You can register multiple callbacks (call the function multiple times). Each callback will get the output of the previous callback as single input parameter (the first callback gets the magnetisation as `discretisedfield.Field` object).
Accessing more than one magnetisation step inside such a callback function requires a bit more manual work. There is no easy functionality inside `micromagneticdata` (it should still be possible with the `register_callback` mechanism).

Alternatively, you can convert a whole drive to an xarray (see the last cell of the Drive section https://ubermag.github.io/documentation/notebooks/micromagneticdata/documentation.html#Drive) and then do more complex postprocessing with the xarray object (which provides good integration with the holoviews plotting ecosystem).

If specific additional functionality in micromagneticdata would be useful, please report back. Maybe something can be implemented.

**Comment by dovod91** [comment]
Thank you so much for the prompt and complete response! 
Cheers,
