### ISSUE TITLE
Customized function for zeeman field not working?

### ISSUE THREAD

**Issue by dovod91** [ubermag/help#305]
Dear Ubermag team,

I am using a customized excitation function for the zeeman field, more exactly, I want to implement a gaussian pulse in a spatial region within my sample. The function I have defined is:

`def exponential(t):
    t0=5e-9
    tdelay=1e-9
    return np.exp(-((t-tdelay)/t0)^2)`

And the code right after is:

`td = mc.TimeDriver()

dt=1e-12    # n = t_T / dt
t_T = 3e-9

system.energy += mm.Zeeman(H=H, func=exponential, dt=1e-12)

system.energy`

However, after launching the time driver with the exponential 'func', I get an error I don't grasp:

![image](https://github.com/user-attachments/assets/2431c2a0-a8cd-445f-add7-ed5e0acec40b)

I also tried with the pre-defined sinc source, and oommf exe runs well.  I don't understand what is the issue with my custom function...
Many thanks for your help!

**Comment by fangohr** [comment]
Try `**` instead of `^` in your equation. Does that help?

**Comment by dovod91** [comment]
Yes it did! Thanks a lot!

**Comment by fangohr** [comment]
Thanks. 

Explanation: `^` is a bitwise (XOR) operator, whereas for `a` to the power of `b` that you want to use, the syntax xs `a**b` in Python.

In the error message there was something about "bitwise XOR" - that's a hint pointing to the problem.
