### ISSUE TITLE
Extracting the table data for each subregion of a system

### ISSUE THREAD

**Issue by CID02086310** [ubermag/help#306]
Dear all,
I was hoping if there's a way to extract the table data (Magnetisation and energies) of each subregion defined within a system separately, after driving it using the HysteresisiDriver(). 
In my case, I have 4 different subregions within my system, stacked on top of each other, and I'm trying to plot the Mx component of each subregion against the applied Bx component. However, I'm only able to access the total Mx (which I assume is averaged out over the 4 different layers) from the command below:
system.table.data.head()
I have attached my full code below. I'd appreciate if you could guide me in the right direction as I've spent an unhealthy amount of time trying to get this to work 😃
[STTO_code.zip](https://github.com/user-attachments/files/18165362/STTO_code.zip)

**Comment by lang-m** [comment]
Hi @CID02086310,
average magnetisation for subregions is not directly available in the table. You can compute it manually by using `micromagneticdata` to access the magnetisation of the individual steps (that returns a Field object) and then select the individual subregions and use Field.mean (https://ubermag.github.io/api/_autosummary/discretisedfield.Field.html#discretisedfield.Field.mean) to compute the average magnetisation.
