### ISSUE TITLE
Help: Multilayer_Spinvalve Defining

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#37]
Hello,
How can I define multilayers using JOOMMF?
Reference in OOMMF .mif file
oommf/app/oxs/examples/spinvalve

Thanks,

**Comment by marijanbeg** [comment]
Please refer to new `oommfc` and `discretisedfield` documentation for this functionality.

https://github.com/ubermag/discretisedfield
https://github.com/ubermag/oommfc
