### ISSUE TITLE
Triangular Geometry (Python Coding Help)

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#40]
Hi,

![triangle](https://user-images.githubusercontent.com/43433451/58787737-0f88e180-8608-11e9-81bb-e658f5774052.png)

I tried to create a triangular geometry in Joommf, but it was not uniform. Kindly help me to create a triangular geometry.

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana, what do you mean by non-uniform triangle?

**Comment by Ponsudana** [comment]
Hello @marijanbeg,
The magnetization inside the area of the triangle is not the same. 
![58787737-0f88e180-8608-11e9-81bb-e658f5774052](https://user-images.githubusercontent.com/43433451/59042830-c56a5f00-8898-11e9-8f92-58d1bcb1ce35.png)
When I returned the value of Ms inside the area of the triangle, I got the result as shown in the image.

**Comment by marijanbeg** [comment]
Thank you for this clarification. I will have a look into more details.

**Comment by marijanbeg** [comment]
This problem should be fixed with new `discretisedfield` package. Please refer to the documentation for new interface.  https://github.com/ubermag/discretisedfield
