### ISSUE TITLE
time-dependent or spatial-dependent Radio Frequency Field(RF field)

### ISSUE THREAD

**Issue by chenminacm** [ubermag/help#43]
Could any bro please teach me how to setup a RF-field with time-dependence or spatial dependence in ubermag?

**Comment by catrevil** [comment]
@chenminacm if you aren’t aware, the recent workshop series had some tutorial materials on this. I recommend taking a look at the recordings to see how something like this could be done!

**Comment by marijanbeg** [comment]
You can have a look at the workshop we recently delivered: https://github.com/ubermag/workshop

There is one tutorial which addresses this issue. Soon, I am going to make that tutorial part of the main ubermag documentation.
