### ISSUE TITLE
Run time is high

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#45]
Hi,
I updated the oommfc as directed in issues 44,
https://github.com/ubermag/help/issues/44

While importing oommfc it takes about 10-15 sec
The running time of OOMMF is high compare to the documentation examples
Attached an example stdproblem3,
[stdprob3.pdf](https://github.com/ubermag/help/files/3558962/stdprob3.pdf)

I there anyway to improve my run time?

Thanks,

**Comment by marijanbeg** [comment]
Hi @Ponsudana

**Comment by Ponsudana** [comment]
Hi @marijanbeg 
Thanks for the quick reply.
Edited my comment. It was submitted accidentally without full content of the issue.

> Hi @Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, is that the case every time you import oommfc? What happens if you try to import it again? This can be the case the first time you import oommfc because in the background matplotlib is imported as well and that can take some time until the fonts are cached.

**Comment by Ponsudana** [comment]
Thanks @marijanbeg 
When I imported again, it's fine. Only the first time there was a lag.

The run time of OOMMF is bit slower.
While using the previous version the system.m was displayed much quicker (Immediately after Shift+Enter). 
In[5] and In [6]: takes longer time. (Shown in screen recording)
Is this the exact simulation time or it's slow?

I have started using micromagnetic simulation recently, so just need clarification if it's normal for this system as the cell size is small.

[program run time.zip](https://github.com/ubermag/help/files/3562088/program.run.time.zip)

**Comment by marijanbeg** [comment]
Hi @Ponsudana, great, that was expected until certain imports are cached (mostly matplotlib).

By looking at the script you sent me, I would say that is the normal running time. In the same cell you are both creating the field (on a relatively large mesh and with a nontrivial norm) and plotting all points in the mesh, so the runtime should be the sum of those two.

To speed up the plotting, and also to improve the plot, you can always choose to plot less points, by passing `n` attribute to the `plane` method. For instance, `system.m.plane('z', n=(20, 20)).mpl()`. At the moment you are plotting 100 x 100 cells. You can also have a look at the `k3d` plotting functions in the tutorials, which gives you 3D plotting in the notebook.

I will close this issue now, but (as always) please feel free to reopen it or to raise a new one :) Thank you for using Ubermag.

**Comment by Ponsudana** [comment]
Hi,

Now I can understand the process. Thanks for explaining it. 
Surely will check k3d plotting.


Thanks again. @marijanbeg
