### ISSUE TITLE
Adding magnetoelatic coupling in the system

### ISSUE THREAD

**Issue by Wako205** [ubermag/help#46]
Dear JOOMMF-Team,

Thank you for creating Ubermag.  It is such an excellent tool for magnetic stimulation.

However, I have a really naive question to ask.

I am wondering if it is possible to include additional energy term to the system and solve the dynamic equation directly.

For instance, the always missing coupling:  the magnetoelastic effect.

In fact, for OOMMF, there is an extension for Magnetoelastic coupling build by Yu Yahagi (https://github.com/yuyahagi/oommf-mel)

Thank you in advance. 

Best regards,
MINGRAN

**Comment by marijanbeg** [comment]
Hi @Wako205, thank you for your question and for showing interest in Ubermag. We are going to consider adding this term to the `oommfc` package (based on the extension you sent us).

I will leave this issue open, so you can remind us in about a month from now if you do not hear back from us.

**Comment by marijanbeg** [comment]
Hi @Wako205, can you please provide us an example of a very simple, yet physically meaningful, simulation using the magnetoelastic term? This is going to help us test the implementation and do the documentation.

**Comment by Wako205** [comment]
Dear Mr Beg,

Many thanks for your reply.
I will suggest these papers for magnetoelastic coupling with simulation.
One is written by the developer of that OOMMF extension.[PHYSICAL REVIEW B 90, 140405(R) (2014)]
Another one studied more detail about the surface acoustic wave driving magnetic dynamic[PHYSICAL REVIEW B 86, 134415 (2012)].

Thank you so much again.
Please let me know if there is anything I can do to help.
Best regards,
MINGRAN

**Comment by marijanbeg** [comment]
If your OOMMF installation has magneto elastic coupling, then you can define this energy term as: https://micromagneticmodel.readthedocs.io/en/latest/magnetoelastic.html
