### ISSUE TITLE
Docker was not found.

### ISSUE THREAD

**Issue by zkhodzhaev** [ubermag/help#47]
Hello,

I am new user,

I followed instructions here: 
`https://oommfc.readthedocs.io/en/latest/index.html`

And when running:
`md = oc.MinDriver()
md.drive(system)`

I get this error:
`OSError: Cannot find OOMMF.`

The screenshot:
<img width="1121" alt="Screen Shot 2019-09-01 at 00 53 08" src="https://user-images.githubusercontent.com/21960382/64072386-f9b0aa00-cc52-11e9-91ce-005f94d762eb.png">

Thank you in advance.

**Comment by marijanbeg** [comment]
Hi @Zulfidin, what operating system are you using? Did you install it using conda or pip?

**Comment by Zulfidin** [comment]
> Hi @Zulfidin, what operating system are you using? Did you install it using conda or pip?

macOS Mojave, version: 10.14.6
I installed it using "conda"

**Comment by marijanbeg** [comment]
Hi @Zulfidin, when you go to the Terminal and assuming you have conda, could you type:
```
conda create -n ubermag python=3.6
conda activate ubermag
conda install --channel conda-forge ubermag
```
What happens now?

**Comment by Zulfidin** [comment]
It created without a problem:
<img width="1121" alt="Screen Shot 2019-09-01 at 00 53 08" src="https://user-images.githubusercontent.com/21960382/64353059-b6dc3280-cfc2-11e9-8ed7-8da39336ca5a.png">

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. I will close this issue now. Feel free to reopen it if necessary.

**Comment by Zulfidin** [comment]
I am still getting the same error:

<img width="872" alt="Screen Shot 2019-09-05 at 09 57 20" src="https://user-images.githubusercontent.com/21960382/64353628-ad9f9580-cfc3-11e9-9eb0-e0f92aa468c5.png">

**Comment by Zulfidin** [comment]
Now, I am getting this message, should I follow what it suggests ? :

<img width="1124" alt="Screen Shot 2019-09-05 at 10 17 22" src="https://user-images.githubusercontent.com/21960382/64355268-826a7580-cfc6-11e9-8a9f-b8eba32f6e7f.png">

**Comment by marijanbeg** [comment]
This means that the system object with the same name was already driven. You can:
- give another name to the system object
- pass `overwrite=True` to the drive method
- run `system.delete()` before you run the drive method for the first time

**Comment by Asohamithran** [comment]
Hi I am very new to Linux and ubermag I have the same "DOCKER WAS NOT FOUND ISSUE" 
I use Manjaro as my distro and I have installed ubermag using pip. I have followed the guidelines from the advanced installation. But I get the same error. Can someone guide me in the right direction? Thank you
![ubermag issue](https://user-images.githubusercontent.com/63597151/99496604-a7b08d00-299a-11eb-9e68-fb545974237a.png)

**Comment by danahmedkhan** [comment]
Hello,

I am experiencing the same error: "OSError: Cannot find OOMMF". I have upgraded OOMMFC still no use. I am running the code in Jupyter Notebook and I have Windows OS. Can you please help me with this? Thank you.

**Comment by marijanbeg** [comment]
Hi @danahmedkhan and @Asohamithran, we recommend installing Ubermag using conda. After you install miniconda, create a new environment `conda create --name ubermag python=3.8` and activate it `conda activate ubermag`. After you are inside a clean environment (there should be `(ubermag)` at the beginning of the prompt line), install ubermag `conda install --channel conda-forge ubermag=0.60.0`. This way, you force installation of the newest version. Please let us know if this resolved your issue.

**Comment by lang-m** [comment]
Hi @danahmedkhan, in case reinstalling does not solve your issue please enable logging in debugging mode as explained here: https://ubermag.github.io/documentation/ipynb/ubermag/logging.html and show the debug output of `oommfc.runner.autoselect_runner()`.

**Comment by danahmedkhan** [comment]
Thank you so much. I forced install that
![Screenshot 2022-02-16 102742](https://user-images.githubusercontent.com/78517565/154297671-77168f55-5b6a-4a00-9a5d-b7061355f1e5.jpg)
But still I am getting the same OS Error: Docker Not Found. 
I tried to run the code in Spyder too. 
Thank you.

**Comment by marijanbeg** [comment]
Hi @danahmedkhan, could you please do the logging suggestion outlined earlier by @lang-m?

**Comment by danahmedkhan** [comment]
I rebooted my system and did everything all over again, Seems to be working but now I am getting this error:
AttributeError: module 'oommfc' has no attribute 'HysteresisDriver'

**Comment by marijanbeg** [comment]
It would be useful if you can give us the information as outlined here: https://ubermag.github.io/documentation/ipynb/ubermag/logging.html.

**Comment by marijanbeg** [comment]
@danahmedkhan, I meant the last two comments here. Have you tried them?

**Comment by mhviolet** [comment]
Hello and respect.
I've been browsing messages but have not yet figured out how to add the hysteresisdriver module to oommfc. I have other modules like mindriver, timedriver, compute, etc. and they work well on Jupiter. I am using the 2018 oommf version. I updated pip as well as oommfc. But the only problem is the lack of a hysteresisdriver module. How to download this driver separately and add it to other modules to make it work fine.
Thank you very much.

**Comment by lang-m** [comment]
Hi @mhviolet, what are your exact versions of oommfc (`oommfc.__version__`) and ubermag (`ubermag.__version__`)? You can get these by running:
```python
import oommfc
import ubermag
print(f'{ubermag.__version__=}, {oommfc.__version__=}')
```

**Comment by lang-m** [comment]
@danahmedkhan in case your issue has not been resolved yet, please update to Ubermag version `0.61.0`, released today, and try again.

**Comment by mhviolet** [comment]
dear  Dr.martini am using oommfc version 0.8.24but i have not ubermag.my system operation is windows8.1
Respectfully
    On Tuesday, February 22, 2022, 08:40:33 PM GMT+3:30, Martin Lang ***@***.***> wrote:  
 
 


@danahmedkhan in case your issue has not been resolved yet, please update to Ubermag version 0.61.0, released today, and try again.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lang-m** [comment]
Hi @mhviolet, please update your version of `oommfc` to `0.61.0` to get the HysteresisDriver. You could also consider installing the `ubermag` metapackage (also version `0.61.0`) that brings `oommfc` and all the other ubermag packages (most of which are requried for `oommfc` anyway) as dependencies.

**Comment by mhviolet** [comment]
Dear.Dr Martin Langthank you for your guidance 
How do I upgrade  oommfc to 0.61.0? Is the "pip upgarde oommfc" command on the command line enough?
Also, with the oommfc update, the previous codes do not have problems during execution?

respectfully



   On Wednesday, February 23, 2022, 12:24:06 PM GMT+3:30, Martin Lang ***@***.***> wrote:  
 
 


Hi @mhviolet, please update your version of oommfc to 0.61.0 to get the HysteresisDriver. You could also consider installing the ubermag metapackage (also version 0.61.0) that brings oommfc and all the other ubermag packages (most of which are requried for oommfc anyway) as dependencies.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marijanbeg** [comment]
Hi @mhviolet, you can update Ubermag by running: `conda update ubermag` in the environment where your conda installation is. You can find more information here: https://ubermag.github.io/installation.html#update

**Comment by marijanbeg** [comment]
Hi @danahmedkhan, could you please confirm if your issue has been resolved?

**Comment by lang-m** [comment]
Assuming, this has been resolved. Please re-open if there are still any problems.

**Comment by bolozubaankesari** [comment]
Hi! I am stilling facing the issue of `Docker was not found.` and `OSError: Cannot find OOMMF.`. My ubermag and OOMMF are `0.61.2` and `0.61.1` respectively. I am running a jupyter notebook in a conda environment. Thank you for any and all help!

**Comment by mhviolet** [comment]
Fortunately, the problem has been solved with the guidance of Dr. Marijan Beg. Only the issue of the hysteresis chart has not yet been implemented. With "pip install ubermag" command

**Comment by bolozubaankesari** [comment]
Hi! I'm still facing the same error as mentioned by the others above. I have installed ubermag through pip and have updated it using conda. I would appreciate it if anyone could suggest further changes that I should make to fix the problem.

**Comment by fangohr** [comment]
@bolozubaankesari

You need to install the Docker software on your Mac before OOMMF can be run in the docker container. 

If you have installed it correctly, you should be able to run 
```bash
docker --version
```
in a `Terminal` window. The response should be something like
```
Docker version 20.10.11, build dea9396
```

If you get a response such as 
```
zsh: command not found: docker
```
then Docker is not installed on your system.
