### ISSUE TITLE
Help: Fixing the range of colorbar

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#49]
Hi,

While plotting, the color bar and its values are automatically generated.
How to fix the range of values in color bar?

Example Standard problem 5,

![After stt](https://user-images.githubusercontent.com/43433451/64312175-91e8bf00-cfc4-11e9-85ef-ce212fead2a0.png)
![Initial Vortex](https://user-images.githubusercontent.com/43433451/64312176-91e8bf00-cfc4-11e9-9317-b4ad0cb20732.png)
![Minimisation](https://user-images.githubusercontent.com/43433451/64312177-92815580-cfc4-11e9-9440-8b6c59e48d9f.png)

In these 3 plots, how to get the color bar with same range of values?
Kindly help me.

Thanks,
With regards, 
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, the data range for colorbars are computed automatically each time you plot it. However, anything which can be passed to the matplotlib's colorbar function can also be passed to the field's colorbar method. You can have a look at the tutorial: https://discretisedfield.readthedocs.io/en/latest/ipynb/09-tutorial-matplotlib-visualisation.html, (especially cell 20) as well as the arguments accepted by the matplotlib's colorbar (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.colorbar.html).

Please let me know if this sound too complicated and I can make an example for you as soon as I find some time. I will close this issue for now, but (as always) feel free to reopen it.

**Comment by Ponsudana** [comment]
Thank you @marijanbeg
