### ISSUE TITLE
AttributeError: module 'oommfc' has no attribute 'gamma0'

### ISSUE THREAD

**Issue by Zulfidin** [ubermag/help#50]
I am getting this error:

<img width="872" alt="Screen Shot 2019-09-05 at 09 57 20" src="https://user-images.githubusercontent.com/21960382/64353903-18e96780-cfc4-11e9-9dd3-1b905e8bbd82.png">

macOS Mojave, version: 10.14.6
I installed it using "conda"

**Comment by marijanbeg** [comment]
Hi @Zulfidin, `gamma0` in new oommfc interface is now accessed as `oc.consts.gamma0`. The reason for this was to shorten the list of available functions/values for the tab completion.
