### ISSUE TITLE
ubermag.test() has no documentation

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#51]
<pre>
In [1]: import ubermag

In [2]: ubermag.test?
Signature: ubermag.test()
Docstring: <no docstring>
File:      ~/anaconda3/envs/ubermag/lib/python3.6/site-packages/ubermag/__init__.py
Type:      function

In [5]: ubermag.__version__
Out[5]: '0.1'
</pre>

**Comment by marijanbeg** [comment]
This is now added on master.
