### ISSUE TITLE
Read Multiple OMF file

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#52]
Hi,

I tried to read a OMF file as,
read_field= df.Field.fromfile(omffilename)
It worked well.

If there are 100 OMF files, can visualize it all at once? Or is there a quick way to import multiple files?

And any ways to convert these into a video/movie?

Thank you,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, this is a part of `micromagneticdata` package which is able to load multiple OMF files. However, there is no tutorial about that at the moment. I will create one and will let you know.

**Comment by marijanbeg** [comment]
We have just finished an online workshop, where we discussed this topic. You can find several tutorials where we show interactive plotting of specific drives.
