### ISSUE TITLE
Restart program from stopping point

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#53]
Hello,

For a time drive, td.drive(system, t=1e-9, n=100)
The program stopped at n=65 and the results are displayed.
How can I restart the program to get results from 65-100?

Thank you,

**Comment by fangohr** [comment]
It is hard to say what is going on. Can you provide more detail? See https://fangohr.github.io/computing/smartquestion.html for some guidance.

**Comment by Ponsudana** [comment]
Hi @fangohr 
Thanks for helping out.

![Screenshot](https://user-images.githubusercontent.com/43433451/68009186-4b9f9b80-fca7-11e9-8ca0-d042f43bf315.png)

For time driver, td.drive(system, t=1e-9, n=100), the OOMMF stopped at n=66.
system.dt display the results with 66 rows and the driver file has 66 *omf files.
As my simulation time is longer I wish to know a possible way to restart it from the stopping point.

Thank you,
Regards,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana,

Thank you for your question. There is no convenient way of restarting simulation. However, if the Hamiltonian is time independent, you can always load the last simulated file (`system.m = df.Field.fromfile(filename)`) and continue time integration. In the directory where you are running Ubermag simulation, a directory with the same name as your system should be created. In the last `drive-N` directory, you can check the last file name and load it in.

This feature could be implemented as a convenience function of Ubermag and I will consider doing that.

I am going to close this issue, but please feel free to reopen it if anything does not make sense.

**Comment by Ponsudana** [comment]
Thank you @marijanbeg 

I have tried to load an omf file for the directory and continued time integration.

**ipynb and omf files: 
[NDsky.zip](https://github.com/ubermag/help/files/3953880/NDsky.zip)**

1. Tried to load an omf file which is a MinDrive after applying a magnetic field.
2. Tired to load an omf file which is a TimeDrive at 1ns.

Got "_NotImplementedError_" while continuing time integration.

Regards,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, this looks like a strange behaviour to me. I will have to investigate how this could be fixed in more details.

As a temporary solution, you can add `system.m.mesh = mesh` in cell 20 of the notebook you sent me (after `system.m= df.Field.fromfile(h300)`).

**Comment by marijanbeg** [comment]
I will reopen this issue because it could be a bug.

**Comment by Ponsudana** [comment]
Hello @marijanbeg 
**_system.m.mesh=mesh_** is working.

But when I changed the velocity constant value and continued the simulation the values are not changing and I'm getting the same previous results.

**ipynb file: 
[ND_u.zip](https://github.com/ubermag/help/files/3982065/ND_u.zip)**

My objective is to change the velocity in the Zhangli term for the same system from the ground equilibrium state after applying the magnetic field.
I also tried another way to change the value and run the time driver in a loop. But similarly, the loop is working and the value is not incremented.
I wish to know if it's possible to change the value of u (or any constants like beta, H, D, K) and continue the simulation?


I don't know if I could address this issue here,
For a change in the magnetic field, in Tutorial 08: Standard Problem 4, it will be helpful if the second magnetic field variation is also shown for the same system from the equilibrium configuration.
Also, a tutorial about hysteresis loop study by varying magnetic fields in a range (-mT, mT) will be helpful.

Thanks for helping in all possible ways. I'm really grateful for all the supports.

Regards,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, yes, it is possible to change the parameters after the Hamiltonian or the dynamics equation are defined. By looking at your notebook, in cell 24, you are changing the value of a variable which is not a part of the system object.

Changing parameters can be done for example:
- external field: `system.hamiltonian.zeeman.H = new_value`
- exchange energy constant: `system.hamiltonian.exchange.A = new_value`
- velocity: `system.dynamics.zhangli.ux = new_value`

Can you please clarify what change you would like to have in standard problem 4?

I assumed the hysteresis loop is obvious, but I will make a tutorial soon (I am travelling at the moment, so my availability is a bit limited). In summary, the code skeleton would be:
```
B_array = [0, 0.1, 0.2, 0.3]  # array of fields in T
mz = []
for B in B_array:
    system.hamiltonian.zeeman.H = (0, 0, B/oc.consts.mu0)
    md.drive(system)
    mz.append(system.m.average[2])
```

**Comment by marijanbeg** [comment]
When you are inside the notebook, you can always try tab completion (pressing TAB after typing the dot) in order to see that attributes you can access and change.

**Comment by Ponsudana** [comment]
Thank you @marijanbeg 

Nothing much in standard problem 4. You have mentioned about new value change in zeeman Hamiltonian. That will work for stdprblm4. 

I'll try B_array for hysteresis loop.

Finally, Thanks for the "tab" tips.

**Comment by DebanjanPolley** [comment]
Hi @marijanbeg and @Ponsudana,
I am trying to calculate a hysteresis loop of a thin film (similar to standard problem 1) with Ubermag. But I am getting kind of a straight line with no coercivity. Can you help?
I have attached here my notebook.

[Hysteresis.ipynb.zip](https://github.com/ubermag/help/files/4377112/Hysteresis.ipynb.zip)

Thanks,
Debanjan

**Comment by marijanbeg** [comment]
Hi Debanjan, thank you for your question. I fixed the loop for computing hysteresis and also did some "improvements" on the way (I attach the notebook). I commented all the changes I did and put questions in certain places for you to consider, where potential mistakes can be hiding.

If anything does not make sense or you have any other question, please let us know - happy to help. 

Cheers,
Marijan

[Hysteresis.ipynb.zip](https://github.com/ubermag/help/files/4377339/Hysteresis.ipynb.zip)

**Comment by DebanjanPolley** [comment]
Thanks Marijian for the help and for the important tips in the notebook. I was stuck for last 2 days with it. You are right about the uniaxial anisotropy, I was randomly checking the system with different values to get a loop.

Thanks,
Debanjan

**Comment by marijanbeg** [comment]
You are welcome Debanjan. Next time, please do not be stuck for 2 days, but ask earlier :)
