### ISSUE TITLE
Link in documentation broken

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#54]
On this page https://discretisedfield.readthedocs.io/en/latest/ipynb/12-tutorial-ovf2vtk.html, the last link leads to a 404: 

Full description of all existing functionality can be found in the API Reference. (broken link is https://discretisedfield.readthedocs.io/en/latest/api_documentation.html)

**Comment by marijanbeg** [comment]
This is now fixed on master in `discretisedfield` for all notebooks.
