### ISSUE TITLE
Plotting magnetisation along a line

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#56]
I much like the details in https://discretisedfield.readthedocs.io/en/latest/ipynb/09-tutorial-matplotlib-visualisation.html that show how the plotting of 2d images with matplotlib can be tailored .

Should we add an example that shows how to plot the magnetisation (maybe m_x, m_y) as function of space along a line? This could be used to show the profile of a domain wall or the helix as we scan through a skyrmion core.

**Comment by marijanbeg** [comment]
This section is now added to tutorial 09 on master.
