### ISSUE TITLE
Plot regions documentation

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#58]
There is a command `mesh.k3d_regions()` (for example in https://oommfc.readthedocs.io/en/latest/ipynb/04-tutorial-dmi.html, input cell [10] at the moment).

Is this document? I couldn't find it in https://discretisedfield.readthedocs.io/en/latest/ipynb/10-tutorial-k3d-visualisation.html

**Comment by marijanbeg** [comment]
I forgot to add it to the tutorials - my mistake. I added a section to https://discretisedfield.readthedocs.io/en/latest/ipynb/10-tutorial-k3d-visualisation.html for plotting regions.
