### ISSUE TITLE
Periodic boundary condition example

### ISSUE THREAD

**Issue by fangohr** [ubermag/help#61]
It would be good to add one or more examples that make use of periodic boundary conditions - at the moment the only place we mention pbc is https://oommfc.readthedocs.io/en/latest/mesh.html#oommfc.Mesh (I think).

Maybe a tutorial notebook that creates a hexagonal skyrmion lattice with PBC (and without demag)?

**Comment by marijanbeg** [comment]
Tutorial 14 is added in `oommfc`.
