### ISSUE TITLE
Does the mumax3c work?

### ISSUE THREAD

**Issue by ThinkfreeJ** [ubermag/help#62]
Hi Ubermag team,

How to set up the mumax3c on Linux? I got a error message "ModuleNotFoundError: No module named 'mumax3c' " when I tested the mumax3 with the command: python3 -c "import mumax3c; mumax3c.test()".

Thanks!

**Comment by marijanbeg** [comment]
Hi @ThinkfreeJ, we recently went through major restructuring of `oommfc` and its associated packages. Therefore, some work is still required to address those changes in `mumax3c`, which is the reason why it is not available at the moment. I will leave this issue open, so you can remind us in a few weeks.

**Comment by ThinkfreeJ** [comment]
@marijanbeg Thank you very much for your hard work.

**Comment by sergiomtzlosa** [comment]
Dear Ubermag team,

Thank you for this useful tool, it is impressive! 🥇 

Please can you tell us if you have a roadmap to implement mumax3 on the ubermag tool? or even can you point us some milestone date for the mumax3 integration on ubermag?

Thanks a lot

**Comment by Emanon77** [comment]
Is it available now? I still can't locate the mumaxc module.

**Comment by code-whale** [comment]
Dear Ubermag team,

I would like to ask whether the mumaxc module can be used now, I still can not find it, and the corresponding document reference can not be opened.

**Comment by PkRPintu** [comment]
Dear UBERMAG Team,

I wish to do some simulation involving Spin Orbit Torque and I found out that it is possible to do in mumax3. Am I correct? If so, then may you please guide on about any documentations and examples on how to use mumax3 in UBERMAG? Is it possible now to use mumax3 now in Ubermag?

Thanks a lot for your help.

Best wishes
Pradeep

**Comment by lang-m** [comment]
Support for mumax3 has been added in ubermag version `0.64.0` (not everything in Mumax3 is supported currently).
