### ISSUE TITLE
Defining Special Dynamics

### ISSUE THREAD

**Issue by Ponsudana** [ubermag/help#63]
Hello,

Using micromagneticmodel I have derived a special dynamics with the help of the tutorial.
https://micromagneticmodel.readthedocs.io/en/latest/ipynb/02-tutorial-deriving-dynamics-term.html
ipynb file: 
[Special dynamics.zip](https://github.com/ubermag/help/files/4260972/Special.dynamics.zip)
How to include the derived dynamical term in a micromagnetic system?
_dynamics= mm.Precession(gamma=2.211e5) + mm.Damping(alpha=0.5) + **Special Dynamics**_

Also, can I add the special dynamics term to my predefine system using oommfc.
_system.dynamics= oc.Precession(gamma=2.211e5) + oc.Damping(alpha=0.5) + **Special Dynamics**_
How can I define the special dynamics?

Regards,
Ponsudana

**Comment by marijanbeg** [comment]
Hi @Ponsudana, this implementation looks good to me. However, the main purpose of that tutorial is how to make an interface class for the micromagnetic calculator (e.g. OOMMF or mumax3) if it can be computed by that calculator. Can OOMMF compute that dynamics?

**Comment by Ponsudana** [comment]
Hi, the special dynamics represent damping-like term of Spin-Orbit Torque (SOT). OOMMF can compute it with the STT module.

**Comment by marijanbeg** [comment]
Thank you for the clarification. We are doing major refactoring at the moment and I will try to add that term in Ubermag for you. Please remind me in 2 weeks if you do not hear anything from me.

Thank you for your patience.

**Comment by marijanbeg** [comment]
Hi @Ponsudana, the new ``oommfc`` package is released and Slonczewski term is there.

Please note that we did some major refactoring (in all Ubermag packages) and added a lot of new functionality. It is going to take us some time to make tutorials for all of them, but:

1. All functionality is fully documented in API-documentations for separate packages.
2. Jupyter notebooks in tutorials are running and all code cells are correct. However, they still need some polishing.
3. You are always welcome to raise an issue to ask a question or report any bugs.

Thank you for your patience.

**Comment by Ponsudana** [comment]
Thanks for the update.
