### ISSUE TITLE
Temperature/thermal energy in LLG equation

### ISSUE THREAD

**Issue by YenLinHuang** [ubermag/help#65]
Dear ubermag,

Is there a way for me to add the thermal energy term to simulation the retention problem? 
Many thanks!

**Comment by marijanbeg** [comment]
Hi @YenLinHuang,

Thank you very much for your question and for using Ubermag. One of the main assumptions in micromagnetics is that it is at zero temperature. Therefore, we do not support T>0 simulations in Ubermag.

Please let me know if you have any further questions.

Best,
Marijan
