### ISSUE TITLE
oommfc.test() with 64 failed, 77 passed, 1 skipped, 5 deselected, 2 warnings

### ISSUE THREAD

**Issue by tk0000** [ubermag/help#66]
Hi Ubermag team-
I am excited to start using your code. Thanks for your hard work!

I am running on Windows 10 and recently installed Anaconda (Anaconda3-2020.02-Windows-x86_64), OOMMF (oommf12b3_20190927_86_x64), and then used pip to install ubermag 0.1 (oommfc 0.8.16). After setting OOMMFTCL to the correct path in my environment variables, I was able to get oommfc to respond.

From the Anaconda Powershell Prompt, I ran: python -c "import oommfc; oommfc.test()" and get a result of 64 failed, 77 passed, 1 skipped, 5 deselected, 2 warnings. Many of the failures are due to the same things:

AttributeError: 'TimeDriver' object has no attribute 'delete'
AttributeError: 'MinDriver' object has no attribute 'delete'
TypeError: compute() takes 2 positional arguments but 3 were given

Please let me know how to proceed. I am happy to provide more information if that helps.

**Comment by marijanbeg** [comment]
Hi tk0000,

Thank you got your question. The error messages suggest you have an outdated version of oommfc. What do you get when you run: `python -c "import oommfc; oommfc.version()"`? As I understand, you have installed OOMMF yourself and then used pip to install Ubermag.

Have you tried to install everything using conda? You can create a new environment (to avoid any possible conflicts) and then install Ubermag.

```
conda create -n ubermag python=3
conda activate ubermag
conda install --channel conda-forge oommfc
```

Please let me know if this still does not work.

**Comment by tk0000** [comment]
Thanks marijanbeg-
Your suggestion to create a new environment worked (76 passed, 1 skipped, 5 deselected, 6 warnings), but I am not familiar with managing conda environments so please bear with me for a moment.... I normally work with Spyder and access it through Anaconda Navigator. I have noticed that I can now select "Applications on: ubermag" in the home screen of Anaconda Navigator. If I start Spyder from there, I can run oommfc.test() and get the same result (76 passed, 1 skipped, 5 deselected, 6 warnings)!

Getting back to your question regarding oommfc version (running from prompt again):
When I run `python -c "import oommfc; oommfc.version()"`, I get `AttributeError: module 'oommfc' has no attribute 'version'`. On the other hand, I am able to get the oommfc version when I run `pip list`, and that returns 0.8.16. This is true both in my base environment and the new ubermag environment.

As long as we are on the topic of conda versus pip, I hope to get your input on how to perform the installation from a clean slate... When I followed the installation instructions on [readthedocs](https://oommfc.readthedocs.io/en/latest/ipynb/00-tutorial-installation-testing-upgrade.html), I tried `conda install --channel conda-forge oommfc` in my base environment with a result as follows:
`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed`

At this point, my prompt just hangs forever until I stop the installation. Of course, we have already seen that creating a new environment does the trick. Previously, I did not know this technique and tried installing through pip which ultimately led me to ask for your help. Is there something funny going on with my version of Anaconda? Do other people see the same issue while performing conda install? 

Thanks again for your help!

**Comment by marijanbeg** [comment]
Hi @tk0000,

Great, I am glad it worked. Here are the answers to your questions:

1. I made a mistake when I asked you to get the version of oommfc. That line should be `python -c "import oommfc; oommfc.__version__"`. I forgot double underscores. Sorry about that.

2. When you run `conda install --channel conda-forge oommfc` in your base environment, then there is a risk you already have something installed in that environment with certain set of dependencies (e.g. it can be a Python version, or any other package). Then, if you try to install `oommfc`, conda struggles to decide what to do with package versions which are already installed in that environment. It can either make `oommfc` work, which would mess up already installed packages, or it can keep the packages already installed working, but then oommfc cannot be installed. That is why the safest way is to first create a new environment, and then install Ubermag there. This avoids any conflict to occur, and this is basically the main purpose of conda. In summary, there is nothing wrong with the Anaconda version you have, but with the packages you have in your base environment. For instance, I personally, never install anything in the base environment, but always create separate ones.

I hope this answered you questions. I will close this issue now, but if you have any further questions, please feel free to reopen it.
