### ISSUE TITLE
conda-install complains about CUDA driver version

### ISSUE THREAD

**Issue by asamarco** [ubermag/help#67]
Hi, I would be willing to test ubermag on my local machine, I am failing with the suggested installation within a conda environment as the CUDA driver version seems not compatible

```
(base) C:\Users\Marco>conda install --channel conda-forge ubermag
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abor\
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0
```
Considering that I am looking forward more to the frontend to oommf thanto mumax, can I workaround this issue somehow?

**Comment by marijanbeg** [comment]
Hi @asamarco, thank you for your question. The error you get means there is a conflict between the packages already installed in your base environment and some of the Ubermag packages. You should try by creating a new environment and installing Ubermag there. This way you avoid any conflicts between your mumax3 and OOMMF installation.

```
conda create -n ubermag python=3
conda install --channel conda-forge oommfc
conda activate ubermag
```

A similar question and solution is in issue #66 

I will close this issue now, but please feel free to reopen if you have any further difficulties.
