### ISSUE TITLE
Exchange energy terms for subregions, need to supply interface term

### ISSUE THREAD

**Issue by andreasfrisk** [ubermag/help#68]
When simulating two regions with different exchange energy A you need to supply n+1 terms giving a value for A at the interface between each region. If the different A are given with a dictionary it will look like this:
A = {'region1': 0, 'region2': 1e-12, 'region1:region2': 0.5e-12}
system.energy = mm.Exchange(A=A)

Since I'm new to ubermag I forgot about this and only supplied two terms:
A = {'region1': 0, 'region2': 1e-12, 'region1:region2': 0.5e-12}.
I then ran different simulations for a couple of days. But my results gave decoupled regions, which I did not realize was wrong until I ran a simulation where both regions had the same constant which I then supplied as:
A=1e-12

Why is not an error or warning given when you only supply two terms to the exchange energy?

A warning would have saved me some time.

**Comment by marijanbeg** [comment]
Hi @andreasfrisk, thank you for your question and I am sorry for the problems you encountered. The suggestion you give is fully justified for a simple system (e.g. 2 regions) and a warning message would be helpful. However, in the case of more complicated samples (more regions, with all sorts of complicated boundaries), it would be very difficult for Ubermag to explore all possibilities how a user could have made a mistake (maybe user defined overlapping subregions, maybe subregions do not cover the entire domain, duplicates,...). In addition, not defining a parameter at the interface of the system might be required by the user. Therefore, this is a difficult decision in terms of deciding how much Ubermag should restrict the user. We decided to give as much freedom as possible to the user and assume the user is fully aware of all restrictions.

Please feel free to reopen this issue.
