### ISSUE TITLE
Simulating  Oxs_SpinXferEvolve.

### ISSUE THREAD

**Issue by squnafeesa** [ubermag/help#7]
Hello JOOMMF team,

In OOMMF,  " Oxs_SpinXferEvolve "  is a time evolver. Is it possible in JOOMMF to simulate MTJ devices with this kind of evolver.

Thanks,
Nafeesa.

**Comment by mb1a15** [comment]
Hi Nafeesa,

We can implement this extension to JOOMMF. For testing purposes, could you please provide us an example as a MIF file or a problem description with the expected output. This will help us understand the use case you require as well as what are the requirements for your problem.

**Comment by squnafeesa** [comment]
Hi,
Thanks, for your response.To start with, is it possible to get the same output in JOOMMF  which we get from the spinxfer.mif  file  located in "oommf/app/oxs/local" folder.

**Comment by marijanbeg** [comment]
This is a part of new release. Please refer to documentation for details.
