### ISSUE TITLE
Error: The T crystal class is not supported on win32 platform

### ISSUE THREAD

**Issue by Baratjan** [ubermag/help#70]
Dear Ubermag team,

Thank you so much for this excellent work, I am enjoying running it on Jupyter!

I am just having one problem when simulating things with DMI. When I set the crystal class other than Cnv, I am having the same error "... not supported on win32 platform", although I have installed everything with their 64bit version (including anaconda). Any idea how to fix this? Many thanks in advance!

**Comment by marijanbeg** [comment]
Hi @Baratjan,

Thank you for using Ubermag and I am sorry about the problem you encountered. Unfortunately, precompiled OOMMF for Windows does not have T and D2d DMI extensions, so Ubermag cannot do much there. This is basically the meaning of the error message you got. If you have to keep using Windows machine, then I can suggest trying to use docker to run OOMMF.

Please let us know if you have any further questions.
