### ISSUE TITLE
New Issue for Standard Problem 3

### ISSUE THREAD

**Issue by okmike** [ubermag/help#71]
Thanks for your replying. I checked the reference website for the Standard Problem 3 at https://www.ctcms.nist.gov/~rdm/mumag.org.html. In the description of the problem, it said that the "The results should be shown to be independent of the discretization size." Could you explain this statement as well? Thank you very much.

_Originally posted by @okmike in https://github.com/ubermag/help/issues/64#issuecomment-638100248_

**Comment by fangohr** [comment]
Your question relates to the physics of the standard problem, not Ubermag. I suggest you subscribe to the mumag mailing list (see https://www.ctcms.nist.gov/~rdm/mumag.org.html), check the archives if the question was dealt with before, and if not, ask your question there.

[In general, for any numerical discretisation of space (or time) you would expect that the result of the simulation on the discretised space is independent of the discretisation you have chosen. If not, then typically the discretisation is too coarse. I think this is what is meant in the context you refer to.]
