### ISSUE TITLE
T/O crystal class for DMI on windows

### ISSUE THREAD

**Issue by fredrendell7** [ubermag/help#72]
When trying to run a simulation involving bulk DMI, with crystal class 'T' or 'O', I get the following error (on Windows 10):

'ValueError: The T crystal class is not supported on win32 platform.'

**Comment by fredrendell7** [comment]
I just noticed there was already a closed issue adressing this so I am closing my question.

**Comment by marijanbeg** [comment]
Hi @fredrendell7, thank you for your question. There is a way of using T(O) crystal class on Windows using Docker. I will make a tutorial about that next week and let you know.

I am going to reopen this issue just to be sure we address it later.

Please let us know if there is anything else we can help with.

**Comment by fredrendell7** [comment]
Hi @marijanbeg, okay that's great to hear - thanks for the response!

**Comment by marijanbeg** [comment]
Hi @fredrendell7, thank you for your patience. I addressed this issue in another repo: https://github.com/ubermag/workshop/issues/15

If anything does not make sense, please let me know.
