### ISSUE TITLE
Periodic boundary conditions and demag

### ISSUE THREAD

**Issue by fredrendell7** [ubermag/help#73]
Hi, 

I am getting the following error when trying to specify x-y periodic boundary conditions (on OSX and Windows 10 with docker installed) with a system that includes demag: `RuntimeError: Error in OOMMF run.`. Is there any way around this in ubermag or is it an intrinsic limitation of OOMMF? 

Thanks in advance

**Comment by marijanbeg** [comment]
Hi @fredrendell7, this is an intrisic limitation of micromagnetics (and OOMMF). Only 1D periodic boudary conditions are allowed. There is a 2D PBC extension for OOMMF as well and we can make it available in the next release.

I am going to keep this issue opened so we address it later.

**Comment by fredrendell7** [comment]
Hi @marijanbeg, okay that is good to know. I have only used Mumax3 up until this point, and never ran into an issue where PBCs were not supported when demag was included. I guess this is because demag is implemented in a different way?
Cheers

**Comment by iamauyy** [comment]
Hi @marijanbeg, I was wondering when would the 2D PBC extension for OOMMF be released? Thanks a lot.

**Comment by marijanbeg** [comment]
Hi @iamauyy, thank you for your question. I am not sure, but we could maybe include it in the next release. What OOMMF extension are you referring to? Could you please send us a link to it just to make sure we are talking about the same thing?

**Comment by marijanbeg** [comment]
To consider for the next release (@lang-m).

**Comment by marijanbeg** [comment]
After investigating this issue, we discovered that the OOMMF extension for 2D periodic boundary conditions is very outdated, and it works only in several special cases. More precisely, it is not compatible with all the different energy terms that can be present in the energy equation. Therefore, we believe that, at this stage, adding this functionality to Ubermag would cause more difficulties than benefits, and it would substantially add to the complexity of the code.

I close this issue now and apologise for not being able to accept this suggestion.
