### ISSUE TITLE
Draw with the data obtained by the minimization energy solver

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#76]
Dear Ubermag team，
I studied your tutorial and found that many drawings set the x-axis as the timeline. I recently simulated a model that used the mindiver solver. When I looked at the data table, I found that there was only one row of data, so I could not draw. I would like to ask if I can draw the energy value of each iteration as you did in the tutorial. If you can, could you tell me what to do? thank you for your help.

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. Unfortunately, Ubermag tables functionality does not allow this type of plotting and we focused only on time for the horizontal axis. However, we might include this functionality in the next Ubermag release. I am going to keep this issue open to remind me of addressing this when the new release is available.

**Comment by code-whale** [comment]
Hi@marijanbeg Thank you for your reply, I am looking forward to the next version! 
In addition, I'd like to ask you to consider the following suggestions about solvers: 
The first is that most of the tutorials I've seen so far are using mindiver and timediver, if you can consider adding more pattern solvers in the next version. I know that there are five modes of solver that can be set in mumax. 
The second problem is about setting some temperature-related parameters and simulating them in ubermag, which I don't seem to have found in the tutorials. 
Thank you again for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, what do you mean by solver patterns? Can you give us an example?

`MinDriver` and `TimeDriver` are the "fundamental" solvers in micromagnetics, so anything else you might need can be built starting from these.

**Comment by code-whale** [comment]
Hi@marijanbeg 
As described in API in mumax, for example, the following solvers can be used in mumax. 
Can it be set up through a similar program in ubermag? 
Please forgive me that my mastery of the software is not very good. 
Thank you for your reply!
![image](https://user-images.githubusercontent.com/61874432/86768704-8d77b180-c080-11ea-9774-69734dbf2029.png)

**Comment by marijanbeg** [comment]
Ah, you mean evolvers. This is already in ubermag, but as you say I did not make a tutorial about that:

Here is a example from docstrings:
```
evolver = mc.RungeKuttaEvolver(method='rkf54s')
td = self.calculator.TimeDriver(evolver=evolver)
td.drive(system, t=0.2e-9, n=50)
```

You can have a look at allowed parameters for both evolvers and drivers in the OOMMF documentation. I will try to make tutorial about this as well.

**Comment by code-whale** [comment]
@marijanbeg 
Thank you for your help, I will try to learn them in the following simulation, and then I would like to ask you about the temperature setting. Can the current ubermag run the simulation of additional temperature? if you can, can you teach me how to set it? thank you again!

**Comment by fangohr** [comment]
Dear @code-whale - see https://github.com/ubermag/help/issues/65 for a discussion of the temperature situation.

For future use of the issues: (i) can you please check first if the question has been answered in the previous and closed issues already, and (ii) open a new issue for a new topic? The first item is to reduce the amount that the developers need to spend on answering questions (which otherwise could be used to work on the software). The second item is that it is easier to find answers that have been provided before and need in principle not to be written down again. Many thanks :)

**Comment by code-whale** [comment]
Hi@fangohr 
Thank you for your reply, which gives me a better understanding of micromagnetism, but I have seen a thermal field in mumax's API, and I often see some literature about temperature when I read it, so I would like to ask you if you can consider the problem of temperature in future versions.
![image](https://user-images.githubusercontent.com/61874432/86892415-cf613000-c132-11ea-8e26-0f95d01359ad.png)

**Comment by fangohr** [comment]
Okay, request noted. 

The thermal fluctuations that are sometimes used may well give you a qualitative impression of the effect of fluctuations (and thus they have the potential to be useful). There are also downsides though: for example the results you get depend on the cell size you use, and the time integration step size needs to be fairly small (i.e. long execution time). So one needs to be really careful when using the fluctuations, and we haven't prioritised this feature request for those reasons.

**Comment by code-whale** [comment]
Hi@fangohr 
Thank you for your help. I understand what you mean, and I wait patiently for your update. In addition, my initial purpose of this question is to solve the drawing problem under the minimization of energy solution, that is, whether it is possible to draw each iteration. Marjianbeg replied that I would try to solve this problem in the next version as much as possible. If your team has noticed this problem, then I will not reopen the problem. And will wait patiently for the next version! 
Thank you again and ubermag team for their selfless dedication!

**Comment by marijanbeg** [comment]
Thanks @fangohr for addressing this issue. I am going to keep this issue open, just to remind us to add minimisation step plotting on the horizontal axis in the next release.

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you so much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/mindriver-steps.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.
