### ISSUE TITLE
How to draw multiple omf files

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#77]
Dear Ubermag team，
I saw this problem in the question library and I am sorry to delay your time. I learned tutorial documentation but I still don't read multiple omf files, I generate many omf files when simulating with time solver, but I can only draw final states when I use matplotlib rendering. 
I beg you to teach me how to draw the specified omf file because I need to view the simulation process. It would be better if you could draw multiple files simultaneously. I tried reading methods you wrote in your tutorial but there was an error. 
Hope you can help me solve this problem!

![image](https://user-images.githubusercontent.com/61874432/86886826-2b738680-c12a-11ea-9c93-5f10706230b2.png)

![image](https://user-images.githubusercontent.com/61874432/86886865-3cbc9300-c12a-11ea-93b4-317ecebd1411.png)

**Comment by fangohr** [comment]
Hi, your idea how to read the omf file is nearly right. Use

```
read_field = df.Field.fromfile("domain_wall_pair-Oxs_TimeDriver-Magnezation-0006-0000126")
```
The difference to your line is that you need quotes around the file name (i.e. `"domain_wall_pair-Oxs_TimeDriver-Magnezation-0006-0000126"`) instead of (`domain_wall_pair-Oxs_TimeDriver-Magnezation-0006-0000126`).

The documentation for reading and writing files is https://discretisedfield.readthedocs.io/en/latest/ipynb/11-tutorial-read-write.html.

Regarding the need to use quotes or not, it may help to learn some Python on the side. Chapter 3 in [this book](https://github.com/fangohr/introduction-to-python-for-computational-science-and-engineering/blob/master/Readme.md) comments on that topic.

**Comment by code-whale** [comment]
Hi@fangohr 
Thank you for your answer. I added "" to the program, but it still doesn't work. It shows that this kind of extension is not supported. I don't understand why.
![image](https://user-images.githubusercontent.com/61874432/86891986-39c5a080-c132-11ea-9f04-7193217cff2a.png)

**Comment by fangohr** [comment]
Ah, okay. You probably need to include the `.omf` extension at the end of the filename, i.e. 
```
read_field = df.Field.fromfile("domain_wall_pair-Oxs_TimeDriver-Magnezation-0006-0000126.omf")
```

**Comment by code-whale** [comment]
@fangohr， 
I think this problem is caused by the complexity of my file name and path. I later tried to put the file on the desktop and rename it with a simple name, such as 111111.omf. at this point, it can be read, but I still don't know how to read multiple files. 
Thank you for your reply.

**Comment by fangohr** [comment]
Yes, I made a second mistake: if you want to read file names directly from disk, you need to prepend the name of the 'system' that has created the files. 

In any case, there is a better way of processing these files using the `micromagneticdata` package (@marijanbeg ).

**Comment by code-whale** [comment]
@fangohr I'm sorry I don't understand what you mean, but I'm currently reading files through this command statement, and I've noticed the micromagneticdata package, but I can't find a tutorial on how to use it. 
Thanks for your help!
![image](https://user-images.githubusercontent.com/61874432/86901611-6e8c2480-c13f-11ea-8cd6-d2c65af587a2.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, if you remember, we talked about this functionality during session 2 of our workshop. There is a `micromagneticdata` package, which is a part of ubermag and does exactly what you need. You can have a look at some of the tutorials there, in particular, vortex dynamics (https://github.com/ubermag/workshop/blob/master/tutorials/vortex-dynamics.ipynb), where we show how to load single fields from individual drives.

For example, in cell 2, there is: `data.drive(2).step(1).plane('z').mpl()` which loads the third drive (0, 1, 2) and then takes step 1. This returns a field, which you can then plot. In the next cell, we build an interactive plot.

**Comment by code-whale** [comment]
Hi@marijanbeg ，Thank you for your answer. I am ashamed of my carelessness. I will study the tutorial carefully again! 
I would like to express my heartfelt thanks to you and the ubermag team for your help.

**Comment by marijanbeg** [comment]
Don't be. It is not easy to keep track of everything :)
