### ISSUE TITLE
Extract single row or column data from simulation results

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#78]
Dear Ubermag team，
When I use table.data, I find that it exports all the data, but many rows will be omitted in the middle. In addition to using other software to view odt documents, is there any other way to view single-column data? I think the widget is also very good, but unfortunately it can only choose the data drawn on the y-axis. It would be great to export the single-column data as a list, so I can draw the x-axis freely. Can the current ubermag package do this?
I tried to modify the code as I wanted, but it was obviously incorrect. Can you help me with this function?
![image](https://user-images.githubusercontent.com/61874432/87222650-1146dc00-c3a8-11ea-8e70-f8f7f93b7d2b.png)

**Comment by catrevil** [comment]
If I understand correctly, this was covered in one of the tutorials put on by spintalks recently. To clarify, you want to extract only, for example, the mx component from the table of values, and make a list of just these values? Then you’d plot it by index?

It’s not exactly clear to me what you mean by “draw the x-axis freely”, can you further explain this?

For convenience, can you please write your code in an easily copy-and-pasteable format? If you surround the code block with 4 “`” symbols in a row
````
Like this
````
It helps immensely for readability, and allows others (who have the same issue, or want to help) to more easily use or improve upon your code :)

**Comment by code-whale** [comment]
Hi@catrevil 
I'm very sorry, but I don't know how to write code in this way. At present, the data on the x-axis in the tutorials I have seen are all "time". I noticed that the widget can choose to draw data in a single column, but only the values on the y-axis are optional, and the values on the x-axis are not selectable. For example, how can I write code when I want the x-axis to be "step"?

**Comment by catrevil** [comment]
Ah, it is markdown style. I will explain, because I cannot see your image well enough to write it myself (and many others will not either):

To put your code in a copy and pasteable manner, you would select/highlight your code in the jupyter notebook, right click or keyboard shortcut (ctrl+v) copy this. Then, in here, type 4 of the “`” symbols in a row, as in “````” without the “ quotation marks, press enter, paste the code you copied from your jupyter notebook, press enter, then type 4 of those symbols from before again. This will format the code block in markdown style for posting on sites such as this one. I am writing this on mobile, however, so it may format it like crazy. I’ll be to my pc soon & can provide better reference for the above markdown style for code blocks.

With how the ubermag built-in functionality is currently, the automated choice for x-axis is indeed time.

I know this issue was brought up before, wanting to plot against something other than time, but there was currently no solution. I think I can come up with a simple way to do this that just accesses values of the current table format, though

As for the shortening with “...” I know this was discussed in one of the tutorials, but I cannot recall which. Indeed, with the powers of matplotlib and pandas combined with ubermag, we can definitely display without “...”, export the column data for use in another program, and plot it in the notebook with matplotlib. I’ll reply with code in a few hours or so that will show you how to do what you want to do :) I hope this will be helpful for you!

**Comment by code-whale** [comment]
@catrevil 
Thank you for your help. What I am simulating is also the example given in the tutorial in workshop.
such as（Is that the markdown format? I'm not very good at it.）
"`"@df.interact(yaxis=system.table.selector(),xlim=system.table.slider())"`"
       "`"def my_interactive_plot(yaxis, xlim):"`"
    "`"system.table.mpl(yaxis=yaxis, xlim=xlim)"`"

I wanted to assign"`" xlim"`" with"`" system.table.selector ()"`", but then the program got it wrong, obviously because I thought it was too simple:).I want to ask ubermag if it is possible to do this because mmdisp in oommf is free to choose the data you want to draw on the x-y axis, and it would be great if you could solve this problem!

**Comment by catrevil** [comment]
For markdown style, you would just sandwich them, or wrap them, or surround them, or however you want to call it, with those four symbols and by that, I mean to just type ```` which doesn't format in a strange way, as I previously thought, which is why I was using the quotation marks.
( However, it does format weird if you tried to type them in quotations beforehand! If you're on PC you can click on the little m in the lower right-hand corner to see more about it. The site it leads to is https://guides.github.com/features/mastering-markdown/ )

It would look like this:
````
>>````
>> With the text for the code block here.
>>````
>> I'm only using the >> to avoid the formatting of the ```` symbols
````

So, if you type that, it would look like this
````
With the text for the code block here.
````

Hope that makes sense!

To be clear, what tutorial is it? I'll show a general method, but it would be useful to work from the tutorial you've been using. The name of the tutorial notebook would be helpful!

**Comment by marijanbeg** [comment]
Hi @code-whale, `system.table.data` is a `pandas` datafreame. This means it is very flexible what you can do with you data. For instance, if you want to extract a single column (e.g. `mx`), you type `system.table.data['mx']` and this gives you pandas series. Please have a look at pandas documentation (https://pandas.pydata.org/docs/getting_started/index.html) and let us know if there is still something you would like to do, but cannot figure out how.

**Comment by code-whale** [comment]
Hi@marijanbeg ，@catrevil I feel very much about the help you have given me. I think I need some time to learn these methods. If I encounter problems in my study, I will ask for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, I assume this issue is now resolved, so I am going to close it. If not, please reopen it again.

Thanks again @catrevil for helping others - much appreciated.
