### ISSUE TITLE
How to draw the magnetization curve along the diameter direction

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#79]
Dear Ubermag team，
In the process of simulation, I hope to be able to draw the magnetization along the diameter of the disk, as shown in the following figure, so how to write code? can you help me? there is only average magnetization in the data I derived.
![image](https://user-images.githubusercontent.com/61874432/87786839-44d4ab00-c86d-11ea-8fe1-83ca6f41f9d8.png)
![image](https://user-images.githubusercontent.com/61874432/87787002-8402fc00-c86d-11ea-9181-e0cf488c38f9.png)

**Comment by catrevil** [comment]
Hi @code-whale ! The [Line](https://discretisedfield.readthedocs.io/en/latest/line.html) class will be your greatest friend in this endeavor! Take a look at the API reference there & let the thread know if any confusions remain? Essentially, you will define a line on which you want to extract that information from--it would be the red lines in the second figure you show.

**Comment by code-whale** [comment]
Hi@catrevil ！I saw this API and the corresponding tutorial! Thanks for your help! This is really great!
