### ISSUE TITLE
Spin Orbit Torque in Ubermag

### ISSUE THREAD

**Issue by PkRPintu** [ubermag/help#80]
Hi there,

Does anyone know how to implement SOT induced magnetization dynamics in Ubermag ?  Also if I wish to simulate a system with two heavy metal layers (e.g. Pt) on either side of a ferromagnet then the spin polarization from top and bottom layers will be opposite to each other. That means if the current is in the x-direction (in plane) then the spin polarization in top and bottom HM layers will be in the +y and -y-direction respectively. Is there a way how to implement the torques in the ferromagnetic layer caused by these spin polarisation ? 

Thanks a lot for the answer.

**Comment by marijanbeg** [comment]
Hi, SOT unfortunately cannot be simulated in Ubermag.

**Comment by PkRPintu** [comment]
Hi @marijanbeg , Thanks a lot for the response. I found out that the SOT can be implemented in mumax. And in your lecture you were mentioning that it is possible to use mumax as a solver also in ubermag. Will you be able to let me know if there is any lectures or examples or manuals on how to implement mumax in ubermag? Thanks a lot.

**Comment by jmiasif** [comment]
Hi @PkRPintu , i wish to simulate a system single layer deposited on substrate and want to calculate spin polarisation efficiency. is it possible in ubermag?
thanks in advance for any suggestion.
