### ISSUE TITLE
Can the initial magnetization be set as bubble domain by function

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#81]
Dear Ubermag team,
I would like to know if it is possible to set the initial magnetization state by function as you explained in the tutorial. I want to create an initial magnetization state of the bubble domain as shown in the figure below, but I don't know how to set the function, can you teach me?
<img width="206" alt="截屏2020-07-25 上午11 11 05" src="https://user-images.githubusercontent.com/61874432/88447601-8d8cf500-ce67-11ea-8468-6bec532dcd3f.png">

<img width="539" alt="截屏2020-07-25 上午11 06 51" src="https://user-images.githubusercontent.com/61874432/88447545-f4f67500-ce66-11ea-82c4-0309fc5623b8.png">

**Comment by marijanbeg** [comment]
Hi @code-whale,

Yes, it is possible. Basically you need to write a Python function to represent the magnetisation. By looking at the bubble you can identify three parts:

1. Inner (red) region where magnetisation is in the (0, 0, 1) direction:
```
if x**2 + y**2 < r_inner**2:
    return (0, 0, 1)
```
2. Outer periphery (blue) region where the magnetisation is in the (0, 0, -1) direction:
```
elif x**2 + y**2 > r_outer**2:
    return (0, 0, -1)
```
3. Transition (white) region where the magnetisation changes as the neel domain wall:
```
else:
    # Here you need some maths which depends on x and y.
    mx = ...
    my = ...
    mz = ...
    return (mx, my, mz)
```

I hope this helps. When you build an initial state and think this is something that can be used relatively often (bubble, skyrmion, domain wall, etc.) you can make a pull request and we can make it part of Ubermag.

**Comment by code-whale** [comment]
Hi@marijanbeg ,Thank you for your reply. I think I need to find out how to make all the points in a concentric ring point to the function of the center of the circle. At present, I don't know how to write this function. I will keep looking for it. Thanks again for your help!
