### ISSUE TITLE
Fixed Spins Function

### ISSUE THREAD

**Issue by askeyjw** [ubermag/help#84]
Hello, thank you to the team who have worked on Ubermag I have found it very intuitive and a great way to learn about micromagnetics. 

I have read through the ubermag and oommf documentation in regards to fixed_spins within the various evolvers available. The list of allowed attributes in the evolvers within ubermag does not contain a fixed_spins attribute whilst in the oommf documentation there exists one. I am not sure whether I am being stupid or whether being able to fix the spins in a certain region of a system is possible within Ubermag. Any help or advice you can provide would be greatly appreciated and apologies if this is a stupid question, but have scoured the documentation and have found no solution. 

I have tried working around fixing the spins by implementing a spatially varying field which essentially fixes spins at the regions I require, but I run into problems if I want to measure domain wall movement in a system with periodic boundary systems. 

Again, sorry if this is a stupid question and thanks again for all your work.

**Comment by marijanbeg** [comment]
Hi @askeyjw, thank you very much for your question and for using Ubermag. You are right - fixing spins is not implemented in Ubermag. However, if this is something you need in your research, we would be happy to implement this functionality and make it available in the next release.

I am on holiday at the moment and I am going to address this when I am back in a few weeks, so thank you for your patience in advance.

**Comment by askeyjw** [comment]
Hi @marijanbeg thank you for your quick response I really appreciate it. This is something that would be very useful in my research in terms of looking at how I can force domain walls to form in infinitely long wires without having to apply spatially varying fields. The whole simulation is slightly complicated with a spatially varying field (periodic boundary conditions and calculating energy components for the DW) so I believe a fixed spins functionality would solve this issue. 

Thanks again for your speedy response and for all your hard work on this program it is a great piece of kit.

**Comment by marijanbeg** [comment]
Hi @askeyjw, thank you so much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/fixed-subregions.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.

**Comment by askeyjw** [comment]
Hi @marijanbeg, 

Thank you for the implementation of the fixed spins function. This is very useful. However, for my own specific purposes I have now realised a further wrinkle that I cannot find a simple a solution to. 

What I want to achieve is to first define two fixed regions and a free region where the fixed regions are at the extremities of a magnetic object and the free region is in the centre separating the two fixed regions. This is fine and works as expected. However I want to now define a function in the free region which returns a random magnetisation direction but the magnetisation within the regions is now only defined via a dictionary, so I am unable to call a function into the dictionary in order to define the magnetisation field. 

Example code: 
`import micromagneticmodel as mm
import discretisedfield as df 
import oommfc as oc
import numpy as np 
import matplotlib.pyplot as plt
import random as rm 

region = df.Region(p1=(-50e-9, 10e-9, 10e-9), p2=(50e-9, 30e-9, 30e-9))
cell = (5e-9, 5e-9, 5e-9)
subregions = {'fixed1': df.Region(p1=(-50e-9, 10e-9, 10e-9), p2=(-25e-9, 30e-9, 30e-9)),
              'free': df.Region(p1=(-25e-9, 10e-9, 10e-9), p2=(0, 30e-9, 30e-9)),
              'fixed2': df.Region(p1=(25e-9, 10e-9, 10e-9), p2=(50e-9, 30e-9, 30e-9))}
mesh = df.Mesh(region=region, cell=cell, subregions=subregions)

Ms = 4.9e5 
A = 9e-12 

def m_free_rand(pos):
    x,y,z = pos
    return [2*rm.random()-1 for i in range(3)]

m_fixed = {'fixed1': (1, 0, 0), 
     'fixed2': (-1, 0, 0), 
    'free': m_free_rand}

system = mm.System(name='NW_Fixed_Region')
system.m = df.Field(mesh, dim=3, value=m_fixed, norm=Ms)
system.m.orientation.plane('z').mpl(figsize=(48,10))`

And this will give error: `TypeError: float() argument must be a string or a number, not 'function'`

One possible (but not easily implemented) solution is to create a subregion at every point in the desired free region using some loops, then define a random magnetisation tuple for each of these subregions. I can see this method becoming very messy though, so I was wondering if there is a way to combine a function which returns a random number for magnetisation components within the dictionary defining the free region? 

Cheers again for all the work you've done on this micromagnetics package, I'm thoroughly enjoying ubermag even though I am terrible at Python. 

-Joe

**Comment by marijanbeg** [comment]
Hi @askeyjw, thank you for your question. This should be a quick fix and we are going to include it in the next Ubermag release. 

@lang-m, could you please add this to the pull request we are working on?

**Comment by lang-m** [comment]
I will add this to the PR.
@askeyjw Until we release the new version you can also use a function as follows:
```
def init_m(mesh):
    def m_free_rand(pos):
        if pos in mesh.subregions['fixed1']:
            return (1, 0, 0)
        elif pos in mesh.subregions['fixed2']:
            return (-1, 0, 0)
        else:
            return [2*rm.random()-1 for i in range(3)]
    return m_free_rand

system.m = df.Field(mesh, dim=3, value=init_m(mesh), norm=Ms)
```

**Comment by askeyjw** [comment]
@lang-m  Thank you so much for this piece of code, this works perfectly! Thanks again for all the work on this, I can't stress enough how useful Ubermag and everyone's help on this repository is. Cheers!
