### ISSUE TITLE
Annealing simulation

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#85]
Dear,Ubermag team,
I know that temperature is generally not taken into account in micromagnetic simulations, but anneal is sometimes done when actually dealing with magnetic materials, and I have seen simulations using the Monte Carlo method in some places. Is this possible in Ubermag, and if so, can you tell me how to do it? Thank you for your help!

**Comment by marijanbeg** [comment]
Hi @code-whale, thank you for your question. As you said, annealing is not something which is done using micromagnetics. The method of choice here would be Monte Carlo.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you for your reply! I saw a description of the Monte Carlo method in Fidimag, but it doesn't tell me how to model it. Do you know how to use monte Carlo methods for simulation in Ubermag? This seems to be the domain of atomic simulation. If possible, please teach me how to model. Thank you again for your kind help!

**Comment by marijanbeg** [comment]
Hi @code-whale, Monte Carlo simulations are entirely different from micromagnetic simulations. Therefore, neither Ubermag nor Fidimag support Monte Carlo simulations.
