### ISSUE TITLE
Installing Ubermag in Ubuntu 20.04 server

### ISSUE THREAD

**Issue by AkravasTheWise** [ubermag/help#87]
Hi, so I'm trying to do something different

To add to my workflow I want to install Ubermag in an Ubuntu server and run scripts outside my laptop using SSH. Following your guide for advanced installation I encountered a problem with setting up numpy. Basically something along the lines `path-for-pip/_in_process.py prepare_metadata_for_build_wheel /tmp/some-tmp-file`. I looked around the web and it said that it may be a problem with the location of the numpy installation source. 

So, I tinkered a while and installed most packages manually (numpy, sympy, jupyter, pandas, nose, matplotlib and sympy). I managed to get around the numpy error this way, but I'm stuck in scipy now. Doesn't seem to matter what I do, how I update scipy or what version I install, I am still hitting a wall. **Could you provide a list of packages and versions I need to install manually in order for the pip installer to ignore the requirements and go on with the setup?**

The machine I am trying to install it in is a Raspberry Pi 4B with Ubuntu 20.04 arm64 architecture, if that is any help.

I'm a big fan of the project, you guys are awesome.

Best regards

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, very interesting! What is exactly the issue you get from scipy?

You can use `--no-dependencies` flag with pip to ignore the dependencies. Then you can identify the packages you are missing when you try to import ubermag.

Please let us know if you managed to resolve this issue.

**Comment by marijanbeg** [comment]
Hi @AkravasTheWise, I will assume this issue is now resolved. If not, please feel free to reopen it.
