### ISSUE TITLE
Topological charge calculation

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#88]
Dear Ubermag team,Can you teach me how to calculate topological charges through Ubermag?

Thank you very much for your help!

**Comment by marijanbeg** [comment]
hi @code-whale, thank you for your question. You can find the relevant information in https://discretisedfield.readthedocs.io/en/latest/field.html#discretisedfield.Field.topological_charge. There are also several examples in the workshop.

Please let us know if you have any further questions.

**Comment by code-whale** [comment]
@marijanbeg ,Thanks for your help, I will learn how to calculate it in these tutorials!
