### ISSUE TITLE
Online-Version of Ubermag Does Not Work Anymore? 

### ISSUE THREAD

**Issue by MartinLonsky** [ubermag/help#89]
Hello, 

Is it possible that the online version of Ubermag (with Binder) is currently not working at all? I am experiencing this issue during the last days. Tried it on different computers where it had worked before, but Ubermag and the Jupyter Notebooks just won't start. Screenshot is attached. Is a possible reason that the developers are working on it at the moment? At least the build logs (console) appear new to me. 

Thank you,
Martin

![Ubermag_Problem](https://user-images.githubusercontent.com/72947369/96184080-8f61d400-0efd-11eb-9225-d0be8fc37882.JPG)

**Comment by marijanbeg** [comment]
Hi @MartinLonsky, thank you for your question and for using Ubermag. You are right, there is some problem with JupyterLab and we need to have a look into that. In the meantime, you can try to use the workshop binder link from this repository: https://github.com/ubermag/workshop. It gives you exactly the same environment as the `oommfc` one.

**Comment by MartinLonsky** [comment]
Hi @marijanbeg, thank you for your quick response! Good to hear that I have not done anything wrong. I hope that the issues with JupyterLab can be fixed. Thank you for the link to your workshop - this works well for me! Best regards, Martin

**Comment by marijanbeg** [comment]
Hi @MartinLonsky, thank you very much for your patience. All Ubermag badges should be working now. If you notice any issues, please let us know.

Please note that Ubermag 0.50 is out and you can update it (`conda update ubermag`). You might also want to have a look at some tutorials to check for new functionalities and (some minor) interface changes: https://github.com/ubermag/workshop

**Comment by MartinLonsky** [comment]
Thanks @marijanbeg and keep up the good work!
