### ISSUE TITLE
How to Decorate MPL Function for Energy Minimization Drivers

### ISSUE THREAD

**Issue by trcote** [ubermag/help#90]
Hi there! First I wanted to thank you for the workshop tutorials through IEEE, very helpful in getting things started.

I'm trying to show the visual change in magnetization for a hysteresis loop by constantly updating the same matplotlib figure. In a loop, I update the Zeeman energy with incremental changes in applied field and running an energy minimization to get a new drive file. In the workshop, its possible to have a decorator for a single time driver, but is there an easy way to do this to have an interactive slider for minimization drive files?

For example lets say I have 10 energy minimization drive files, drive0-drive9. 
Is it possible to decorate a matplotlib function to show 

`data.drive(n).m0.plane('z').mpl()`

where n is the number of the specific drive file I want to view? I've tried with interactive matplotlib buttons that cycle up or down to preview the magnetization, but it just creates a new inline matplotlib figure each time.

**Comment by marijanbeg** [comment]
Hi @trcote, thank you for your question. Yes, `Data` object can return `selector` widget which allows you to go through individual drives one by one.

(Please note that in your plotting line `m0` represents the initial magnetisation, not the relaxed one. If this is not what you wanted, you need to replace it with `m`. )

**Comment by trcote** [comment]
Worked perfectly, tank you for the help. Since every initial magnetization m0 uses the previous drivers relaxed state, either works in this scenario. Just making a template for a small project to give undergraduates an introduction to micromagnetics.
