### ISSUE TITLE
Error using TimeDriver() on system with periodic boundary conditions

### ISSUE THREAD

**Issue by PkRPintu** [ubermag/help#91]
Hi,

I ran into a problem trying to run a oc.TimeDriver() on a system with periodic boundary conditions: Relaxing my system with periodic boundary conditions in x-directions works well, the kernel automatically chooses the TclOOMMFRunner and the output is what I would expect. When proceeding to the oc.TimeDriver() (current in x-direction), I get the following error (see the attachment please)

![ErrorMessage](https://user-images.githubusercontent.com/59337225/96460726-d31d4c00-1223-11eb-9e40-cab232db1066.png)

Also: when dropping the periodic boundary conditions, the default TclOOMMFRunner is chosen and both oc.MinDriver() and oc.TimeDriver() work as expected. Is there something I am missing in order to drive a current through a system with periodic boundary conditions? Did someone encounter the same error message before?

**Comment by marijanbeg** [comment]
Hi @PkRPintu, thank you for your question. Not all energy terms support periodic boundary conditions (for example, demag). What is the energy equation you are using?

**Comment by PkRPintu** [comment]
Hi @marijanbeg , Thanks for your response. The energy terms I am using is Exchange, RKKY, DMI and Zeeman. I am not using Demag. is there any energy term from the above which doesn't support PBC as well?  I am simulating a synthetic antiferromagnet with skyrmions with opposite helicity in both magnetic layers. Thanks in advance for your help.

Best wishes

**Comment by marijanbeg** [comment]
Hi @PkRPintu, can you please send us a minimal failing example, so we could investigate the issue you encountered.

**Comment by marijanbeg** [comment]
I am going to assume this issue is now resolved since it has been inactive for over 3 months and we cannot replicate the error.

If not, please feel free to reopen it :)
