### ISSUE TITLE
Hysteresis simulation with a frequency in the applied field

### ISSUE THREAD

**Issue by daavera** [ubermag/help#92]
Hi everyone. Thanks to the Ubermag team for all their work.

Maybe I wasn't clear enough in my lasst issue. What I pretend to study is how the area of the hysteresis loop of my system varies with the frequency of the applied field. The micromagnetic field library allows me to add a frequency to the applied field in the Zeeman energy. Nevertheless, when I try to run me simulation with oc.MinDriver() I get an error because the system is time dependent, and when I run it with oc.TimeDriver the simulation never ends. Maybe you know a way in which this 'minimization' can be simulated using applied field with finite frequencies?

Sorry for opening a new issue, I wasn't able to re-open the last issue I post.

**Comment by CostiD** [comment]
Hi, 

For creating a hysteresis loop, I think the approach is this: 

- Apply external field (one value at a time), minimize energy, compute average of magnetization component along the direction of the applied field for each field value

You have several options for applying a list of field values (along one direction, for example the x, y or z axis):

- Let's say you want to apply a field that goes from B0 to -B0 and back again to B0 in steps of Bstep (so, for example, 800 mT, 795 mT, 790 mT, ..., -800 mT, -795 mT, -790 mT, ..., 800 mT). For this you can simply write:
```python
B0 = 800 # mT
Bstep = 5 # mT
B_array_1 = np.arange(B0, -B0, -Bstep) # goes from B0 to -B0 - (-Bstep), so 800 to -795
B_array_2 = np.arange(-B0, B0 + Bstep, Bstep) # goes from -B0 to B0 + Bstep - Bstep, so -800 to 800
B_array = np.concatenate([B_array_1, B_array_2])
```
Ok, so for each value in B_array you will run the minimization driver and compute the average of the magnetization component along the direction of the applied field (I will give an example later)

- Ok, so now let's say you want to apply a field from B0 to -B0 which varies as a cosine; additionally, let it vary for a number of periods (nT) and have a certain number of points (npoints):
```python
nT = 1
npoints = 101
B0 = 800 # mT
t = np.linspace(0, nT * 2 * np.pi, npoints)
B_array = B0 * np.cos(t)
```

- Finally, maybe you would like to apply a field which slowly goes down (maybe you want to demagnetize your sample); for this you can specify f (between 0 and 1) - the ratio peak_{n+1} / peak_{n} (so if you want the next peak to be 0.7 smaller than the previous, f = 0.7):
```python
nT = 10
npoints = 1001
f = 0.7
B0 = 800 # mT
D = -np.log(f) / (2 * np.pi)
t = np.linspace(0, nT * 2 * np.pi, npoints)
B_array = B0 * np.exp(-D * t) * np.cos(t)
```

No matter your choice, for making the hysteresis loop, you can do something like this:
```python
# suppose you apply the field along the y direction (0, B_applied, 0)
my = [] # you will append one by one the average of the y magnetization component divided by Ms
for B_applied in B_array:
      # don't forget to convert mT to A/m
      system.energy.zeeman.H = (0, B_applied * 10**(-3) / mm.consts.mu0, 0)
      md.drive(system)
      my.append(system.m.orientation.y.average)
```
That should be it. Just plot "my" against B_array and that should be the hysteresis loop where the applied field can vary like a cosine, damped cosine or whatever you want.

**Comment by daavera** [comment]
Thank you very much for your help. The explanation was very good :)

**Comment by CostiD** [comment]
Great! Glad it was ok, you're welcome :)
