### ISSUE TITLE
Create Concentric Spherical Regions in JOOMMF (Core-Shell Particles)

### ISSUE THREAD

**Issue by MagProf** [ubermag/help#93]
Hello,

I am trying to create concentric spherical regions of magnetic materials to model core-shell nanoparticles, but the df.Region definition is only for cubic regions. We need this specifically so that we can assign different values of anisotropy (Ku) and exchange stiffness (A) to the subregions (the core and shell, respectively).
 
We have tried creating "fields" of Ku and A that are spatially defined inside different radii (similar to the way you might set the magnetization do be within a sphere of a given radius but inside a cubic "region"). However, the calculation results are wrong. I think the only way to do such a calculation would be if the regions can be defined as spherical regions. Can you help?

Thank you.

**Comment by marijanbeg** [comment]
Hi @MagProf, thank you for your question and for using Ubermag. The regions in finite-difference simulations are always cubic, and they cannot be made spherical. In this case, you would need to use finite-elements simulations which allow you to define meshes with "smooth" interfaces. We have a simulation tool called finmag which you can maybe use for that: https://github.com/fangohr/finmag.
