### ISSUE TITLE
Initialization of Random Magnetization 

### ISSUE THREAD

**Issue by Harry-09** [ubermag/help#94]
I'm trying to initialize random magnetization in the 1umx1um area for which, I get an error response that had been attached in the png image. Please help me with this issue
![download](https://user-images.githubusercontent.com/59189839/96956558-0c9cd280-1516-11eb-934a-467c368faaf1.png)
![Capture](https://user-images.githubusercontent.com/59189839/96956565-16bed100-1516-11eb-9a0d-3851e9f35be6.PNG)

**Comment by fangohr** [comment]
Can you attach a python file or notebook with the code above, and which produces the error you report? That will make it easier to experiment and investigate your issue. Thanks!

**Comment by marijanbeg** [comment]
Hi @Harry-09, thank you for your question and for using Ubermag. You have `m_random` function defined, which returns a vector with three random components. You pass that function to `norm` argument in when you define the field. Please note that `norm` can be interpreted as saturation magnetisation Ms and it has to be scalar - not a vector. Also, please double-check whether you need a random Ms at all.

I am going to close this issue now, but please feel free to continue the discussion or raise new issues :)

**Comment by Harry-09** [comment]
Thanks for the your valuable answers @fangohr and @marijanbeg, if then How to initialize a random Magnetization inside area of 1umX1um? Please help me with it.
![Untitled](https://user-images.githubusercontent.com/59189839/96998555-43440e80-1551-11eb-9b96-9ff1b155dae9.png)

**Comment by marijanbeg** [comment]
Hi @Harry-09, thank you for the notebook. `m_init` function would be:

```
def m_init(point):
    if 0.5e-6 < x < 1.5e-6 and 0.5e-6 < x < 1.5e-6:  # inside the cube
        return [2*random.random()-1 for I in range(3)]
    else:  # outside the cube
        return (0, 0, 1)  # here you define what magnetisation should be outside the cube
```

I hope this helps. If not, please let us know.

**Comment by Harry-09** [comment]
Yeah thank you so much @fangohr, It helped in defining the magnetization though but couldn't able to minimize the magnetization an error occurred in it. Please kindly look into the attached file.
![image](https://user-images.githubusercontent.com/59189839/97080898-62f43900-161c-11eb-9f03-0a35317eb2bc.png)

**Comment by Harry-09** [comment]
I even updated the ubermag and did some installation test too after looking into the issue raised by #63 in ubermag/workshop.

**Comment by marijanbeg** [comment]
Hi @Harry-09, can you please send me the notebook (`.ipynb` file). You can attach it here (drag & drop). I can then investigate what went wrong.

**Comment by Harry-09** [comment]
Actually i couldn't able to attach the .ipynb file, since that doesn't support attaching here. so I had attached a pdf file. Please find it
[Random_mag.pdf](https://github.com/ubermag/help/files/5432845/Random_mag.pdf)

**Comment by marijanbeg** [comment]
Thanks. I think the discretisation you have is too fine and OOMMF probably crashes because of that (your sample is 2x2 microns).

I attach the modified notebook.

[debug-notebook.pdf](https://github.com/ubermag/help/files/5432862/debug-notebook.pdf)

**Comment by Harry-09** [comment]
Thank you for the reply @marijanbeg, I think the problem with the Tcl_runner, if i use docker_runner was able to obtain the output.
