### ISSUE TITLE
How to add a spatially varying sinc field in oommfc

### ISSUE THREAD

**Issue by yuanshh** [ubermag/help#95]
Dear ubermag team,
I want to excite a system in a small region with a signal based on the sinc function. But when i add this field as follows:
![H_sinc](https://user-images.githubusercontent.com/64522903/97798853-f2c16500-1c64-11eb-95ea-56170602d991.png)

However, it returns:
![error](https://user-images.githubusercontent.com/64522903/97798870-14bae780-1c65-11eb-8b96-3e3f7cb9a62d.png)

I want to know what is the problem with my code and how to add a spatially varying sinc field correctly.

**Comment by catrevil** [comment]
Hi @yuanshh,

Can you please post your `w-k.py` file? It seems that the problem is within that file, and it is not clear to me how your first image of a code block feeds into the issue you are experiencing from `w-k.py`. Thanks!

**Comment by yuanshh** [comment]
Dear @catrevil ,
Thanks for your response! This is my w-k.py file.
[w-k.zip](https://github.com/ubermag/help/files/5504343/w-k.zip)
Looking forward to your reply.

**Comment by marijanbeg** [comment]
Hi @yuanshh, thank you for using Ubermag. External magnetic fields which vary both in space and time are not supported at the moment - this is something we plan to add in the next release.

**Comment by marijanbeg** [comment]
Hi @yuanshh, thank you so much for your patience - Ubermag 0.50 is out and provides this functionality.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/space-time-field.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.
