### ISSUE TITLE
First order reversal curves (FORC) simulation

### ISSUE THREAD

**Issue by daavera** [ubermag/help#96]
Hello! Thanks again to the entire Ubermag team.

I am trying to simulate the FORC curve set for my system. However, when applying a gradually decreasing field, I only get two reversibility curves.

I was wondering if anyone has done this kind of simulation before and has any idea of what might be going on.

Thanks for any help!

- This is the field that I'm applying:

```python
max_m = 1.
min_m = 0.2
res = 0.05
cambio = 0.02

B_array = np.arange(max_m, min_m,-res)

for i in np.arange(0.0, 1.2, cambio):
    B_array = np.append(B_array, np.arange(min_m, max_m,res))
    min_m = min_m-cambio
    B_array = np.append(B_array, np.arange(max_m, min_m,-res))
B_array = np.append(B_array, np.arange(-1, 1.05, res))
```

- And this is the loop that I'm using for de the simulation:

```python
def hysteresis(system, B):
    M = [] #valores promedio del campo magnético
    x = np.arange(0,np.size(B),1) #contador
    for B_i, i in zip(B, x):
        # Actualización del campo magnético
        system.energy.zeeman.H = (B_i/mm.consts.mu0, 0, 0) #Zeeman energy term takes H instead of B.
        md.drive(system) #minimizar el torque del sistema
        M.append(system.m.orientation.average)
        print(i) #contador
    M = np.array(M)
    return M
```

**Comment by marijanbeg** [comment]
Hi @daavera, thank you for using Ubermag. The code you sent us seems to be ok for simulating hysteresis and I suspect the issue you have is probably due to the model of the system you use (geometry, energy equation, etc.).

**Comment by marijanbeg** [comment]
Hi @daavera, could you please update us on this issue? Have you managed to resolve it? If yes, could you please let us know what the issue was?

**Comment by marijanbeg** [comment]
I am going to assume this issue is now resolved. If not, please open a new issue.
