### ISSUE TITLE
Hysteresis for different frequencies 

### ISSUE THREAD

**Issue by BobClok** [ubermag/help#97]
Hello! Thanks to the Ubermag team for all their work.

In some previous issues I have seen the method to generate hysteresis curves. However, I still don't know how to include the frequency of the applied field in those simulations.

I would like to simulate something like what is in the image. Does anyone have any hints how I can achieve this?

![Captura de Pantalla 2020-11-26 a la(s) 12 02 31 a  m](https://user-images.githubusercontent.com/75058858/100310676-b808cf00-2f7b-11eb-8179-35cbaaa8bfd2.png)

**Comment by marijanbeg** [comment]
Hi @BobClok, thank you so much for your patience. I am not sure I understood right from your question what you are trying to simulate, but I made a short tutorial which shows how to plot M vs. H when H is a sine-field.

Please update Ubermag (`conda update ubermag`) and have a look at this tutorial: https://github.com/ubermag/workshop/blob/master/tutorials/sine-hysteresis.ipynb

Please note that there are many new functionalities and (some minor) changes in the interface, so you might want to have a look at other tutorials as well.

If you require any further support, please raise an issue in this repository, and we would be happy to address it.
