### ISSUE TITLE
The exchange energy equation is inconsistent

### ISSUE THREAD

**Issue by code-whale** [ubermag/help#98]
Dear Ubermag team,
I type````system.energy```` in simulation, but I found that there is a symbol in front of the exchange displayed, which is not consistent with what you have shown in the tutorial. Can you tell me why?
![image](https://user-images.githubusercontent.com/61874432/101165491-b58c3080-3671-11eb-8f02-bbad0c5ee026.png)

**Comment by marijanbeg** [comment]
Hi @code-whale, there should be minus sign as a part of the exchange energy term. If you have seen a plus sign somewhere in the tutorials, then this is a mistake. Plus sign is when the exchange energy term is written using squared gradients. I hope this answers your question. If not, please let me know.

**Comment by code-whale** [comment]
@marijanbeg ,Thank you very much for your help! I will continue to learn about micromagnetism to help understand some phenomena in the simulation. If you can, can you tell me some books about micromagnetism or atomic spin? Because when I read the literature, I often see a lot of formulas and modeling that I don't understand. Thank you again for your kind help!
