### ISSUE TITLE
Subtracting magnetisation fields at different slices along a nanowire

### ISSUE THREAD

**Issue by askeyjw** [ubermag/help#99]
Hello, just wondering if it is possible to subtract magnetisation field slices at different points along an object? For example, I am simulating a NW of length 100nm and diameter 10nm, centred around the origin (so we have -50 to 50nm along x, and -5 to 5nm in y and z planes) and want to subtract a slice at the end of the wire in the yz plane, say at -45nm (so m.orientation.plane(x=-45e-9) ) from a slice in the middle of the wire say at 0nm (so m.orientation.plane('x')). When I do this I get an error message that I cannot subtract fields defined on different meshes but I do not understand how these can be different meshes when the slices are taken along different x-positions on the same wire and so I would assume that it is the same mesh. 

Essentially I am trying to take surface integrals of the magnetisation field and like the convenience functionality of surface_integral, so would like to try and keep everything in terms of the magnetisation field. I think it would be possible to subtract the two values if I converted them into arrays but then I would be stuck with numpy arrays which then means I would have to find a method of taking the surface integral of a numpy array for a 3D vector field on a 3D coordinate space. 

I feel like I'm being stupid but any help with this potentially silly question would be greatly appreciated. Thanks again for all the work on creating and maintaining this micromagnetics package. - Joe

**Comment by marijanbeg** [comment]
Hi @askeyjw, thank you for your question. Here is the explanation of the issue you encountered: Field is defined on a mesh, and mesh is defined in a region. The region is uniquely defined by points p1 and p2. So, in order for two meshes to be the same, they must not only have the same disretisation (`n`), but also be positioned in the same place in space.

If we allowed operations between fields defined in different regions of space but on the same disretisation, the question would be: "What would be the spatial coordinates of the resulting field?"

You can resolve this issue like this (after you decide what are the coordinates of the resulting mesh):
```
f1 = m.orientation.plane(x=-45e-9)
f2 = m.orientation.plane('x')

# I assume here that you want the resulting field to have the same mesh as f1
res = df.Field(f1.mesh, dim=3, value=f1.value-f2.value)

I hope this helps. If not, please feel free to reopen the issue.
```

**Comment by askeyjw** [comment]
Hello @marijanbeg thank you so much for this response. This has solved my problem for me, though I found that value=f1.value-f2.value always tends to give zero, so I replaced .value with .array and this works as intended. 

Thanks again! 
Joe

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.
